DROP TABLE IF EXISTS `PublicFacingData`.`SchoolScores`;

CREATE TABLE `PublicFacingData`.`SchoolScores` (
	`UNITID` INT NOT NULL,
	`INSTNM` VARCHAR(255) NOT NULL,
	`STATE` VARCHAR(2) NOT NULL,
	`INSTFUNDINGTYPE` VARCHAR(2) NOT NULL,
	`LEADERSHIP` INT NOT NULL,
	`POLICIES` INT NOT NULL,
	`SAFETY` INT NOT NULL,
	`DIVERSITY` INT NOT NULL,
	PRIMARY KEY (`UNITID`)
);