USE PublicFacingData;

-- NOTE: This is a temporary fix while finalized merge script is not available

DROP TABLE IF EXISTS SchoolData;

CREATE TABLE SchoolData AS
SELECT *
FROM merged_ipeds_css_irs.GenderFair2024;

/*

DROP TABLE IF EXISTS SchoolData;

CREATE TABLE SchoolData (
    `UNITID` INT PRIMARY KEY,
    `INSTNM` VARCHAR(255),
    `EIN` INT,
    `OPEID` INT,
    `STATE` VARCHAR(2),
    `INSTFUNDINGTYPE` VARCHAR(2),
    `DEGREETOT` INT,
    `ENROLLTOT` INT,
    `HASDAYCARE` INT,
    `ACADEMICPOPM` INT,
    `ACADEMICPOPF` INT,
    `SALARYTOTM` INT,
    `SALARYTOTF` INT,
    `SALARYPPM` DOUBLE,
    `SALARYPPF` DOUBLE,
    `NONACD_BLKPCT` DOUBLE,
    `NONACD_HSPPCT` DOUBLE,
    `NONACD_ASIAPCT` DOUBLE,
    `PROFWOMENPCT` DOUBLE,
    `ASSOCPROFWOMENPCT` DOUBLE,
    `TENUREWOMENPCT` DOUBLE,
    `BLACKPROFWOMENPCT` DOUBLE,
    `BLACKASSOCPROFWOMENPCT` DOUBLE,
    `BLACKTENUREWOMENPCT` DOUBLE,
    `HISPANICPROFWOMENPCT` DOUBLE,
    `HISPANICASSOCPROFWOMENPCT` DOUBLE,
    `HISPANICTENUREWOMENPCT` DOUBLE,
    `ASIANPROFWOMENPCT` DOUBLE,
    `ASIANASSOCPROFWOMENPCT` DOUBLE,
    `ASIANTENUREWOMENPCT` DOUBLE,
    `YEARLYHATECRIME` DOUBLE,
    `YEARLYHATECRIME1K` DOUBLE,
    `YEARLYVAWA` DOUBLE,
    `YEARLYVAWA1K` DOUBLE,
    `IRS_MONTH` VARCHAR(3),
    `YEAR` INT,
    `PERCENTAGE_WOMEN_TRUSTEES` DOUBLE,
    `PERCENTAGE_WOMEN_KEY_EMPLOYEES` DOUBLE,
    `WHISTLEBLOWER_POLICY` TINYINT(1),
    `CEO_REVIEWED_COMPENSATION` TINYINT(1),
    `OTHER_REVIEWED_COMPENSATION` TINYINT(1),
    `MALE_TO_FEMALE_PAY_RATIO` DOUBLE,
    `PRESIDENT_TO_AVERAGE_PAY_RATIO` DOUBLE
);

INSERT INTO SchoolData (`GROUP`, `ABBR`, `DESC`)
SELECT 1, Codevalue, LEFT(valueLabel, 100) FROM ipeds_2024_db.valuesets22
	where varName = "STABBR"
	order by Codevalue;


SELECT * FROM `SchoolData`;