DROP TABLE IF EXISTS `PublicFacingData`.`SchoolData_v2`;

-- Create Table w/ Concrete Dtype --
CREATE TABLE `PublicFacingData`.`SchoolData_v2` (
	UNITID INT PRIMARY KEY,
	INSTNM varchar(255), 
	STATE varchar(2), 
	EIN varchar(10), 
	OPEID varchar(10), 
	DEGREETOT INT, 
	ENROLLTOT INT, 
	INSTFUNDINGTYPE INT, 
	HASDAYCARE INT, 
	ACDPOPM INT, 
	ACDPOPF INT, 
	SALARYTOTACDM INT, 
	SALARYTOTACDF INT,
	ACDTOTMEN INT, 
	ACDTOTWOMEN INT, 
	ACDTOTWHIT INT, 
	ACDTOTBLAK INT, 
	ACDTOTASIA INT, 
	ACDTOTHISP INT, 
	ACDTOTNHPI INT, 
	ACDTOTNAMC INT, 
	ACDTOTNRES INT, 
	ACDTOTTWOP INT, 
	ACDTOTUNKN INT, 
	PROFMEN INT,
	PROFWOMEN INT, 
	PROFWHIT INT, 
	PROFBLAK INT, 
	PROFASIA INT, 
	PROFHISP INT, 
	PROFNHPI INT, 
	PROFNAMC INT, 
	PROFNRES INT, 
	PROFTWOP INT, 
	PROFUNKN INT, 
	ASSOCIATEPROFMEN INT, 
	ASSOCIATEPROFWOMEN INT, 
	ASSOCIATEPROFWHIT INT, 
	ASSOCIATEPROFBLAK INT, 
	ASSOCIATEPROFASIA INT, 
	ASSOCIATEPROFHISP INT, 
	ASSOCIATEPROFNHPI INT, 
	ASSOCIATEPROFNAMC INT, 
	ASSOCIATEPROFNRES INT, 
	ASSOCIATEPROFTWOP INT, 
	ASSOCIATEPROFUNKN INT, 
	ASSISTANTPROFMEN INT, 
	ASSISTANTPROFWOMEN INT, 
	ASSISTANTPROFWHIT INT, 
	ASSISTANTPROFBLAK INT, 
	ASSISTANTPROFASIA INT, 
	ASSISTANTPROFHISP INT, 
	ASSISTANTPROFNHPI INT, 
	ASSISTANTPROFNAMC INT, 
	ASSISTANTPROFNRES INT, 
	ASSISTANTPROFTWOP INT, 
	ASSISTANTPROFUNKN INT, 
	INSTRUCTORMEN INT, 
	INSTRUCTORWOMEN INT, 
	INSTRUCTORWHIT INT, 
	INSTRUCTORBLAK INT, 
	INSTRUCTORASIA INT, 
	INSTRUCTORHISP INT, 
	INSTRUCTORNHPI INT, 
	INSTRUCTORNAMC INT, 
	INSTRUCTORNRES INT, 
	INSTRUCTORTWOP INT, 
	INSTRUCTORUNKN INT, 
	LECTURERMEN INT, 
	LECTURERWOMEN INT, 
	LECTURERWHIT INT, 
	LECTURERBLAK INT, 
	LECTURERASIA INT, 
	LECTURERHISP INT, 
	LECTURERNHPI INT, 
	LECTURERNAMC INT, 
	LECTURERNRES INT, 
	LECTURERTWOP INT, 
	LECTURERUNKN INT, 
	NONACDMEN INT,
	NONACDWOMEN INT,
	NONACDWHIT INT, 
	NONACDBLAK INT, 
	NONACDASIA INT, 
	NONACDHISP INT, 
	NONACDNHPI INT, 
	NONACDNAMC INT, 
	NONACDNRES INT, 
	NONACDTWOP INT, 
	NONACDUNKN INT,
	CSSPOPULATION INT, 
	YEARLYHATECRIME INT, 
	YEARLYHATECRIME1K decimal(53,4), 
	YEARLYVAWA INT,
	YEARLYVAWA1K decimal(42,4), 
	WHISTLEBLOWER_POLICY tinyint(1), 
	CEO_REVIEWED_COMPENSATION tinyint(1), 
	OTHER_REVIEWED_COMPENSATION tinyint(1) 
);

-- Dtype Documentation --
/*
Metadata          				Original dtype      Aggregated dtype
UNITID							INT					INT	
INSTNM							VARCHAR(255)		VARCHAR(255)
STATE							VARCHAR(2)			VARCHAR(2)
EIN								VARCHAR(10)			VARCHAR(10)
OPEID							VARCHAR(10)			VARCHAR(10)
DEGREETOT						INT					INT
ENROLLTOT						INT					INT
INSTFUNDINGTYPE					INT					INT
HASDAYCARE						INT					INT
ACDPOPM							INT					INT
ACDPOPF							INT					INT
SALARYTOTACDM					INT					INT
SALARYTOTACDF					INT					INT
ACDTOTMEN						INT					INT
ACDTOTWOMEN 					INT					INT
ACDTOTWHIT						INT					INT
ACDTOTBLAK						INT					INT
ACDTOTASIA						INT					INT
ACDTOTHISP						INT					INT
ACDTOTNHPI						INT					INT
ACDTOTNAMC						INT					INT
ACDTOTNRES						INT					INT
ACDTOTTWOP						INT					INT
ACDTOTUNKN 						INT					INT
PROFMEN							INT					INT
PROFWOMEN 						INT					INT
PROFWHIT 						INT					INT
PROFBLAK 						INT					INT
PROFASIA 						INT					INT
PROFHISP 						INT					INT
PROFNHPI 						INT					INT
PROFNAMC 						INT					INT
PROFNRES 						INT					INT
PROFTWOP 						INT					INT
PROFUNKN 						INT					INT
ASSOCIATEPROFMEN 				INT					INT
ASSOCIATEPROFWOMEN 				INT					INT
ASSOCIATEPROFWHIT				INT					INT
ASSOCIATEPROFBLAK 				INT					INT
ASSOCIATEPROFASIA 				INT					INT
ASSOCIATEPROFHISP 				INT					INT
ASSOCIATEPROFNHPI 				INT					INT
ASSOCIATEPROFNAMC 				INT					INT
ASSOCIATEPROFNRES 				INT					INT
ASSOCIATEPROFTWOP 				INT					INT
ASSOCIATEPROFUNKN 				INT					INT
ASSISTANTPROFMEN 				INT					INT
ASSISTANTPROFWOMEN 				INT					INT
ASSISTANTPROFWHIT 				INT					INT
ASSISTANTPROFBLAK 				INT					INT
ASSISTANTPROFASIA 				INT					INT
ASSISTANTPROFHISP 				INT					INT
ASSISTANTPROFNHPI 				INT					INT
ASSISTANTPROFNAMC 				INT					INT
ASSISTANTPROFNRES 				INT					INT
ASSISTANTPROFTWOP 				INT					INT
ASSISTANTPROFUNKN 				INT					INT
INSTRUCTORMEN					INT					INT
INSTRUCTORWOMEN 				INT					INT
INSTRUCTORWHIT 					INT					INT
INSTRUCTORBLAK 					INT					INT
INSTRUCTORASIA 					INT					INT
INSTRUCTORHISP 					INT					INT
INSTRUCTORNHPI 					INT					INT
INSTRUCTORNAMC 					INT					INT
INSTRUCTORNRES 					INT					INT
INSTRUCTORTWOP 					INT					INT
INSTRUCTORUNKN 					INT					INT
LECTURERMEN						INT					INT
LECTURERWOMEN 					INT					INT
LECTURERWHIT 					INT					INT
LECTURERBLAK 					INT					INT
LECTURERASIA 					INT					INT
LECTURERHISP 					INT					INT
LECTURERNHPI 					INT					INT
LECTURERNAMC 					INT					INT
LECTURERNRES 					INT					INT
LECTURERTWOP 					INT					INT
LECTURERUNKN 					INT					INT
NONACDMEN						INT					INT
NONACDWOMEN 					INT					INT
NONACDWHIT 						INT					INT
NONACDBLAK 						INT					INT
NONACDASIA 						INT					INT
NONACDHISP 						INT					INT
NONACDNHPI 						INT					INT
NONACDNAMC 						INT					INT
NONACDNRES 						INT					INT
NONACDTWOP						INT					INT
NONACDUNKN 						INT					INT
CSSPOPULATION 					INT					INT
YEARLYHATECRIME 				INT					INT
YEARLYHATECRIME1K				N/A					decimal(53,4)
YEARLYVAWA						INT					INT
YEARLYVAWA1K 					N/A					decimal(42,4)
WHISTLEBLOWER_POLICY 			tinyint(1)			tinyint(1)
CEO_REVIEWED_COMPENSATION 		tinyint(1)			tinyint(1)
OTHER_REVIEWED_COMPENSATION		tinyint(1)			tinyint(1)

Note that only YEARLYHATECRIME1K and YEARLYVAWA1K are new metadata that has no original dtype, 
and their aggregated dtype in SchoolData table is defaulted by the database.

Every other metadata shares the same aggregated dtype as their original.

Also note that metadata UNITID, EIN, and OPEID should not be null or empty.
*/