DROP TABLE IF EXISTS `PublicFacingData`.`SchoolData_v2`;

-- Create Table w/ Concrete Dtype --
CREATE TABLE `PublicFacingData`.`SchoolData_v2` (
	UNITID INT PRIMARY KEY,
	INSTNM varchar(255) NOT NULL,
	STATE varchar(2) NOT NULL,
	EIN varchar(10) NOT NULL,
	OPEID varchar(10) NOT NULL,
	DEGREETOT INT NOT NULL,
	ENROLLTOT INT NOT NULL,
	INSTFUNDINGTYPE INT NOT NULL,
	HASDAYCARE INT NOT NULL,
	ACDPOPM INT NOT NULL,
	ACDPOPF INT NOT NULL,
	SALARYTOTACDM INT NOT NULL,
	SALARYTOTACDF INT NOT NULL,
	ACDTOTMEN INT NOT NULL,
	ACDTOTWOMEN INT NOT NULL,
	ACDTOTWHIT INT NOT NULL,
	ACDTOTBLAK INT NOT NULL,
	ACDTOTASIA INT NOT NULL,
	ACDTOTHISP INT NOT NULL,
	ACDTOTNHPI INT NOT NULL,
	ACDTOTNAMC INT NOT NULL,
	ACDTOTNRES INT NOT NULL,
	ACDTOTTWOP INT NOT NULL,
	ACDTOTUNKN INT NOT NULL,
	PROFMEN INT NOT NULL,
	PROFWOMEN INT NOT NULL,
	PROFWHIT INT NOT NULL,
	PROFBLAK INT NOT NULL,
	PROFASIA INT NOT NULL,
	PROFHISP INT NOT NULL,
	PROFNHPI INT NOT NULL,
	PROFNAMC INT NOT NULL,
	PROFNRES INT NOT NULL,
	PROFTWOP INT NOT NULL,
	PROFUNKN INT NOT NULL,
	ASSOCIATEPROFMEN INT NOT NULL,
	ASSOCIATEPROFWOMEN INT NOT NULL,
	ASSOCIATEPROFWHIT INT NOT NULL,
	ASSOCIATEPROFBLAK INT NOT NULL,
	ASSOCIATEPROFASIA INT NOT NULL,
	ASSOCIATEPROFHISP INT NOT NULL,
	ASSOCIATEPROFNHPI INT NOT NULL,
	ASSOCIATEPROFNAMC INT NOT NULL,
	ASSOCIATEPROFNRES INT NOT NULL,
	ASSOCIATEPROFTWOP INT NOT NULL,
	ASSOCIATEPROFUNKN INT NOT NULL,
	ASSISTANTPROFMEN INT NOT NULL,
	ASSISTANTPROFWOMEN INT NOT NULL,
	ASSISTANTPROFWHIT INT NOT NULL,
	ASSISTANTPROFBLAK INT NOT NULL,
	ASSISTANTPROFASIA INT NOT NULL,
	ASSISTANTPROFHISP INT NOT NULL,
	ASSISTANTPROFNHPI INT NOT NULL,
	ASSISTANTPROFNAMC INT NOT NULL,
	ASSISTANTPROFNRES INT NOT NULL,
	ASSISTANTPROFTWOP INT NOT NULL,
	ASSISTANTPROFUNKN INT NOT NULL,
	INSTRUCTORMEN INT NOT NULL,
	INSTRUCTORWOMEN INT NOT NULL,
	INSTRUCTORWHIT INT NOT NULL,
	INSTRUCTORBLAK INT NOT NULL,
	INSTRUCTORASIA INT NOT NULL,
	INSTRUCTORHISP INT NOT NULL,
	INSTRUCTORNHPI INT NOT NULL,
	INSTRUCTORNAMC INT NOT NULL,
	INSTRUCTORNRES INT NOT NULL,
	INSTRUCTORTWOP INT NOT NULL,
	INSTRUCTORUNKN INT NOT NULL,
	LECTURERMEN INT NOT NULL,
	LECTURERWOMEN INT NOT NULL,
	LECTURERWHIT INT NOT NULL,
	LECTURERBLAK INT NOT NULL,
	LECTURERASIA INT NOT NULL,
	LECTURERHISP INT NOT NULL,
	LECTURERNHPI INT NOT NULL,
	LECTURERNAMC INT NOT NULL,
	LECTURERNRES INT NOT NULL,
	LECTURERTWOP INT NOT NULL,
	LECTURERUNKN INT NOT NULL,
	NONACDMEN INT NOT NULL,
	NONACDWOMEN INT NOT NULL,
	NONACDWHIT INT NOT NULL,
	NONACDBLAK INT NOT NULL,
	NONACDASIA INT NOT NULL,
	NONACDHISP INT NOT NULL,
	NONACDNHPI INT NOT NULL,
	NONACDNAMC INT NOT NULL,
	NONACDNRES INT NOT NULL,
	NONACDTWOP INT NOT NULL,
	NONACDUNKN INT NOT NULL,
	CSSPOPULATION INT NOT NULL,
	YEARLYHATECRIME INT NOT NULL,
	YEARLYHATECRIME1K DOUBLE NOT NULL,
	YEARLYVAWA INT NOT NULL,
	YEARLYVAWA1K DOUBLE NOT NULL,
	WHISTLEBLOWER_POLICY tinyint(1),
	CEO_REVIEWED_COMPENSATION tinyint(1),
	OTHER_REVIEWED_COMPENSATION tinyint(1) 
);

-- Dtype Documentation --
/*
Metadata          				Original dtype      Aggregated dtype
UNITID							INT					INT	
INSTNM							VARCHAR(255)		VARCHAR(255)
STATE							VARCHAR(2)			VARCHAR(2)
EIN								VARCHAR(10)			VARCHAR(10)
OPEID							VARCHAR(10)			VARCHAR(10)
DEGREETOT						INT					INT
ENROLLTOT						INT					INT
INSTFUNDINGTYPE					INT					INT
HASDAYCARE						INT					INT
ACDPOPM							INT					INT
ACDPOPF							INT					INT
SALARYTOTACDM					INT					INT
SALARYTOTACDF					INT					INT
ACDTOTMEN						INT					INT
ACDTOTWOMEN 					INT					INT
ACDTOTWHIT						INT					INT
ACDTOTBLAK						INT					INT
ACDTOTASIA						INT					INT
ACDTOTHISP						INT					INT
ACDTOTNHPI						INT					INT
ACDTOTNAMC						INT					INT
ACDTOTNRES						INT					INT
ACDTOTTWOP						INT					INT
ACDTOTUNKN 						INT					INT
PROFMEN							INT					INT
PROFWOMEN 						INT					INT
PROFWHIT 						INT					INT
PROFBLAK 						INT					INT
PROFASIA 						INT					INT
PROFHISP 						INT					INT
PROFNHPI 						INT					INT
PROFNAMC 						INT					INT
PROFNRES 						INT					INT
PROFTWOP 						INT					INT
PROFUNKN 						INT					INT
ASSOCIATEPROFMEN 				INT					INT
ASSOCIATEPROFWOMEN 				INT					INT
ASSOCIATEPROFWHIT				INT					INT
ASSOCIATEPROFBLAK 				INT					INT
ASSOCIATEPROFASIA 				INT					INT
ASSOCIATEPROFHISP 				INT					INT
ASSOCIATEPROFNHPI 				INT					INT
ASSOCIATEPROFNAMC 				INT					INT
ASSOCIATEPROFNRES 				INT					INT
ASSOCIATEPROFTWOP 				INT					INT
ASSOCIATEPROFUNKN 				INT					INT
ASSISTANTPROFMEN 				INT					INT
ASSISTANTPROFWOMEN 				INT					INT
ASSISTANTPROFWHIT 				INT					INT
ASSISTANTPROFBLAK 				INT					INT
ASSISTANTPROFASIA 				INT					INT
ASSISTANTPROFHISP 				INT					INT
ASSISTANTPROFNHPI 				INT					INT
ASSISTANTPROFNAMC 				INT					INT
ASSISTANTPROFNRES 				INT					INT
ASSISTANTPROFTWOP 				INT					INT
ASSISTANTPROFUNKN 				INT					INT
INSTRUCTORMEN					INT					INT
INSTRUCTORWOMEN 				INT					INT
INSTRUCTORWHIT 					INT					INT
INSTRUCTORBLAK 					INT					INT
INSTRUCTORASIA 					INT					INT
INSTRUCTORHISP 					INT					INT
INSTRUCTORNHPI 					INT					INT
INSTRUCTORNAMC 					INT					INT
INSTRUCTORNRES 					INT					INT
INSTRUCTORTWOP 					INT					INT
INSTRUCTORUNKN 					INT					INT
LECTURERMEN						INT					INT
LECTURERWOMEN 					INT					INT
LECTURERWHIT 					INT					INT
LECTURERBLAK 					INT					INT
LECTURERASIA 					INT					INT
LECTURERHISP 					INT					INT
LECTURERNHPI 					INT					INT
LECTURERNAMC 					INT					INT
LECTURERNRES 					INT					INT
LECTURERTWOP 					INT					INT
LECTURERUNKN 					INT					INT
NONACDMEN						INT					INT
NONACDWOMEN 					INT					INT
NONACDWHIT 						INT					INT
NONACDBLAK 						INT					INT
NONACDASIA 						INT					INT
NONACDHISP 						INT					INT
NONACDNHPI 						INT					INT
NONACDNAMC 						INT					INT
NONACDNRES 						INT					INT
NONACDTWOP						INT					INT
NONACDUNKN 						INT					INT
CSSPOPULATION 					INT					INT
YEARLYHATECRIME 				INT					INT
YEARLYHATECRIME1K				N/A					DOUBLE
YEARLYVAWA						INT					INT
YEARLYVAWA1K 					N/A					DOUBLE
WHISTLEBLOWER_POLICY 			tinyint(1)			tinyint(1)
CEO_REVIEWED_COMPENSATION 		tinyint(1)			tinyint(1)
OTHER_REVIEWED_COMPENSATION		tinyint(1)			tinyint(1)

Note that only YEARLYHATECRIME1K and YEARLYVAWA1K are new metadata that has no original dtype,
and their aggregated dtype in SchoolData table is defaulted by the database.

Every other metadata shares the same aggregated dtype as their original.

Also note that metadata UNITID,EIN,and OPEID should not be null or empty.
*/