USE PublicFacingData;

DROP PROCEDURE IF EXISTS GetAverages;
DROP PROCEDURE IF EXISTS GetMetadata;
DROP PROCEDURE IF EXISTS GetSchoolScores;
DROP PROCEDURE IF EXISTS GetSchoolData;

delimiter $$

CREATE PROCEDURE GetAverages ()
BEGIN
	SELECT "AveragePayMen" as "Name", sum(SALARYTOTM)/sum(ACADEMICPOPM) as "Value" FROM SchoolData
	UNION ALL
	SELECT "AveragePayWomen" as "Name", sum(SALARYTOTF)/sum(ACADEMICPOPF) as "Value" FROM SchoolData
	UNION ALL
	SELECT "AverageHateCrime" as "Name", sum(YEARLYHATECRIME)/sum(ENROLLTOT)*1000 as "Value" FROM SchoolData
	UNION ALL
	SELECT "AverageVAWA" as "Name", sum(YEARLYVAWA)/sum(ENROLLTOT)*1000 as "Value" FROM SchoolData;
END$$



CREATE PROCEDURE GetMetadata ()
BEGIN
	SELECT `GROUP`, `ABBR`, `DESC`
	FROM Metadata;
END$$



CREATE PROCEDURE GetSchoolScores ()
BEGIN
	SELECT UNITID, INSTNM, STATE, LEADERSHIP, POLICIES, SAFETY, DIVERSITY
	FROM SchoolScores;
END$$



-- The implementation of GetSchoolData uses a varchar for the string of school UNITIDs to allow querying a variable number of schools.
-- Note that in current implementation school data is only fetched one at a time.
CREATE PROCEDURE GetSchoolData (IN UnitIDs VARCHAR(10000))
BEGIN
    IF TRIM(UnitIDs) = '' THEN
        SELECT 'No UNITIDs provided. Returning no results.' AS Message;
	ELSE
		If UnitIDs REGEXP '^[0-9, ]*$' THEN
			SET @query = CONCAT('SELECT UNITID,INSTNM,EIN,OPEID,STATE,DEGREETOT,ENROLLTOT,INSTFUNDINGTYPE,HASDAYCARE,ACADEMICPOPM,ACADEMICPOPF,
            SALARYTOTM,SALARYTOTF,SALARYPPM,SALARYPPF,NONACD_BLKPCT,NONACD_HSPPCT,NONACD_ASIAPCT,PROFWOMENPCT,ASSOCPROFWOMENPCT,TENUREWOMENPCT,
            BLACKPROFWOMENPCT,BLACKASSOCPROFWOMENPCT,BLACKTENUREWOMENPCT,HISPANICPROFWOMENPCT,HISPANICASSOCPROFWOMENPCT,HISPANICTENUREWOMENPCT,
            ASIANPROFWOMENPCT,ASIANASSOCPROFWOMENPCT,ASIANTENUREWOMENPCT,YEARLYHATECRIME,YEARLYHATECRIME1K,YEARLYVAWA,YEARLYVAWA1K,IRS_MONTH,
            YEAR,PERCENTAGE_WOMEN_TRUSTEES,PERCENTAGE_WOMEN_KEY_EMPLOYEES,WHISTLEBLOWER_POLICY,CEO_REVIEWED_COMPENSATION,OTHER_REVIEWED_COMPENSATION,
            MALE_TO_FEMALE_PAY_RATIO,PRESIDENT_TO_AVERAGE_PAY_RATIO
			from PublicFacingData.SchoolData WHERE UNITID IN (', UnitIDs, ');');
			PREPARE stmt FROM @query;
			EXECUTE stmt;
			DEALLOCATE PREPARE stmt;
		ELSE 
			SELECT 'String validation by \'^[0-9, ]*$\' failed. Returning no results.' AS Message;
		END IF;
	END IF;
END$$

delimiter ;

CALL GetAverages();
CALL GetMetadata();
CALL GetSchoolScores();
CALL GetSchoolData("");
CALL GetSchoolData("   1, 2,3   , -576   , 681,    66984133,-768913,-100706,3578");
CALL GetSchoolData("100654, 100706, 100751, 101301); Malicious query capable of injection");
CALL GetSchoolData("100654    ,     100706   ,   100751,     101301   ");
CALL GetSchoolData("100654, 100706, 100751, 101301");