-- Main Query --
CREATE TABLE `merged_ipeds_css_irs`.`gf2024_final` AS
-- CTEs --
WITH css_hate_temp1 AS (
SELECT 
    OPEID,
    MIN(Total) AS Total,
    (	SUM(MURD20) +
		SUM(RAPE20) +
		SUM(FOND20) +
		SUM(INCE20) +
		SUM(STAT20) +
		SUM(ROBBE20) +
		SUM(AGG_A20) +
		SUM(BURGLA20) +
		SUM(VEHIC20) +
		SUM(ARSON20) +
		SUM(SIM_A20) +
		SUM(LAR_T20) +
		SUM(INTIM20) +
		SUM(VANDAL20) +
		SUM(MURD21) +
		SUM(RAPE21) +
		SUM(FOND21) +
		SUM(INCE21) +
		SUM(STAT21) +
		SUM(ROBBE21) +
		SUM(AGG_A21) +
		SUM(BURGLA21) +
		SUM(VEHIC21) +
		SUM(ARSON21) +
		SUM(SIM_A21) +
		SUM(LAR_T21) +
		SUM(INTIM21) +
		SUM(VANDAL21) +
		SUM(MURD22) +
		SUM(RAPE22) +
		SUM(FOND22) +
		SUM(INCE22) +
		SUM(STAT22) +
		SUM(ROBBE22) +
		SUM(AGG_A22) +
		SUM(BURGLA22) +
		SUM(VEHIC22) +
		SUM(ARSON22) +
		SUM(SIM_A22) +
		SUM(LAR_T22) +
		SUM(INTIM22) +
		SUM(VANDAL22)	) / 3 AS YEARLYHATECRIME
FROM `css`.`css_hate`
GROUP BY OPEID),
css_hate_temp2 AS (
SELECT *, YEARLYHATECRIME * 1000 / NULLIF(Total, 0) AS YEARLYHATECRIME1K
FROM css_hate_temp1),
css_vawa_temp1 AS (
SELECT 
    OPEID, 
    MIN(Total) AS Total,  
    (	SUM(DOMEST20) +
		SUM(DATING20) +
		SUM(STALK20) +
		SUM(DOMEST21) +
		SUM(DATING21) +
		SUM(STALK21) +
		SUM(DOMEST22) +
		SUM(DATING22) +
		SUM(STALK22)	) / 3 AS YEARLYVAWA
FROM `css`.`css_vawa`
GROUP BY OPEID),
css_vawa_temp2 AS (
SELECT *, YEARLYVAWA * 1000 / NULLIF(Total, 0) AS YEARLYVAWA1K
FROM css_vawa_temp1),
ipeds_S2022_IS_temp AS (
SELECT
    UNITID,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAW ELSE 0 END) AS HRASIAW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPW ELSE 0 END) AS HRHISPW_101,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAW ELSE 0 END) AS HRASIAW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPW ELSE 0 END) AS HRHISPW_102,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAW ELSE 0 END) AS HRASIAW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPW ELSE 0 END) AS HRHISPW_200
FROM `ipeds_2024_db`.`S2022_IS`
WHERE `SISCAT` IN (101, 102, 200)
GROUP BY `UNITID`),
ipeds_S2022_OC_temp AS (
SELECT 
    UNITID,
    SUM(HRTOTLT) AS HRTOTLT,
    SUM(HRTOTLM) AS HRTOTLM,
    SUM(HRTOTLW) AS HRTOTLW,
    SUM(HRASIAT) AS HRASIAT,
    SUM(HRASIAM) AS HRASIAM,
    SUM(HRASIAW) AS HRASIAW,
    SUM(HRBKAAT) AS HRBKAAT,
    SUM(HRBKAAM) AS HRBKAAM,
    SUM(HRBKAAW) AS HRBKAAW,
    SUM(HRHISPT) AS HRHISPT,
    SUM(HRHISPM) AS HRHISPM,
    SUM(HRHISPW) AS HRHISPW
FROM `ipeds_2024_db`.`S2022_OC`
WHERE `OCCUPCAT` IN (220, 230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 420, 490)
GROUP BY UNITID),
ipeds_SAL2022_IS_temp AS (
SELECT *, 
  CASE 
    WHEN SAINSTM = 0 OR SAOUTLM = 0 THEN NULL
    ELSE SAOUTLM / SAINSTM 
  END AS AVGSALM,
  CASE 
    WHEN SAINSTW = 0 OR SAOUTLW = 0 THEN NULL
    ELSE SAOUTLW / SAINSTW 
  END AS AVGSALW
FROM `ipeds_2024_db`.`SAL2022_IS`
WHERE `ARANK` IN (7)),
ipeds_IC2022_temp AS (
SELECT *
FROM `ipeds_2024_db`.`IC2022`
WHERE (
    LEVEL3 = 1 OR
    LEVEL4 = 1 OR
    LEVEL5 = 1 OR
    LEVEL6 = 1 OR
    LEVEL7 = 1 OR
    LEVEL8 = 1 OR
    LEVEL17 = 1 OR
    LEVEL18 = 1 OR
    LEVEL19 = 1
) AND `CNTLAFFI` IN (1, 3, 4)),
ipeds_EF2022_temp AS (
SELECT * 
FROM `ipeds_2024_db`.`EF2022`
WHERE `EFLEVEL` IN (10)),
irs990_temp AS (
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY `EIN` 
               ORDER BY `YEAR` DESC, `IRS_MONTH` DESC
           ) AS rn
    FROM `irs990`.`Organizations`
) AS ranked
WHERE rn = 1)
-- Selecting columns --
SELECT
	a.UNITID AS UNITID,
    d.INSTNM AS INSTNM,
    d.STABBR AS STATE,
    d.EIN AS EIN,
    d.OPEID AS OPEID,
    a.CSTOTLT AS DEGREETOT,
    b.EFTOTAL AS ENROLLTOT,
    c.CNTLAFFI AS INSTFUNDINGTYPE,
    c.STUSRV8 AS HASDAYCARE,
    e.SAINSTM AS ACADEMICPOPM,
    e.SAINSTW AS ACADEMICPOPF,
    e.SAOUTLM AS SALARYTOTM,
    e.SAOUTLW AS SALARYTOTF,  
    e.AVGSALM AS SALARYPPM,
    e.AVGSALW AS SALARYPPF,
    f.HRBKAAT AS NONACD_BLKPCT,
    f.HRHISPT AS NONACD_HSPPCT,
    f.HRASIAT AS NONACD_ASIAPCT,
    g.HRTOTLW_101 AS PROFWOMENPCT,
    g.HRTOTLW_102 AS ASSOCPROFWOMENPCT,
    g.HRTOTLW_200 AS TENUREWOMENPCT,
    g.HRBKAAW_101 AS BLACKPROFWOMENPCT,
    g.HRBKAAW_102 AS BLACKASSOCPROFWOMENPCT,
    g.HRBKAAW_200 AS BLACKTENUREWOMENPCT,
    g.HRHISPW_101 AS HISPANICPROFWOMENPCT,
    g.HRHISPW_102 AS HISPANICASSOCPROFWOMENPCT,
    g.HRHISPW_200 AS HISPANICTENUREWOMENPCT,
    g.HRASIAW_101 AS ASIANPROFWOMENPCT, 
    g.HRASIAW_102 AS ASIANASSOCPROFWOMENPCT,
    g.HRASIAW_200 AS ASIANTENUREWOMENPCT,
    h.YEARLYHATECRIME AS YEARLYHATECRIME,
    h.YEARLYHATECRIME1K AS YEARLYHATECRIME1K,
    i.YEARLYVAWA AS YEARLYVAWA,
    i.YEARLYVAWA1K AS YEARLYVAWA1K,
    j.IRS_MONTH AS IRS_MONTH,
    j.`YEAR` AS `YEAR`,
    j.PERCENTAGE_WOMEN_TRUSTEES AS PERCENTAGE_WOMEN_TRUSTEES,
    j.PERCENTAGE_WOMEN_KEY_EMPLOYEES AS PERCENTAGE_WOMEN_KEY_EMPLOYEES,
    j.WHISTLEBLOWER_POLICY AS WHISTLEBLOWER_POLICY,
    j.CEO_REVIEWED_COMPENSATION AS CEO_REVIEWED_COMPENSATION,
    j.OTHER_REVIEWED_COMPENSATION AS OTHER_REVIEWED_COMPENSATION,
    j.MALE_TO_FEMALE_PAY_RATIO AS MALE_TO_FEMALE_PAY_RATIO,
    j.PRESIDENT_TO_AVERAGE_PAY_RATIO AS PRESIDENT_TO_AVERAGE_PAY_RATIO
FROM `ipeds_2024_db`.`C2022_B` a
INNER JOIN `ipeds_EF2022_temp` b ON a.UNITID = b.UNITID
INNER JOIN `ipeds_IC2022_temp` c ON a.UNITID = c.UNITID
INNER JOIN `ipeds_2024_db`.`HD2022` d ON a.UNITID = d.UNITID
INNER JOIN `ipeds_SAL2022_IS_temp` e ON a.UNITID = e.UNITID
INNER JOIN `ipeds_S2022_OC_temp` f ON a.UNITID = f.UNITID
INNER JOIN `ipeds_S2022_IS_temp` g ON a.UNITID = g.UNITID
INNER JOIN `css_hate_temp2` h ON d.OPEID = h.OPEID
INNER JOIN `css_vawa_temp2` i ON d.OPEID = i.OPEID
LEFT JOIN `irs990_temp` j ON d.EIN = j.EIN
WHERE a.CSTOTLT >= 50 AND b.EFTOTAL >= 200
ORDER BY a.`UNITID` ASC;

ALTER TABLE `merged_ipeds_css_irs`.`gf2024_final`
ADD PRIMARY KEY (`UNITID`);
