-- Combined SQL Script for GenderFair2024 DB --
-- Disabling SQL Safe Mode --
SET SQL_SAFE_UPDATES = 0;

-- Processing CSS DB --
-- Creating Merged Hate Table --
CREATE TABLE `css`.`css_hate_merged_records` (
    OPEID INT PRIMARY KEY,
    men_total INT,
    women_total INT,
    Total INT,
    MURD20 INT,
    MURD_RAC20 INT,
    MURD_REL20 INT,
    MURD_SEX20 INT,
    MURD_GEN20 INT,
    MURD_GID20 INT,
    MURD_DIS20 INT,
    MURD_ET20 INT,
    MURD_NAT20 INT,
    RAPE20 INT,
    RAPE_RAC20 INT,
    RAPE_REL20 INT,
    RAPE_SEX20 INT,
    RAPE_GEN20 INT,
    RAPE_GID20 INT,
    RAPE_DIS20 INT,
    RAPE_ET20 INT,
    RAPE_NAT20 INT,
    FOND20 INT,
    FOND_RAC20 INT,
    FOND_REL20 INT,
    FOND_SEX20 INT,
    FOND_GEN20 INT,
    FOND_GID20 INT,
    FOND_DIS20 INT,
    FOND_ET20 INT,
    FOND_NAT20 INT,
    INCE20 INT,
    INCE_RAC20 INT,
    INCE_REL20 INT,
    INCE_SEX20 INT,
    INCE_GEN20 INT,
    INCE_GID20 INT,
    INCE_DIS20 INT,
    INCE_ET20 INT,
    INCE_NAT20 INT,
    STAT20 INT,
    STAT_RAC20 INT,
    STAT_REL20 INT,
    STAT_SEX20 INT,
    STAT_GEN20 INT,
    STAT_GID20 INT,
    STAT_DIS20 INT,
    STAT_ET20 INT,
    STAT_NAT20 INT,
    ROBBE20 INT,
    ROBBE_RAC20 INT,
    ROBBE_REL20 INT,
    ROBBE_SEX20 INT,
    ROBBE_GEN20 INT,
    ROBBE_GID20 INT,
    ROBBE_DIS20 INT,
    ROBBE_ET20 INT,
    ROBBE_NAT20 INT,
    AGG_A20 INT,
    AGG_A_RAC20 INT,
    AGG_A_REL20 INT,
    AGG_A_SEX20 INT,
    AGG_A_GEN20 INT,
    AGG_A_GID20 INT,
    AGG_A_DIS20 INT,
    AGG_A_ET20 INT,
    AGG_A_NAT20 INT,
    BURGLA20 INT,
    BURGLA_RAC20 INT,
    BURGLA_REL20 INT,
    BURGLA_SEX20 INT,
    BURGLA_GEN20 INT,
    BURGLA_GID20 INT,
    BURGLA_DIS20 INT,
    BURGLA_ET20 INT,
    BURGLA_NAT20 INT,
    VEHIC20 INT,
    VEHIC_RAC20 INT,
    VEHIC_REL20 INT,
    VEHIC_SEX20 INT,
    VEHIC_GEN20 INT,
    VEHIC_GID20 INT,
    VEHIC_DIS20 INT,
    VEHIC_ET20 INT,
    VEHIC_NAT20 INT,
    ARSON20 INT,
    ARSON_RAC20 INT,
    ARSON_REL20 INT,
    ARSON_SEX20 INT,
    ARSON_GEN20 INT,
    ARSON_GID20 INT,
    ARSON_DIS20 INT,
    ARSON_ET20 INT,
    ARSON_NAT20 INT,
    SIM_A20 INT,
    SIM_A_RAC20 INT,
    SIM_A_REL20 INT,
    SIM_A_SEX20 INT,
    SIM_A_GEN20 INT,
    SIM_A_GID20 INT,
    SIM_A_DIS20 INT,
    SIM_A_ET20 INT,
    SIM_A_NAT20 INT,
    LAR_T20 INT,
    LAR_T_RAC20 INT,
    LAR_T_REL20 INT,
    LAR_T_SEX20 INT,
    LAR_T_GEN20 INT,
    LAR_T_GID20 INT,
    LAR_T_DIS20 INT,
    LAR_T_ET20 INT,
    LAR_T_NAT20 INT,
    INTIM20 INT,
    INTIM_RAC20 INT,
    INTIM_REL20 INT,
    INTIM_SEX20 INT,
    INTIM_GEN20 INT,
    INTIM_GID20 INT,
    INTIM_DIS20 INT,
    INTIM_ET20 INT,
    INTIM_NAT20 INT,
    VANDAL20 INT,
    VANDAL_RAC20 INT,
    VANDAL_REL20 INT,
    VANDAL_SEX20 INT,
    VANDAL_GEN20 INT,
    VANDAL_GID20 INT,
    VANDAL_DIS20 INT,
    VANDAL_ET20 INT,
    VANDAL_NAT20 INT,
    MURD21 INT,
    MURD_RAC21 INT,
    MURD_REL21 INT,
    MURD_SEX21 INT,
    MURD_GEN21 INT,
    MURD_GID21 INT,
    MURD_DIS21 INT,
    MURD_ET21 INT,
    MURD_NAT21 INT,
    RAPE21 INT,
    RAPE_RAC21 INT,
    RAPE_REL21 INT,
    RAPE_SEX21 INT,
    RAPE_GEN21 INT,
    RAPE_GID21 INT,
    RAPE_DIS21 INT,
    RAPE_ET21 INT,
    RAPE_NAT21 INT,
    FOND21 INT,
    FOND_RAC21 INT,
    FOND_REL21 INT,
    FOND_SEX21 INT,
    FOND_GEN21 INT,
    FOND_GID21 INT,
    FOND_DIS21 INT,
    FOND_ET21 INT,
    FOND_NAT21 INT,
    INCE21 INT,
    INCE_RAC21 INT,
    INCE_REL21 INT,
    INCE_SEX21 INT,
    INCE_GEN21 INT,
    INCE_GID21 INT,
    INCE_DIS21 INT,
    INCE_ET21 INT,
    INCE_NAT21 INT,
    STAT21 INT,
    STAT_RAC21 INT,
    STAT_REL21 INT,
    STAT_SEX21 INT,
    STAT_GEN21 INT,
    STAT_GID21 INT,
    STAT_DIS21 INT,
    STAT_ET21 INT,
    STAT_NAT21 INT,
    ROBBE21 INT,
    ROBBE_RAC21 INT,
    ROBBE_REL21 INT,
    ROBBE_SEX21 INT,
    ROBBE_GEN21 INT,
    ROBBE_GID21 INT,
    ROBBE_DIS21 INT,
    ROBBE_ET21 INT,
    ROBBE_NAT21 INT,
    AGG_A21 INT,
    AGG_A_RAC21 INT,
    AGG_A_REL21 INT,
    AGG_A_SEX21 INT,
    AGG_A_GEN21 INT,
    AGG_A_GID21 INT,
    AGG_A_DIS21 INT,
    AGG_A_ET21 INT,
    AGG_A_NAT21 INT,
    BURGLA21 INT,
    BURGLA_RAC21 INT,
    BURGLA_REL21 INT,
    BURGLA_SEX21 INT,
    BURGLA_GEN21 INT,
    BURGLA_GID21 INT,
    BURGLA_DIS21 INT,
    BURGLA_ET21 INT,
    BURGLA_NAT21 INT,
    VEHIC21 INT,
    VEHIC_RAC21 INT,
    VEHIC_REL21 INT,
    VEHIC_SEX21 INT,
    VEHIC_GEN21 INT,
    VEHIC_GID21 INT,
    VEHIC_DIS21 INT,
    VEHIC_ET21 INT,
    VEHIC_NAT21 INT,
    ARSON21 INT,
    ARSON_RAC21 INT,
    ARSON_REL21 INT,
    ARSON_SEX21 INT,
    ARSON_GEN21 INT,
    ARSON_GID21 INT,
    ARSON_DIS21 INT,
    ARSON_ET21 INT,
    ARSON_NAT21 INT,
    SIM_A21 INT,
    SIM_A_RAC21 INT,
    SIM_A_REL21 INT,
    SIM_A_SEX21 INT,
    SIM_A_GEN21 INT,
    SIM_A_GID21 INT,
    SIM_A_DIS21 INT,
    SIM_A_ET21 INT,
    SIM_A_NAT21 INT,
    LAR_T21 INT,
    LAR_T_RAC21 INT,
    LAR_T_REL21 INT,
    LAR_T_SEX21 INT,
    LAR_T_GEN21 INT,
    LAR_T_GID21 INT,
    LAR_T_DIS21 INT,
    LAR_T_ET21 INT,
    LAR_T_NAT21 INT,
    INTIM21 INT,
    INTIM_RAC21 INT,
    INTIM_REL21 INT,
    INTIM_SEX21 INT,
    INTIM_GEN21 INT,
    INTIM_GID21 INT,
    INTIM_DIS21 INT,
    INTIM_ET21 INT,
    INTIM_NAT21 INT,
    VANDAL21 INT,
    VANDAL_RAC21 INT,
    VANDAL_REL21 INT,
    VANDAL_SEX21 INT,
    VANDAL_GEN21 INT,
    VANDAL_GID21 INT,
    VANDAL_DIS21 INT,
    VANDAL_ET21 INT,
    VANDAL_NAT21 INT,
    MURD22 INT,
    MURD_RAC22 INT,
    MURD_REL22 INT,
    MURD_SEX22 INT,
    MURD_GEN22 INT,
    MURD_GID22 INT,
    MURD_DIS22 INT,
    MURD_ET22 INT,
    MURD_NAT22 INT,
    RAPE22 INT,
    RAPE_RAC22 INT,
    RAPE_REL22 INT,
    RAPE_SEX22 INT,
    RAPE_GEN22 INT,
    RAPE_GID22 INT,
    RAPE_DIS22 INT,
    RAPE_ET22 INT,
    RAPE_NAT22 INT,
    FOND22 INT,
    FOND_RAC22 INT,
    FOND_REL22 INT,
    FOND_SEX22 INT,
    FOND_GEN22 INT,
    FOND_GID22 INT,
    FOND_DIS22 INT,
    FOND_ET22 INT,
    FOND_NAT22 INT,
    INCE22 INT,
    INCE_RAC22 INT,
    INCE_REL22 INT,
    INCE_SEX22 INT,
    INCE_GEN22 INT,
    INCE_GID22 INT,
    INCE_DIS22 INT,
    INCE_ET22 INT,
    INCE_NAT22 INT,
    STAT22 INT,
    STAT_RAC22 INT,
    STAT_REL22 INT,
    STAT_SEX22 INT,
    STAT_GEN22 INT,
    STAT_GID22 INT,
    STAT_DIS22 INT,
    STAT_ET22 INT,
    STAT_NAT22 INT,
    ROBBE22 INT,
    ROBBE_RAC22 INT,
    ROBBE_REL22 INT,
    ROBBE_SEX22 INT,
    ROBBE_GEN22 INT,
    ROBBE_GID22 INT,
    ROBBE_DIS22 INT,
    ROBBE_ET22 INT,
    ROBBE_NAT22 INT,
    AGG_A22 INT,
    AGG_A_RAC22 INT,
    AGG_A_REL22 INT,
    AGG_A_SEX22 INT,
    AGG_A_GEN22 INT,
    AGG_A_GID22 INT,
    AGG_A_DIS22 INT,
    AGG_A_ET22 INT,
    AGG_A_NAT22 INT,
    BURGLA22 INT,
    BURGLA_RAC22 INT,
    BURGLA_REL22 INT,
    BURGLA_SEX22 INT,
    BURGLA_GEN22 INT,
    BURGLA_GID22 INT,
    BURGLA_DIS22 INT,
    BURGLA_ET22 INT,
    BURGLA_NAT22 INT,
    VEHIC22 INT,
    VEHIC_RAC22 INT,
    VEHIC_REL22 INT,
    VEHIC_SEX22 INT,
    VEHIC_GEN22 INT,
    VEHIC_GID22 INT,
    VEHIC_DIS22 INT,
    VEHIC_ET22 INT,
    VEHIC_NAT22 INT,
    ARSON22 INT,
    ARSON_RAC22 INT,
    ARSON_REL22 INT,
    ARSON_SEX22 INT,
    ARSON_GEN22 INT,
    ARSON_GID22 INT,
    ARSON_DIS22 INT,
    ARSON_ET22 INT,
    ARSON_NAT22 INT,
    SIM_A22 INT,
    SIM_A_RAC22 INT,
    SIM_A_REL22 INT,
    SIM_A_SEX22 INT,
    SIM_A_GEN22 INT,
    SIM_A_GID22 INT,
    SIM_A_DIS22 INT,
    SIM_A_ET22 INT,
    SIM_A_NAT22 INT,
    LAR_T22 INT,
    LAR_T_RAC22 INT,
    LAR_T_REL22 INT,
    LAR_T_SEX22 INT,
    LAR_T_GEN22 INT,
    LAR_T_GID22 INT,
    LAR_T_DIS22 INT,
    LAR_T_ET22 INT,
    LAR_T_NAT22 INT,
    INTIM22 INT,
    INTIM_RAC22 INT,
    INTIM_REL22 INT,
    INTIM_SEX22 INT,
    INTIM_GEN22 INT,
    INTIM_GID22 INT,
    INTIM_DIS22 INT,
    INTIM_ET22 INT,
    INTIM_NAT22 INT,
    VANDAL22 INT,
    VANDAL_RAC22 INT,
    VANDAL_REL22 INT,
    VANDAL_SEX22 INT,
    VANDAL_GEN22 INT,
    VANDAL_GID22 INT,
    VANDAL_DIS22 INT,
    VANDAL_ET22 INT,
    VANDAL_NAT22 INT
);

INSERT INTO `css`.`css_hate_merged_records`
SELECT 
    OPEID,
    MIN(men_total) AS men_total,
    MIN(women_total) AS women_total,
    MIN(Total) AS Total,
    SUM(MURD20) AS MURD20,
    SUM(MURD_RAC20) AS MURD_RAC20,
    SUM(MURD_REL20) AS MURD_REL20,
    SUM(MURD_SEX20) AS MURD_SEX20,
    SUM(MURD_GEN20) AS MURD_GEN20,
    SUM(MURD_GID20) AS MURD_GID20,
    SUM(MURD_DIS20) AS MURD_DIS20,
    SUM(MURD_ET20) AS MURD_ET20,
    SUM(MURD_NAT20) AS MURD_NAT20,
    SUM(RAPE20) AS RAPE20,
    SUM(RAPE_RAC20) AS RAPE_RAC20,
    SUM(RAPE_REL20) AS RAPE_REL20,
    SUM(RAPE_SEX20) AS RAPE_SEX20,
    SUM(RAPE_GEN20) AS RAPE_GEN20,
    SUM(RAPE_GID20) AS RAPE_GID20,
    SUM(RAPE_DIS20) AS RAPE_DIS20,
    SUM(RAPE_ET20) AS RAPE_ET20,
    SUM(RAPE_NAT20) AS RAPE_NAT20,
    SUM(FOND20) AS FOND20,
    SUM(FOND_RAC20) AS FOND_RAC20,
    SUM(FOND_REL20) AS FOND_REL20,
    SUM(FOND_SEX20) AS FOND_SEX20,
    SUM(FOND_GEN20) AS FOND_GEN20,
    SUM(FOND_GID20) AS FOND_GID20,
    SUM(FOND_DIS20) AS FOND_DIS20,
    SUM(FOND_ET20) AS FOND_ET20,
    SUM(FOND_NAT20) AS FOND_NAT20,
    SUM(INCE20) AS INCE20,
    SUM(INCE_RAC20) AS INCE_RAC20,
    SUM(INCE_REL20) AS INCE_REL20,
    SUM(INCE_SEX20) AS INCE_SEX20,
    SUM(INCE_GEN20) AS INCE_GEN20,
    SUM(INCE_GID20) AS INCE_GID20,
    SUM(INCE_DIS20) AS INCE_DIS20,
    SUM(INCE_ET20) AS INCE_ET20,
    SUM(INCE_NAT20) AS INCE_NAT20,
    SUM(STAT20) AS STAT20,
    SUM(STAT_RAC20) AS STAT_RAC20,
    SUM(STAT_REL20) AS STAT_REL20,
    SUM(STAT_SEX20) AS STAT_SEX20,
    SUM(STAT_GEN20) AS STAT_GEN20,
    SUM(STAT_GID20) AS STAT_GID20,
    SUM(STAT_DIS20) AS STAT_DIS20,
    SUM(STAT_ET20) AS STAT_ET20,
    SUM(STAT_NAT20) AS STAT_NAT20,
    SUM(ROBBE20) AS ROBBE20,
    SUM(ROBBE_RAC20) AS ROBBE_RAC20,
    SUM(ROBBE_REL20) AS ROBBE_REL20,
    SUM(ROBBE_SEX20) AS ROBBE_SEX20,
    SUM(ROBBE_GEN20) AS ROBBE_GEN20,
    SUM(ROBBE_GID20) AS ROBBE_GID20,
    SUM(ROBBE_DIS20) AS ROBBE_DIS20,
    SUM(ROBBE_ET20) AS ROBBE_ET20,
    SUM(ROBBE_NAT20) AS ROBBE_NAT20,
    SUM(AGG_A20) AS AGG_A20,
    SUM(AGG_A_RAC20) AS AGG_A_RAC20,
    SUM(AGG_A_REL20) AS AGG_A_REL20,
    SUM(AGG_A_SEX20) AS AGG_A_SEX20,
    SUM(AGG_A_GEN20) AS AGG_A_GEN20,
    SUM(AGG_A_GID20) AS AGG_A_GID20,
    SUM(AGG_A_DIS20) AS AGG_A_DIS20,
    SUM(AGG_A_ET20) AS AGG_A_ET20,
    SUM(AGG_A_NAT20) AS AGG_A_NAT20,
    SUM(BURGLA20) AS BURGLA20,
    SUM(BURGLA_RAC20) AS BURGLA_RAC20,
    SUM(BURGLA_REL20) AS BURGLA_REL20,
    SUM(BURGLA_SEX20) AS BURGLA_SEX20,
    SUM(BURGLA_GEN20) AS BURGLA_GEN20,
    SUM(BURGLA_GID20) AS BURGLA_GID20,
    SUM(BURGLA_DIS20) AS BURGLA_DIS20,
    SUM(BURGLA_ET20) AS BURGLA_ET20,
    SUM(BURGLA_NAT20) AS BURGLA_NAT20,
    SUM(VEHIC20) AS VEHIC20,
    SUM(VEHIC_RAC20) AS VEHIC_RAC20,
    SUM(VEHIC_REL20) AS VEHIC_REL20,
    SUM(VEHIC_SEX20) AS VEHIC_SEX20,
    SUM(VEHIC_GEN20) AS VEHIC_GEN20,
    SUM(VEHIC_GID20) AS VEHIC_GID20,
    SUM(VEHIC_DIS20) AS VEHIC_DIS20,
    SUM(VEHIC_ET20) AS VEHIC_ET20,
    SUM(VEHIC_NAT20) AS VEHIC_NAT20,
    SUM(ARSON20) AS ARSON20,
    SUM(ARSON_RAC20) AS ARSON_RAC20,
    SUM(ARSON_REL20) AS ARSON_REL20,
    SUM(ARSON_SEX20) AS ARSON_SEX20,
    SUM(ARSON_GEN20) AS ARSON_GEN20,
    SUM(ARSON_GID20) AS ARSON_GID20,
    SUM(ARSON_DIS20) AS ARSON_DIS20,
    SUM(ARSON_ET20) AS ARSON_ET20,
    SUM(ARSON_NAT20) AS ARSON_NAT20,
    SUM(SIM_A20) AS SIM_A20,
    SUM(SIM_A_RAC20) AS SIM_A_RAC20,
    SUM(SIM_A_REL20) AS SIM_A_REL20,
    SUM(SIM_A_SEX20) AS SIM_A_SEX20,
    SUM(SIM_A_GEN20) AS SIM_A_GEN20,
    SUM(SIM_A_GID20) AS SIM_A_GID20,
    SUM(SIM_A_DIS20) AS SIM_A_DIS20,
    SUM(SIM_A_ET20) AS SIM_A_ET20,
    SUM(SIM_A_NAT20) AS SIM_A_NAT20,
    SUM(LAR_T20) AS LAR_T20,
    SUM(LAR_T_RAC20) AS LAR_T_RAC20,
    SUM(LAR_T_REL20) AS LAR_T_REL20,
    SUM(LAR_T_SEX20) AS LAR_T_SEX20,
    SUM(LAR_T_GEN20) AS LAR_T_GEN20,
    SUM(LAR_T_GID20) AS LAR_T_GID20,
    SUM(LAR_T_DIS20) AS LAR_T_DIS20,
    SUM(LAR_T_ET20) AS LAR_T_ET20,
    SUM(LAR_T_NAT20) AS LAR_T_NAT20,
    SUM(INTIM20) AS INTIM20,
    SUM(INTIM_RAC20) AS INTIM_RAC20,
    SUM(INTIM_REL20) AS INTIM_REL20,
    SUM(INTIM_SEX20) AS INTIM_SEX20,
    SUM(INTIM_GEN20) AS INTIM_GEN20,
    SUM(INTIM_GID20) AS INTIM_GID20,
    SUM(INTIM_DIS20) AS INTIM_DIS20,
    SUM(INTIM_ET20) AS INTIM_ET20,
    SUM(INTIM_NAT20) AS INTIM_NAT20,
    SUM(VANDAL20) AS VANDAL20,
    SUM(VANDAL_RAC20) AS VANDAL_RAC20,
    SUM(VANDAL_REL20) AS VANDAL_REL20,
    SUM(VANDAL_SEX20) AS VANDAL_SEX20,
    SUM(VANDAL_GEN20) AS VANDAL_GEN20,
    SUM(VANDAL_GID20) AS VANDAL_GID20,
    SUM(VANDAL_DIS20) AS VANDAL_DIS20,
    SUM(VANDAL_ET20) AS VANDAL_ET20,
    SUM(VANDAL_NAT20) AS VANDAL_NAT20,
    SUM(MURD21) AS MURD21,
    SUM(MURD_RAC21) AS MURD_RAC21,
    SUM(MURD_REL21) AS MURD_REL21,
    SUM(MURD_SEX21) AS MURD_SEX21,
    SUM(MURD_GEN21) AS MURD_GEN21,
    SUM(MURD_GID21) AS MURD_GID21,
    SUM(MURD_DIS21) AS MURD_DIS21,
    SUM(MURD_ET21) AS MURD_ET21,
    SUM(MURD_NAT21) AS MURD_NAT21,
    SUM(RAPE21) AS RAPE21,
    SUM(RAPE_RAC21) AS RAPE_RAC21,
    SUM(RAPE_REL21) AS RAPE_REL21,
    SUM(RAPE_SEX21) AS RAPE_SEX21,
    SUM(RAPE_GEN21) AS RAPE_GEN21,
    SUM(RAPE_GID21) AS RAPE_GID21,
    SUM(RAPE_DIS21) AS RAPE_DIS21,
    SUM(RAPE_ET21) AS RAPE_ET21,
    SUM(RAPE_NAT21) AS RAPE_NAT21,
    SUM(FOND21) AS FOND21,
    SUM(FOND_RAC21) AS FOND_RAC21,
    SUM(FOND_REL21) AS FOND_REL21,
    SUM(FOND_SEX21) AS FOND_SEX21,
    SUM(FOND_GEN21) AS FOND_GEN21,
    SUM(FOND_GID21) AS FOND_GID21,
    SUM(FOND_DIS21) AS FOND_DIS21,
    SUM(FOND_ET21) AS FOND_ET21,
    SUM(FOND_NAT21) AS FOND_NAT21,
    SUM(INCE21) AS INCE21,
    SUM(INCE_RAC21) AS INCE_RAC21,
    SUM(INCE_REL21) AS INCE_REL21,
    SUM(INCE_SEX21) AS INCE_SEX21,
    SUM(INCE_GEN21) AS INCE_GEN21,
    SUM(INCE_GID21) AS INCE_GID21,
    SUM(INCE_DIS21) AS INCE_DIS21,
    SUM(INCE_ET21) AS INCE_ET21,
    SUM(INCE_NAT21) AS INCE_NAT21,
    SUM(STAT21) AS STAT21,
    SUM(STAT_RAC21) AS STAT_RAC21,
    SUM(STAT_REL21) AS STAT_REL21,
    SUM(STAT_SEX21) AS STAT_SEX21,
    SUM(STAT_GEN21) AS STAT_GEN21,
    SUM(STAT_GID21) AS STAT_GID21,
    SUM(STAT_DIS21) AS STAT_DIS21,
    SUM(STAT_ET21) AS STAT_ET21,
    SUM(STAT_NAT21) AS STAT_NAT21,
    SUM(ROBBE21) AS ROBBE21,
    SUM(ROBBE_RAC21) AS ROBBE_RAC21,
    SUM(ROBBE_REL21) AS ROBBE_REL21,
    SUM(ROBBE_SEX21) AS ROBBE_SEX21,
    SUM(ROBBE_GEN21) AS ROBBE_GEN21,
    SUM(ROBBE_GID21) AS ROBBE_GID21,
    SUM(ROBBE_DIS21) AS ROBBE_DIS21,
    SUM(ROBBE_ET21) AS ROBBE_ET21,
    SUM(ROBBE_NAT21) AS ROBBE_NAT21,
    SUM(AGG_A21) AS AGG_A21,
    SUM(AGG_A_RAC21) AS AGG_A_RAC21,
    SUM(AGG_A_REL21) AS AGG_A_REL21,
    SUM(AGG_A_SEX21) AS AGG_A_SEX21,
    SUM(AGG_A_GEN21) AS AGG_A_GEN21,
    SUM(AGG_A_GID21) AS AGG_A_GID21,
    SUM(AGG_A_DIS21) AS AGG_A_DIS21,
    SUM(AGG_A_ET21) AS AGG_A_ET21,
    SUM(AGG_A_NAT21) AS AGG_A_NAT21,
    SUM(BURGLA21) AS BURGLA21,
    SUM(BURGLA_RAC21) AS BURGLA_RAC21,
    SUM(BURGLA_REL21) AS BURGLA_REL21,
    SUM(BURGLA_SEX21) AS BURGLA_SEX21,
    SUM(BURGLA_GEN21) AS BURGLA_GEN21,
    SUM(BURGLA_GID21) AS BURGLA_GID21,
    SUM(BURGLA_DIS21) AS BURGLA_DIS21,
    SUM(BURGLA_ET21) AS BURGLA_ET21,
    SUM(BURGLA_NAT21) AS BURGLA_NAT21,
    SUM(VEHIC21) AS VEHIC21,
    SUM(VEHIC_RAC21) AS VEHIC_RAC21,
    SUM(VEHIC_REL21) AS VEHIC_REL21,
    SUM(VEHIC_SEX21) AS VEHIC_SEX21,
    SUM(VEHIC_GEN21) AS VEHIC_GEN21,
    SUM(VEHIC_GID21) AS VEHIC_GID21,
    SUM(VEHIC_DIS21) AS VEHIC_DIS21,
    SUM(VEHIC_ET21) AS VEHIC_ET21,
    SUM(VEHIC_NAT21) AS VEHIC_NAT21,
    SUM(ARSON21) AS ARSON21,
    SUM(ARSON_RAC21) AS ARSON_RAC21,
    SUM(ARSON_REL21) AS ARSON_REL21,
    SUM(ARSON_SEX21) AS ARSON_SEX21,
    SUM(ARSON_GEN21) AS ARSON_GEN21,
    SUM(ARSON_GID21) AS ARSON_GID21,
    SUM(ARSON_DIS21) AS ARSON_DIS21,
    SUM(ARSON_ET21) AS ARSON_ET21,
    SUM(ARSON_NAT21) AS ARSON_NAT21,
    SUM(SIM_A21) AS SIM_A21,
    SUM(SIM_A_RAC21) AS SIM_A_RAC21,
    SUM(SIM_A_REL21) AS SIM_A_REL21,
    SUM(SIM_A_SEX21) AS SIM_A_SEX21,
    SUM(SIM_A_GEN21) AS SIM_A_GEN21,
    SUM(SIM_A_GID21) AS SIM_A_GID21,
    SUM(SIM_A_DIS21) AS SIM_A_DIS21,
    SUM(SIM_A_ET21) AS SIM_A_ET21,
    SUM(SIM_A_NAT21) AS SIM_A_NAT21,
    SUM(LAR_T21) AS LAR_T21,
    SUM(LAR_T_RAC21) AS LAR_T_RAC21,
    SUM(LAR_T_REL21) AS LAR_T_REL21,
    SUM(LAR_T_SEX21) AS LAR_T_SEX21,
    SUM(LAR_T_GEN21) AS LAR_T_GEN21,
    SUM(LAR_T_GID21) AS LAR_T_GID21,
    SUM(LAR_T_DIS21) AS LAR_T_DIS21,
    SUM(LAR_T_ET21) AS LAR_T_ET21,
    SUM(LAR_T_NAT21) AS LAR_T_NAT21,
    SUM(INTIM21) AS INTIM21,
    SUM(INTIM_RAC21) AS INTIM_RAC21,
    SUM(INTIM_REL21) AS INTIM_REL21,
    SUM(INTIM_SEX21) AS INTIM_SEX21,
    SUM(INTIM_GEN21) AS INTIM_GEN21,
    SUM(INTIM_GID21) AS INTIM_GID21,
    SUM(INTIM_DIS21) AS INTIM_DIS21,
    SUM(INTIM_ET21) AS INTIM_ET21,
    SUM(INTIM_NAT21) AS INTIM_NAT21,
    SUM(VANDAL21) AS VANDAL21,
    SUM(VANDAL_RAC21) AS VANDAL_RAC21,
    SUM(VANDAL_REL21) AS VANDAL_REL21,
    SUM(VANDAL_SEX21) AS VANDAL_SEX21,
    SUM(VANDAL_GEN21) AS VANDAL_GEN21,
    SUM(VANDAL_GID21) AS VANDAL_GID21,
    SUM(VANDAL_DIS21) AS VANDAL_DIS21,
    SUM(VANDAL_ET21) AS VANDAL_ET21,
    SUM(VANDAL_NAT21) AS VANDAL_NAT21,
    SUM(MURD22) AS MURD22,
    SUM(MURD_RAC22) AS MURD_RAC22,
    SUM(MURD_REL22) AS MURD_REL22,
    SUM(MURD_SEX22) AS MURD_SEX22,
    SUM(MURD_GEN22) AS MURD_GEN22,
    SUM(MURD_GID22) AS MURD_GID22,
    SUM(MURD_DIS22) AS MURD_DIS22,
    SUM(MURD_ET22) AS MURD_ET22,
    SUM(MURD_NAT22) AS MURD_NAT22,
    SUM(RAPE22) AS RAPE22,
    SUM(RAPE_RAC22) AS RAPE_RAC22,
    SUM(RAPE_REL22) AS RAPE_REL22,
    SUM(RAPE_SEX22) AS RAPE_SEX22,
    SUM(RAPE_GEN22) AS RAPE_GEN22,
    SUM(RAPE_GID22) AS RAPE_GID22,
    SUM(RAPE_DIS22) AS RAPE_DIS22,
    SUM(RAPE_ET22) AS RAPE_ET22,
    SUM(RAPE_NAT22) AS RAPE_NAT22,
    SUM(FOND22) AS FOND22,
    SUM(FOND_RAC22) AS FOND_RAC22,
    SUM(FOND_REL22) AS FOND_REL22,
    SUM(FOND_SEX22) AS FOND_SEX22,
    SUM(FOND_GEN22) AS FOND_GEN22,
    SUM(FOND_GID22) AS FOND_GID22,
    SUM(FOND_DIS22) AS FOND_DIS22,
    SUM(FOND_ET22) AS FOND_ET22,
    SUM(FOND_NAT22) AS FOND_NAT22,
    SUM(INCE22) AS INCE22,
    SUM(INCE_RAC22) AS INCE_RAC22,
    SUM(INCE_REL22) AS INCE_REL22,
    SUM(INCE_SEX22) AS INCE_SEX22,
    SUM(INCE_GEN22) AS INCE_GEN22,
    SUM(INCE_GID22) AS INCE_GID22,
    SUM(INCE_DIS22) AS INCE_DIS22,
    SUM(INCE_ET22) AS INCE_ET22,
    SUM(INCE_NAT22) AS INCE_NAT22,
    SUM(STAT22) AS STAT22,
    SUM(STAT_RAC22) AS STAT_RAC22,
    SUM(STAT_REL22) AS STAT_REL22,
    SUM(STAT_SEX22) AS STAT_SEX22,
    SUM(STAT_GEN22) AS STAT_GEN22,
    SUM(STAT_GID22) AS STAT_GID22,
    SUM(STAT_DIS22) AS STAT_DIS22,
    SUM(STAT_ET22) AS STAT_ET22,
    SUM(STAT_NAT22) AS STAT_NAT22,
    SUM(ROBBE22) AS ROBBE22,
    SUM(ROBBE_RAC22) AS ROBBE_RAC22,
    SUM(ROBBE_REL22) AS ROBBE_REL22,
    SUM(ROBBE_SEX22) AS ROBBE_SEX22,
    SUM(ROBBE_GEN22) AS ROBBE_GEN22,
    SUM(ROBBE_GID22) AS ROBBE_GID22,
    SUM(ROBBE_DIS22) AS ROBBE_DIS22,
    SUM(ROBBE_ET22) AS ROBBE_ET22,
    SUM(ROBBE_NAT22) AS ROBBE_NAT22,
    SUM(AGG_A22) AS AGG_A22,
    SUM(AGG_A_RAC22) AS AGG_A_RAC22,
    SUM(AGG_A_REL22) AS AGG_A_REL22,
    SUM(AGG_A_SEX22) AS AGG_A_SEX22,
    SUM(AGG_A_GEN22) AS AGG_A_GEN22,
    SUM(AGG_A_GID22) AS AGG_A_GID22,
    SUM(AGG_A_DIS22) AS AGG_A_DIS22,
    SUM(AGG_A_ET22) AS AGG_A_ET22,
    SUM(AGG_A_NAT22) AS AGG_A_NAT22,
    SUM(BURGLA22) AS BURGLA22,
    SUM(BURGLA_RAC22) AS BURGLA_RAC22,
    SUM(BURGLA_REL22) AS BURGLA_REL22,
    SUM(BURGLA_SEX22) AS BURGLA_SEX22,
    SUM(BURGLA_GEN22) AS BURGLA_GEN22,
    SUM(BURGLA_GID22) AS BURGLA_GID22,
    SUM(BURGLA_DIS22) AS BURGLA_DIS22,
    SUM(BURGLA_ET22) AS BURGLA_ET22,
    SUM(BURGLA_NAT22) AS BURGLA_NAT22,
    SUM(VEHIC22) AS VEHIC22,
    SUM(VEHIC_RAC22) AS VEHIC_RAC22,
    SUM(VEHIC_REL22) AS VEHIC_REL22,
    SUM(VEHIC_SEX22) AS VEHIC_SEX22,
    SUM(VEHIC_GEN22) AS VEHIC_GEN22,
    SUM(VEHIC_GID22) AS VEHIC_GID22,
    SUM(VEHIC_DIS22) AS VEHIC_DIS22,
    SUM(VEHIC_ET22) AS VEHIC_ET22,
    SUM(VEHIC_NAT22) AS VEHIC_NAT22,
    SUM(ARSON22) AS ARSON22,
    SUM(ARSON_RAC22) AS ARSON_RAC22,
    SUM(ARSON_REL22) AS ARSON_REL22,
    SUM(ARSON_SEX22) AS ARSON_SEX22,
    SUM(ARSON_GEN22) AS ARSON_GEN22,
    SUM(ARSON_GID22) AS ARSON_GID22,
    SUM(ARSON_DIS22) AS ARSON_DIS22,
    SUM(ARSON_ET22) AS ARSON_ET22,
    SUM(ARSON_NAT22) AS ARSON_NAT22,
    SUM(SIM_A22) AS SIM_A22,
    SUM(SIM_A_RAC22) AS SIM_A_RAC22,
    SUM(SIM_A_REL22) AS SIM_A_REL22,
    SUM(SIM_A_SEX22) AS SIM_A_SEX22,
    SUM(SIM_A_GEN22) AS SIM_A_GEN22,
    SUM(SIM_A_GID22) AS SIM_A_GID22,
    SUM(SIM_A_DIS22) AS SIM_A_DIS22,
    SUM(SIM_A_ET22) AS SIM_A_ET22,
    SUM(SIM_A_NAT22) AS SIM_A_NAT22,
    SUM(LAR_T22) AS LAR_T22,
    SUM(LAR_T_RAC22) AS LAR_T_RAC22,
    SUM(LAR_T_REL22) AS LAR_T_REL22,
    SUM(LAR_T_SEX22) AS LAR_T_SEX22,
    SUM(LAR_T_GEN22) AS LAR_T_GEN22,
    SUM(LAR_T_GID22) AS LAR_T_GID22,
    SUM(LAR_T_DIS22) AS LAR_T_DIS22,
    SUM(LAR_T_ET22) AS LAR_T_ET22,
    SUM(LAR_T_NAT22) AS LAR_T_NAT22,
    SUM(INTIM22) AS INTIM22,
    SUM(INTIM_RAC22) AS INTIM_RAC22,
    SUM(INTIM_REL22) AS INTIM_REL22,
    SUM(INTIM_SEX22) AS INTIM_SEX22,
    SUM(INTIM_GEN22) AS INTIM_GEN22,
    SUM(INTIM_GID22) AS INTIM_GID22,
    SUM(INTIM_DIS22) AS INTIM_DIS22,
    SUM(INTIM_ET22) AS INTIM_ET22,
    SUM(INTIM_NAT22) AS INTIM_NAT22,
    SUM(VANDAL22) AS VANDAL22,
    SUM(VANDAL_RAC22) AS VANDAL_RAC22,
    SUM(VANDAL_REL22) AS VANDAL_REL22,
    SUM(VANDAL_SEX22) AS VANDAL_SEX22,
    SUM(VANDAL_GEN22) AS VANDAL_GEN22,
    SUM(VANDAL_GID22) AS VANDAL_GID22,
    SUM(VANDAL_DIS22) AS VANDAL_DIS22,
    SUM(VANDAL_ET22) AS VANDAL_ET22,
    SUM(VANDAL_NAT22) AS VANDAL_NAT22
FROM `css`.`css_hate`
GROUP BY OPEID;

-- Creating Final Hate Table --
ALTER TABLE `css`.`css_hate_merged_records`
ADD COLUMN YEARLYHATECRIME DOUBLE;

UPDATE `css`.`css_hate_merged_records`
SET YEARLYHATECRIME = (
    MURD20 +
    RAPE20 +
    FOND20 +
    INCE20 +
    STAT20 +
    ROBBE20 +
    AGG_A20 +
    BURGLA20 +
    VEHIC20 +
    ARSON20 +
    SIM_A20 +
    LAR_T20 +
    INTIM20 +
    VANDAL20 +
    MURD21 +
    RAPE21 +
    FOND21 +
    INCE21 +
    STAT21 +
    ROBBE21 +
    AGG_A21 +
    BURGLA21 +
    VEHIC21 +
    ARSON21 +
    SIM_A21 +
    LAR_T21 +
    INTIM21 +
    VANDAL21 +
    MURD22 +
    RAPE22 +
    FOND22 +
    INCE22 +
    STAT22 +
    ROBBE22 +
    AGG_A22 +
    BURGLA22 +
    VEHIC22 +
    ARSON22 +
    SIM_A22 +
    LAR_T22 +
    INTIM22 +
    VANDAL22
) / 3;

ALTER TABLE `css`.`css_hate_merged_records`
ADD COLUMN YEARLYHATECRIME1K DOUBLE;

UPDATE `css`.`css_hate_merged_records`
SET YEARLYHATECRIME1K = YEARLYHATECRIME * 1000 / NULLIF(Total, 0);

RENAME TABLE `css`.`css_hate_merged_records` TO `css`.`css_hate_final`;

-- Creating Merged VAWA Table --
CREATE TABLE `css`.`css_vawa_merged_records` (
    OPEID INT PRIMARY KEY,
    men_total INT,
    women_total INT,
    Total INT,
    DOMEST20 INT,
    DATING20 INT,
    STALK20 INT,
    DOMEST21 INT,
    DATING21 INT,
    STALK21 INT,
    DOMEST22 INT,
    DATING22 INT,
    STALK22 INT
);

-- Insert the aggregated records
INSERT INTO `css`.`css_vawa_merged_records`
SELECT 
    OPEID,
    -- First occurrence of 'men_total', 'women_total', 'Total'
    MIN(men_total) AS men_total,  
    MIN(women_total) AS women_total,  
    MIN(Total) AS Total,  
    -- Sum numeric columns except first_columns
    SUM(DOMEST20) AS DOMEST20,
    SUM(DATING20) AS DATING20,
    SUM(STALK20) AS STALK20,
    SUM(DOMEST21) AS DOMEST21,
    SUM(DATING21) AS DATING21,
    SUM(STALK21) AS STALK21,
    SUM(DOMEST22) AS DOMEST22,
    SUM(DATING22) AS DATING22,
    SUM(STALK22) AS STALK22
FROM `css`.`css_vawa`
GROUP BY OPEID;

-- Creating Final VAWA Table --
ALTER TABLE `css`.`css_vawa_merged_records`
ADD COLUMN YEARLYVAWA DOUBLE;

UPDATE `css`.`css_vawa_merged_records`
SET YEARLYVAWA = (DOMEST20 + DATING20 + STALK20
                 + DOMEST21 + DATING21 + STALK21
                 + DOMEST22 + DATING22 + STALK22) / 3;
                 
ALTER TABLE `css`.`css_vawa_merged_records`
ADD COLUMN YEARLYVAWA1K DOUBLE;

UPDATE `css`.`css_vawa_merged_records`
SET YEARLYVAWA1K = YEARLYVAWA * 1000 / NULLIF(Total, 0);

RENAME TABLE `css`.`css_vawa_merged_records` TO `css`.`css_vawa_final`;
-- End of CSS DB Processing --

-- Processing IPEDS DB --
-- Processing S2022_IS --
CREATE TABLE `ipeds_tables`.`S2022_IS_temp` AS
SELECT * 
FROM `ipeds_2024_db`.`S2022_IS`
WHERE `SISCAT` IN (101, 102, 200)
ORDER BY `UNITID` ASC;

CREATE TABLE `ipeds_tables`.`S2022_IS_sorted` AS
SELECT
    UNITID,
    SUM(CASE WHEN SISCAT = 101 THEN FACSTAT ELSE 0 END) AS FACSTAT_101,
    SUM(CASE WHEN SISCAT = 101 THEN ARANK ELSE 0 END) AS ARANK_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLT ELSE 0 END) AS HRTOTLT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLM ELSE 0 END) AS HRTOTLM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRAIANT ELSE 0 END) AS HRAIANT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRAIANM ELSE 0 END) AS HRAIANM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRAIANW ELSE 0 END) AS HRAIANW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAT ELSE 0 END) AS HRASIAT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAM ELSE 0 END) AS HRASIAM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAW ELSE 0 END) AS HRASIAW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAT ELSE 0 END) AS HRBKAAT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAM ELSE 0 END) AS HRBKAAM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPT ELSE 0 END) AS HRHISPT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPM ELSE 0 END) AS HRHISPM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPW ELSE 0 END) AS HRHISPW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNHPIT ELSE 0 END) AS HRNHPIT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNHPIM ELSE 0 END) AS HRNHPIM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNHPIW ELSE 0 END) AS HRNHPIW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRWHITT ELSE 0 END) AS HRWHITT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRWHITM ELSE 0 END) AS HRWHITM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRWHITW ELSE 0 END) AS HRWHITW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HR2MORT ELSE 0 END) AS HR2MORT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HR2MORM ELSE 0 END) AS HR2MORM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HR2MORW ELSE 0 END) AS HR2MORW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRUNKNT ELSE 0 END) AS HRUNKNT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRUNKNM ELSE 0 END) AS HRUNKNM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRUNKNW ELSE 0 END) AS HRUNKNW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNRALT ELSE 0 END) AS HRNRALT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNRALM ELSE 0 END) AS HRNRALM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNRALW ELSE 0 END) AS HRNRALW_101,
    SUM(CASE WHEN SISCAT = 102 THEN FACSTAT ELSE 0 END) AS FACSTAT_102,
    SUM(CASE WHEN SISCAT = 102 THEN ARANK ELSE 0 END) AS ARANK_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLT ELSE 0 END) AS HRTOTLT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLM ELSE 0 END) AS HRTOTLM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRAIANT ELSE 0 END) AS HRAIANT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRAIANM ELSE 0 END) AS HRAIANM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRAIANW ELSE 0 END) AS HRAIANW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAT ELSE 0 END) AS HRASIAT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAM ELSE 0 END) AS HRASIAM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAW ELSE 0 END) AS HRASIAW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAT ELSE 0 END) AS HRBKAAT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAM ELSE 0 END) AS HRBKAAM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPT ELSE 0 END) AS HRHISPT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPM ELSE 0 END) AS HRHISPM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPW ELSE 0 END) AS HRHISPW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNHPIT ELSE 0 END) AS HRNHPIT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNHPIM ELSE 0 END) AS HRNHPIM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNHPIW ELSE 0 END) AS HRNHPIW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRWHITT ELSE 0 END) AS HRWHITT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRWHITM ELSE 0 END) AS HRWHITM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRWHITW ELSE 0 END) AS HRWHITW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HR2MORT ELSE 0 END) AS HR2MORT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HR2MORM ELSE 0 END) AS HR2MORM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HR2MORW ELSE 0 END) AS HR2MORW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRUNKNT ELSE 0 END) AS HRUNKNT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRUNKNM ELSE 0 END) AS HRUNKNM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRUNKNW ELSE 0 END) AS HRUNKNW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNRALT ELSE 0 END) AS HRNRALT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNRALM ELSE 0 END) AS HRNRALM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNRALW ELSE 0 END) AS HRNRALW_102,
    SUM(CASE WHEN SISCAT = 200 THEN FACSTAT ELSE 0 END) AS FACSTAT_200,
    SUM(CASE WHEN SISCAT = 200 THEN ARANK ELSE 0 END) AS ARANK_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLT ELSE 0 END) AS HRTOTLT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLM ELSE 0 END) AS HRTOTLM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRAIANT ELSE 0 END) AS HRAIANT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRAIANM ELSE 0 END) AS HRAIANM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRAIANW ELSE 0 END) AS HRAIANW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAT ELSE 0 END) AS HRASIAT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAM ELSE 0 END) AS HRASIAM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAW ELSE 0 END) AS HRASIAW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAT ELSE 0 END) AS HRBKAAT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAM ELSE 0 END) AS HRBKAAM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPT ELSE 0 END) AS HRHISPT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPM ELSE 0 END) AS HRHISPM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPW ELSE 0 END) AS HRHISPW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNHPIT ELSE 0 END) AS HRNHPIT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNHPIM ELSE 0 END) AS HRNHPIM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNHPIW ELSE 0 END) AS HRNHPIW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRWHITT ELSE 0 END) AS HRWHITT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRWHITM ELSE 0 END) AS HRWHITM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRWHITW ELSE 0 END) AS HRWHITW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HR2MORT ELSE 0 END) AS HR2MORT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HR2MORM ELSE 0 END) AS HR2MORM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HR2MORW ELSE 0 END) AS HR2MORW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRUNKNT ELSE 0 END) AS HRUNKNT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRUNKNM ELSE 0 END) AS HRUNKNM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRUNKNW ELSE 0 END) AS HRUNKNW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNRALT ELSE 0 END) AS HRNRALT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNRALM ELSE 0 END) AS HRNRALM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNRALW ELSE 0 END) AS HRNRALW_200
FROM `ipeds_tables`.`S2022_IS_temp`
GROUP BY `UNITID`;

ALTER TABLE `ipeds_tables`.`S2022_IS_sorted`
ADD PRIMARY KEY (`UNITID`);

DROP TABLE `ipeds_tables`.`S2022_IS_temp`;

-- Processing S2022_OC --
CREATE TABLE `ipeds_tables`.`S2022_OC_temp` AS
SELECT * 
FROM `ipeds_2024_db`.`S2022_OC`
WHERE `OCCUPCAT` IN (220, 230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 420, 490)
ORDER BY `UNITID` ASC;

CREATE TABLE `ipeds_tables`.`S2022_OC_sorted` AS
SELECT 
    UNITID,
	SUM(STAFFCAT) AS STAFFCAT,
    SUM(HRTOTLT) AS HRTOTLT,
    SUM(HRTOTLM) AS HRTOTLM,
    SUM(HRTOTLW) AS HRTOTLW,
    SUM(HRAIANT) AS HRAIANT,
    SUM(HRAIANM) AS HRAIANM,
    SUM(HRAIANW) AS HRAIANW,
    SUM(HRASIAT) AS HRASIAT,
    SUM(HRASIAM) AS HRASIAM,
    SUM(HRASIAW) AS HRASIAW,
    SUM(HRBKAAT) AS HRBKAAT,
    SUM(HRBKAAM) AS HRBKAAM,
    SUM(HRBKAAW) AS HRBKAAW,
    SUM(HRHISPT) AS HRHISPT,
    SUM(HRHISPM) AS HRHISPM,
    SUM(HRHISPW) AS HRHISPW,
    SUM(HRNHPIT) AS HRNHPIT,
    SUM(HRNHPIM) AS HRNHPIM,
    SUM(HRNHPIW) AS HRNHPIW,
    SUM(HRWHITT) AS HRWHITT,
    SUM(HRWHITM) AS HRWHITM,
    SUM(HRWHITW) AS HRWHITW,
    SUM(HR2MORT) AS HR2MORT,
    SUM(HR2MORM) AS HR2MORM,
    SUM(HR2MORW) AS HR2MORW,
    SUM(HRUNKNT) AS HRUNKNT,
    SUM(HRUNKNM) AS HRUNKNM,
    SUM(HRUNKNW) AS HRUNKNW,
    SUM(HRNRALT) AS HRNRALT,
    SUM(HRNRALM) AS HRNRALM,
    SUM(HRNRALW) AS HRNRALW
FROM `ipeds_tables`.`S2022_OC_temp`
GROUP BY UNITID;

ALTER TABLE `ipeds_tables`.`S2022_OC_sorted`
ADD PRIMARY KEY (`UNITID`);

DROP TABLE `ipeds_tables`.`S2022_OC_temp`;

-- Processing SAL2022_IS --
CREATE TABLE `ipeds_tables`.`SAL2022_IS_sorted` AS
SELECT * 
FROM `ipeds_2024_db`.`SAL2022_IS`
WHERE `ARANK` IN (7)
ORDER BY `UNITID` ASC;

ALTER TABLE `ipeds_tables`.`SAL2022_IS_sorted`
ADD COLUMN AVGSALM DOUBLE,
ADD COLUMN AVGSALW DOUBLE;

UPDATE `ipeds_tables`.`SAL2022_IS_sorted`
SET 
  AVGSALM = CASE 
              WHEN SAINSTM = 0 OR SAOUTLM = 0 THEN NULL
              ELSE SAOUTLM / SAINSTM 
            END,
  AVGSALW = CASE 
              WHEN SAINSTW = 0 OR SAOUTLW = 0 THEN NULL
              ELSE SAOUTLW / SAINSTW 
            END;

ALTER TABLE `ipeds_tables`.`SAL2022_IS_sorted`
ADD PRIMARY KEY (`UNITID`);

-- Processing IC2022 --
CREATE TABLE `ipeds_tables`.`IC2022_sorted` AS
SELECT *
FROM `ipeds_2024_db`.`IC2022`
WHERE (
    LEVEL3 = 1 OR
    LEVEL4 = 1 OR
    LEVEL5 = 1 OR
    LEVEL6 = 1 OR
    LEVEL7 = 1 OR
    LEVEL8 = 1 OR
    LEVEL17 = 1 OR
    LEVEL18 = 1 OR
    LEVEL19 = 1
)
AND `CNTLAFFI` IN (1, 3, 4);

ALTER TABLE `ipeds_tables`.`IC2022_sorted`
ADD PRIMARY KEY (`UNITID`);

-- No Processing Needed for C2023_B --

-- Processing EF2022 --
CREATE TABLE `ipeds_tables`.`EF2022_sorted` AS
SELECT * 
FROM `ipeds_2024_db`.`EF2022`
WHERE `EFLEVEL` IN (10)
ORDER BY `UNITID` ASC;

ALTER TABLE `ipeds_tables`.`EF2022_sorted`
ADD PRIMARY KEY (`UNITID`);

-- Filtering schools using tables --
CREATE TABLE `ipeds_tables`.`ipeds_filter` AS
SELECT 
    a.UNITID,
    a.CSTOTLT,
    b.EFLEVEL,
    b.EFTOTAL,
    c.CNTLAFFI,
    c.STUSRV8
FROM `ipeds_2024_db`.`C2022_B` a
INNER JOIN `ipeds_tables`.`EF2022_sorted` b ON a.UNITID = b.UNITID
INNER JOIN `ipeds_tables`.`IC2022_sorted` c ON a.UNITID = c.UNITID
WHERE a.CSTOTLT >= 50 AND b.EFTOTAL >= 200;

ALTER TABLE `ipeds_tables`.`ipeds_filter`
ADD PRIMARY KEY (`UNITID`);

-- Joining IPEDS tables --
CREATE TABLE `ipeds_tables`.`ipeds_final` AS
SELECT
	a.UNITID,
    b.INSTNM,
    b.STABBR,
    b.EIN,
    b.OPEID,
    a.CSTOTLT,
    a.EFTOTAL,
    a.CNTLAFFI,
    a.STUSRV8,
    c.SAINSTM,
    c.SAINSTW,
    c.SAOUTLM,
    c.SAOUTLW,
    c.AVGSALM,
    c.AVGSALW,
    d.HRBKAAT,
    d.HRHISPT,
    d.HRASIAT,
    e.HRTOTLW_101,
    e.HRTOTLW_102,
    e.HRTOTLW_200,
    e.HRBKAAW_101,
    e.HRBKAAW_102,
    e.HRBKAAW_200,
    e.HRHISPW_101,
    e.HRHISPW_102,
    e.HRHISPW_200,
    e.HRASIAW_101,
    e.HRASIAW_102,
    e.HRASIAW_200
FROM `ipeds_tables`.`ipeds_filter` a
INNER JOIN `ipeds_2024_db`.`HD2022` b ON a.UNITID = b.UNITID
INNER JOIN `ipeds_tables`.`SAL2022_IS_sorted` c ON a.UNITID = c.UNITID
INNER JOIN `ipeds_tables`.`S2022_OC_sorted` d ON a.UNITID = d.UNITID
INNER JOIN `ipeds_tables`.`S2022_IS_sorted` e ON a.UNITID = e.UNITID
ORDER BY a.`UNITID` ASC;

ALTER TABLE `ipeds_tables`.`ipeds_final`
ADD PRIMARY KEY (`UNITID`);
-- End of IPEDS DB Processing --

-- Processing IRS DB --
CREATE TABLE `irs990`.`irs_final` AS
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY `EIN` 
               ORDER BY `YEAR` DESC, `IRS_MONTH` DESC
           ) AS rn
    FROM `irs990`.`Organizations`
) AS ranked
WHERE rn = 1;

ALTER TABLE `irs990`.`irs_final`
ADD PRIMARY KEY (`EIN`);
-- End of IRS DB Processing --

-- Merging IPEDS, CSS, IRS Tables into GF2024 --
CREATE TABLE `merged_ipeds_css_irs`.`gf2024` AS
SELECT
	a.UNITID AS UNITID,
    a.INSTNM AS INSTNM,
    a.STABBR AS STATE,
    a.EIN AS EIN,
    a.OPEID AS OPEID,
    a.CSTOTLT AS DEGREETOT,
    a.EFTOTAL AS ENROLLTOT,
    a.CNTLAFFI AS INSTFUNDINGTYPE,
    a.STUSRV8 AS HASDAYCARE,
    a.SAINSTM AS ACADEMICPOPM,
    a.SAINSTW AS ACADEMICPOPF,
    a.SAOUTLM AS SALARYTOTM,
    a.SAOUTLW AS SALARYTOTF,  
    a.AVGSALM AS SALARYPPM,
    a.AVGSALW AS SALARYPPF,
    a.HRBKAAT AS NONACD_BLKPCT,
    a.HRHISPT AS NONACD_HSPPCT,
    a.HRASIAT AS NONACD_ASIAPCT,
    a.HRTOTLW_101 AS PROFWOMENPCT,
    a.HRTOTLW_102 AS ASSOCPROFWOMENPCT,
    a.HRTOTLW_200 AS TENUREWOMENPCT,
    a.HRBKAAW_101 AS BLACKPROFWOMENPCT,
    a.HRBKAAW_102 AS BLACKASSOCPROFWOMENPCT,
    a.HRBKAAW_200 AS BLACKTENUREWOMENPCT,
    a.HRHISPW_101 AS HISPANICPROFWOMENPCT,
    a.HRHISPW_102 AS HISPANICASSOCPROFWOMENPCT,
    a.HRHISPW_200 AS HISPANICTENUREWOMENPCT,
    a.HRASIAW_101 AS ASIANPROFWOMENPCT, 
    a.HRASIAW_102 AS ASIANASSOCPROFWOMENPCT,
    a.HRASIAW_200 AS ASIANTENUREWOMENPCT,
    b.YEARLYHATECRIME AS YEARLYHATECRIME,
    b.YEARLYHATECRIME1K AS YEARLYHATECRIME1K,
    c.YEARLYVAWA AS YEARLYVAWA,
    c.YEARLYVAWA1K AS YEARLYVAWA1K,
    d.IRS_MONTH AS IRS_MONTH,
    d.`YEAR` AS `YEAR`,
    d.PERCENTAGE_WOMEN_TRUSTEES AS PERCENTAGE_WOMEN_TRUSTEES,
    d.PERCENTAGE_WOMEN_KEY_EMPLOYEES AS PERCENTAGE_WOMEN_KEY_EMPLOYEES,
    d.WHISTLEBLOWER_POLICY AS WHISTLEBLOWER_POLICY,
    d.CEO_REVIEWED_COMPENSATION AS CEO_REVIEWED_COMPENSATION,
    d.OTHER_REVIEWED_COMPENSATION AS OTHER_REVIEWED_COMPENSATION,
    d.MALE_TO_FEMALE_PAY_RATIO AS MALE_TO_FEMALE_PAY_RATIO,
    d.PRESIDENT_TO_AVERAGE_PAY_RATIO AS PRESIDENT_TO_AVERAGE_PAY_RATIO
FROM `ipeds_tables`.`ipeds_final` a
INNER JOIN `css`.`css_hate_final` b ON a.OPEID = b.OPEID
INNER JOIN `css`.`css_vawa_final` c ON a.OPEID = c.OPEID
LEFT JOIN `irs990`.`irs_final` d ON a.EIN = d.EIN
ORDER BY a.`UNITID` ASC;

ALTER TABLE `merged_ipeds_css_irs`.`gf2024`
ADD PRIMARY KEY (`UNITID`);
-- End of Merging --

-- Re-enabling SQL Safe Mode --
SET SQL_SAFE_UPDATES = 1;

-- End of Combined SQL Script --