-- Processing S2022_IS --
CREATE TABLE `ipeds_tables`.`S2022_IS_temp` AS
SELECT * 
FROM `ipeds_2024_db`.`S2022_IS`
WHERE `SISCAT` IN (101, 102, 200)
ORDER BY `UNITID` ASC;

CREATE TABLE `ipeds_tables`.`S2022_IS_sorted` AS
SELECT
    UNITID,
    SUM(CASE WHEN SISCAT = 101 THEN FACSTAT ELSE 0 END) AS FACSTAT_101,
    SUM(CASE WHEN SISCAT = 101 THEN ARANK ELSE 0 END) AS ARANK_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLT ELSE 0 END) AS HRTOTLT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLM ELSE 0 END) AS HRTOTLM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRAIANT ELSE 0 END) AS HRAIANT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRAIANM ELSE 0 END) AS HRAIANM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRAIANW ELSE 0 END) AS HRAIANW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAT ELSE 0 END) AS HRASIAT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAM ELSE 0 END) AS HRASIAM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRASIAW ELSE 0 END) AS HRASIAW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAT ELSE 0 END) AS HRBKAAT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAM ELSE 0 END) AS HRBKAAM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPT ELSE 0 END) AS HRHISPT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPM ELSE 0 END) AS HRHISPM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRHISPW ELSE 0 END) AS HRHISPW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNHPIT ELSE 0 END) AS HRNHPIT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNHPIM ELSE 0 END) AS HRNHPIM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNHPIW ELSE 0 END) AS HRNHPIW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRWHITT ELSE 0 END) AS HRWHITT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRWHITM ELSE 0 END) AS HRWHITM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRWHITW ELSE 0 END) AS HRWHITW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HR2MORT ELSE 0 END) AS HR2MORT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HR2MORM ELSE 0 END) AS HR2MORM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HR2MORW ELSE 0 END) AS HR2MORW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRUNKNT ELSE 0 END) AS HRUNKNT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRUNKNM ELSE 0 END) AS HRUNKNM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRUNKNW ELSE 0 END) AS HRUNKNW_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNRALT ELSE 0 END) AS HRNRALT_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNRALM ELSE 0 END) AS HRNRALM_101,
    SUM(CASE WHEN SISCAT = 101 THEN HRNRALW ELSE 0 END) AS HRNRALW_101,
    SUM(CASE WHEN SISCAT = 102 THEN FACSTAT ELSE 0 END) AS FACSTAT_102,
    SUM(CASE WHEN SISCAT = 102 THEN ARANK ELSE 0 END) AS ARANK_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLT ELSE 0 END) AS HRTOTLT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLM ELSE 0 END) AS HRTOTLM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRAIANT ELSE 0 END) AS HRAIANT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRAIANM ELSE 0 END) AS HRAIANM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRAIANW ELSE 0 END) AS HRAIANW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAT ELSE 0 END) AS HRASIAT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAM ELSE 0 END) AS HRASIAM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRASIAW ELSE 0 END) AS HRASIAW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAT ELSE 0 END) AS HRBKAAT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAM ELSE 0 END) AS HRBKAAM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPT ELSE 0 END) AS HRHISPT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPM ELSE 0 END) AS HRHISPM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRHISPW ELSE 0 END) AS HRHISPW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNHPIT ELSE 0 END) AS HRNHPIT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNHPIM ELSE 0 END) AS HRNHPIM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNHPIW ELSE 0 END) AS HRNHPIW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRWHITT ELSE 0 END) AS HRWHITT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRWHITM ELSE 0 END) AS HRWHITM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRWHITW ELSE 0 END) AS HRWHITW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HR2MORT ELSE 0 END) AS HR2MORT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HR2MORM ELSE 0 END) AS HR2MORM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HR2MORW ELSE 0 END) AS HR2MORW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRUNKNT ELSE 0 END) AS HRUNKNT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRUNKNM ELSE 0 END) AS HRUNKNM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRUNKNW ELSE 0 END) AS HRUNKNW_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNRALT ELSE 0 END) AS HRNRALT_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNRALM ELSE 0 END) AS HRNRALM_102,
    SUM(CASE WHEN SISCAT = 102 THEN HRNRALW ELSE 0 END) AS HRNRALW_102,
    SUM(CASE WHEN SISCAT = 200 THEN FACSTAT ELSE 0 END) AS FACSTAT_200,
    SUM(CASE WHEN SISCAT = 200 THEN ARANK ELSE 0 END) AS ARANK_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLT ELSE 0 END) AS HRTOTLT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLM ELSE 0 END) AS HRTOTLM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRAIANT ELSE 0 END) AS HRAIANT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRAIANM ELSE 0 END) AS HRAIANM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRAIANW ELSE 0 END) AS HRAIANW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAT ELSE 0 END) AS HRASIAT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAM ELSE 0 END) AS HRASIAM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRASIAW ELSE 0 END) AS HRASIAW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAT ELSE 0 END) AS HRBKAAT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAM ELSE 0 END) AS HRBKAAM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPT ELSE 0 END) AS HRHISPT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPM ELSE 0 END) AS HRHISPM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRHISPW ELSE 0 END) AS HRHISPW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNHPIT ELSE 0 END) AS HRNHPIT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNHPIM ELSE 0 END) AS HRNHPIM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNHPIW ELSE 0 END) AS HRNHPIW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRWHITT ELSE 0 END) AS HRWHITT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRWHITM ELSE 0 END) AS HRWHITM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRWHITW ELSE 0 END) AS HRWHITW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HR2MORT ELSE 0 END) AS HR2MORT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HR2MORM ELSE 0 END) AS HR2MORM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HR2MORW ELSE 0 END) AS HR2MORW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRUNKNT ELSE 0 END) AS HRUNKNT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRUNKNM ELSE 0 END) AS HRUNKNM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRUNKNW ELSE 0 END) AS HRUNKNW_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNRALT ELSE 0 END) AS HRNRALT_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNRALM ELSE 0 END) AS HRNRALM_200,
    SUM(CASE WHEN SISCAT = 200 THEN HRNRALW ELSE 0 END) AS HRNRALW_200
FROM `ipeds_tables`.`S2022_IS_temp`
GROUP BY `UNITID`;

ALTER TABLE `ipeds_tables`.`S2022_IS_sorted`
ADD PRIMARY KEY (`UNITID`);

DROP TABLE `ipeds_tables`.`S2022_IS_temp`;

-- Processing S2022_OC --
CREATE TABLE `ipeds_tables`.`S2022_OC_temp` AS
SELECT * 
FROM `ipeds_2024_db`.`S2022_OC`
WHERE `OCCUPCAT` IN (220, 230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 420, 490)
ORDER BY `UNITID` ASC;

CREATE TABLE `ipeds_tables`.`S2022_OC_sorted` AS
SELECT 
    UNITID,
	SUM(STAFFCAT) AS STAFFCAT,
    SUM(HRTOTLT) AS HRTOTLT,
    SUM(HRTOTLM) AS HRTOTLM,
    SUM(HRTOTLW) AS HRTOTLW,
    SUM(HRAIANT) AS HRAIANT,
    SUM(HRAIANM) AS HRAIANM,
    SUM(HRAIANW) AS HRAIANW,
    SUM(HRASIAT) AS HRASIAT,
    SUM(HRASIAM) AS HRASIAM,
    SUM(HRASIAW) AS HRASIAW,
    SUM(HRBKAAT) AS HRBKAAT,
    SUM(HRBKAAM) AS HRBKAAM,
    SUM(HRBKAAW) AS HRBKAAW,
    SUM(HRHISPT) AS HRHISPT,
    SUM(HRHISPM) AS HRHISPM,
    SUM(HRHISPW) AS HRHISPW,
    SUM(HRNHPIT) AS HRNHPIT,
    SUM(HRNHPIM) AS HRNHPIM,
    SUM(HRNHPIW) AS HRNHPIW,
    SUM(HRWHITT) AS HRWHITT,
    SUM(HRWHITM) AS HRWHITM,
    SUM(HRWHITW) AS HRWHITW,
    SUM(HR2MORT) AS HR2MORT,
    SUM(HR2MORM) AS HR2MORM,
    SUM(HR2MORW) AS HR2MORW,
    SUM(HRUNKNT) AS HRUNKNT,
    SUM(HRUNKNM) AS HRUNKNM,
    SUM(HRUNKNW) AS HRUNKNW,
    SUM(HRNRALT) AS HRNRALT,
    SUM(HRNRALM) AS HRNRALM,
    SUM(HRNRALW) AS HRNRALW
FROM `ipeds_tables`.`S2022_OC_temp`
GROUP BY UNITID;

ALTER TABLE `ipeds_tables`.`S2022_OC_sorted`
ADD PRIMARY KEY (`UNITID`);

DROP TABLE `ipeds_tables`.`S2022_OC_temp`;

-- Processing SAL2022_IS --
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE `ipeds_tables`.`SAL2022_IS_sorted` AS
SELECT * 
FROM `ipeds_2024_db`.`SAL2022_IS`
WHERE `ARANK` IN (7)
ORDER BY `UNITID` ASC;

ALTER TABLE `ipeds_tables`.`SAL2022_IS_sorted`
ADD COLUMN AVGSALM DOUBLE,
ADD COLUMN AVGSALW DOUBLE;

UPDATE `ipeds_tables`.`SAL2022_IS_sorted`
SET 
  AVGSALM = CASE 
              WHEN SAINSTM = 0 OR SAOUTLM = 0 THEN NULL
              ELSE SAOUTLM / SAINSTM 
            END,
  AVGSALW = CASE 
              WHEN SAINSTW = 0 OR SAOUTLW = 0 THEN NULL
              ELSE SAOUTLW / SAINSTW 
            END;

ALTER TABLE `ipeds_tables`.`SAL2022_IS_sorted`
ADD PRIMARY KEY (`UNITID`);

SET SQL_SAFE_UPDATES = 1;
-- Processing IC2022 --
CREATE TABLE `ipeds_tables`.`IC2022_sorted` AS
SELECT *
FROM `ipeds_2024_db`.`IC2022`
WHERE (
    LEVEL3 = 1 OR
    LEVEL4 = 1 OR
    LEVEL5 = 1 OR
    LEVEL6 = 1 OR
    LEVEL7 = 1 OR
    LEVEL8 = 1 OR
    LEVEL17 = 1 OR
    LEVEL18 = 1 OR
    LEVEL19 = 1
)
AND `CNTLAFFI` IN (1, 3, 4);

ALTER TABLE `ipeds_tables`.`IC2022_sorted`
ADD PRIMARY KEY (`UNITID`);

-- No Processing Needed for C2023_B --

-- Processing EF2022 --
CREATE TABLE `ipeds_tables`.`EF2022_sorted` AS
SELECT * 
FROM `ipeds_2024_db`.`EF2022`
WHERE `EFLEVEL` IN (10)
ORDER BY `UNITID` ASC;

ALTER TABLE `ipeds_tables`.`EF2022_sorted`
ADD PRIMARY KEY (`UNITID`);
