# -*- coding: utf-8 -*-
"""IPEDS preprocessing scripts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFEsG301GgDWYRI57TI0t7HrD4oeBe1c

## Python Script for generating IPEDS SQL scripts
"""

import pandas as pd

# Load your CSV file
csv_path = "S2023_OC.csv"  # <-- replace with the path to your CSV file
df = pd.read_csv(csv_path)

# Define the column to group by and any columns you want to exclude from the SUM
groupby_col = 'UNITID'
exclude_from_sum = [groupby_col, 'OCCUPCAT', 'FTPT', 'SABDTYPE']  # Don't sum these

# Identify numeric columns to SUM
numeric_cols = df.select_dtypes(include='number').columns.tolist()
sum_cols = [col for col in numeric_cols if col not in exclude_from_sum]

# Generate the SUM SQL parts
sum_sql_parts = [f"    SUM({col}) AS {col}" for col in sum_cols]
sum_sql = ",\n".join(sum_sql_parts)

# Generate the full SQL script
sql_script = f"""
CREATE TABLE `ipeds_tables`.`S2022_OC_sorted` AS
SELECT
    {groupby_col},
    {sum_sql},
    100 AS OCCUPCAT
FROM `ipeds_tables`.`S2022_OC_temp`
GROUP BY {groupby_col};
"""

print(sql_script)

import pandas as pd

# Load your CSV
df = pd.read_csv("S2023_IS_sorted_decimal.csv")

value_columns = [col for col in df.columns if col not in ["UNITID", "SISCAT"]]
siscat_values = sorted(df["SISCAT"].dropna().unique().astype(int))

sql_lines = ["SELECT\n    UNITID,"]
for siscat in siscat_values:
    for col in value_columns:
        line = f"    SUM(CASE WHEN SISCAT = {siscat} THEN {col} ELSE 0 END) AS {col}_{siscat},"
        sql_lines.append(line)

# Remove trailing comma on the last column
sql_lines[-1] = sql_lines[-1].rstrip(',')

sql_lines.append("FROM your_table")
sql_lines.append("GROUP BY UNITID;")

# Output the SQL
# pivot_sql = "\n".join(sql_lines)
# print(pivot_sql)

# Save to a .sql file
with open("S2022_IS_flatten.sql", "w") as f:
    f.write("\n".join(sql_lines))

print("SQL script generated successfully: S2022_IS_flatten.sql")

