-- Merging CSS, IPEDS, IRS --

CREATE TABLE `merged_ipeds_css_irs`.`gf2024` AS
SELECT
	a.UNITID AS UNITID,
    a.INSTNM AS INSTNM,
    a.STABBR AS STATE,
    a.EIN AS EIN,
    a.OPEID AS OPEID,
    a.CSTOTLT AS DEGREETOT,
    a.EFTOTAL AS ENROLLTOT,
    a.CNTLAFFI AS INSTFUNDINGTYPE,
    a.STUSRV8 AS HASDAYCARE,
    a.SAINSTM AS ACADEMICPOPM,
    a.SAINSTW AS ACADEMICPOPF,
    a.SAOUTLM AS SALARYTOTM,
    a.SAOUTLW AS SALARYTOTF,  
    a.AVGSALM AS SALARYPPM,
    a.AVGSALW AS SALARYPPF,
    a.HRBKAAT AS NONACD_BLKPCT,
    a.HRHISPT AS NONACD_HSPPCT,
    a.HRASIAT AS NONACD_ASIAPCT,
    a.HRTOTLW_101 AS PROFWOMENPCT,
    a.HRTOTLW_102 AS ASSOCPROFWOMENPCT,
    a.HRTOTLW_200 AS TENUREWOMENPCT,
    a.HRBKAAW_101 AS BLACKPROFWOMENPCT,
    a.HRBKAAW_102 AS BLACKASSOCPROFWOMENPCT,
    a.HRBKAAW_200 AS BLACKTENUREWOMENPCT,
    a.HRHISPW_101 AS HISPANICPROFWOMENPCT,
    a.HRHISPW_102 AS HISPANICASSOCPROFWOMENPCT,
    a.HRHISPW_200 AS HISPANICTENUREWOMENPCT,
    a.HRASIAW_101 AS ASIANPROFWOMENPCT, 
    a.HRASIAW_102 AS ASIANASSOCPROFWOMENPCT,
    a.HRASIAW_200 AS ASIANTENUREWOMENPCT,
    b.YEARLYHATECRIME AS YEARLYHATECRIME,
    b.YEARLYHATECRIME1K AS YEARLYHATECRIME1K,
    c.YEARLYVAWA AS YEARLYVAWA,
    c.YEARLYVAWA1K AS YEARLYVAWA1K,
    d.IRS_MONTH AS IRS_MONTH,
    d.`YEAR` AS `YEAR`,
    d.PERCENTAGE_WOMEN_TRUSTEES AS PERCENTAGE_WOMEN_TRUSTEES,
    d.PERCENTAGE_WOMEN_KEY_EMPLOYEES AS PERCENTAGE_WOMEN_KEY_EMPLOYEES,
    d.WHISTLEBLOWER_POLICY AS WHISTLEBLOWER_POLICY,
    d.CEO_REVIEWED_COMPENSATION AS CEO_REVIEWED_COMPENSATION,
    d.OTHER_REVIEWED_COMPENSATION AS OTHER_REVIEWED_COMPENSATION,
    d.MALE_TO_FEMALE_PAY_RATIO AS MALE_TO_FEMALE_PAY_RATIO,
    d.PRESIDENT_TO_AVERAGE_PAY_RATIO AS PRESIDENT_TO_AVERAGE_PAY_RATIO
FROM `ipeds_tables`.`ipeds_final` a
INNER JOIN `css`.`css_hate_final` b ON a.OPEID = b.OPEID
INNER JOIN `css`.`css_vawa_final` c ON a.OPEID = c.OPEID
LEFT JOIN `irs990`.`irs_final` d ON a.EIN = d.EIN
ORDER BY a.`UNITID` ASC;

ALTER TABLE `merged_ipeds_css_irs`.`gf2024`
ADD PRIMARY KEY (`UNITID`);

