
INSERT INTO `PublicFacingData`.`SchoolData` (
	UNITID,
	INSTNM, 
	STATE,
	EIN,
	OPEID,
	DEGREETOT,
	ENROLLTOT,
	INSTFUNDINGTYPE,
	HASDAYCARE,
	ACDPOPM,
	ACDPOPF,
	SALARYTOTACDM,
	SALARYTOTACDF,
	ACDTOTMEN,
	ACDTOTWOMEN, 
	ACDTOTWHIT,
	ACDTOTBLAK,
	ACDTOTASIA,
	ACDTOTHISP,
	ACDTOTNHPI,
	ACDTOTNAMC,
	ACDTOTNRES,
	ACDTOTTWOP,
	ACDTOTUNKN, 
	PROFMEN,
	PROFWOMEN, 
	PROFWHIT, 
	PROFBLAK, 
	PROFASIA, 
	PROFHISP, 
	PROFNHPI, 
	PROFNAMC, 
	PROFNRES, 
	PROFTWOP, 
	PROFUNKN, 
	ASSOCIATEPROFMEN, 
	ASSOCIATEPROFWOMEN, 
	ASSOCIATEPROFWHIT, 
	ASSOCIATEPROFBLAK, 
	ASSOCIATEPROFASIA, 
	ASSOCIATEPROFHISP, 
	ASSOCIATEPROFNHPI, 
	ASSOCIATEPROFNAMC, 
	ASSOCIATEPROFNRES, 
	ASSOCIATEPROFTWOP, 
	ASSOCIATEPROFUNKN, 
	ASSISTANTPROFMEN, 
	ASSISTANTPROFWOMEN, 
	ASSISTANTPROFWHIT, 
	ASSISTANTPROFBLAK, 
	ASSISTANTPROFASIA, 
	ASSISTANTPROFHISP, 
	ASSISTANTPROFNHPI, 
	ASSISTANTPROFNAMC, 
	ASSISTANTPROFNRES, 
	ASSISTANTPROFTWOP, 
	ASSISTANTPROFUNKN, 
	INSTRUCTORMEN, 
	INSTRUCTORWOMEN, 
	INSTRUCTORWHIT, 
	INSTRUCTORBLAK, 
	INSTRUCTORASIA, 
	INSTRUCTORHISP, 
	INSTRUCTORNHPI, 
	INSTRUCTORNAMC, 
	INSTRUCTORNRES, 
	INSTRUCTORTWOP, 
	INSTRUCTORUNKN, 
	LECTURERMEN, 
	LECTURERWOMEN, 
	LECTURERWHIT, 
	LECTURERBLAK, 
	LECTURERASIA, 
	LECTURERHISP, 
	LECTURERNHPI, 
	LECTURERNAMC, 
	LECTURERNRES, 
	LECTURERTWOP, 
	LECTURERUNKN, 
	NONACDMEN, 
	NONACDWOMEN, 
	NONACDWHIT, 
	NONACDBLAK, 
	NONACDASIA, 
	NONACDHISP, 
	NONACDNHPI, 
	NONACDNAMC, 
	NONACDNRES, 
	NONACDTWOP, 
	NONACDUNKN, 
-- 	CSSPOPULATION2020, 
-- 	Y2020HATECRIME, 
-- 	Y2020HATECRIME1K,
-- 	Y2020VAWA,
-- 	Y2020VAWA1K, 
-- 	CSSPOPULATION2021, 
-- 	Y2021HATECRIME, 
-- 	Y2021HATECRIME1K,
-- 	Y2021VAWA,
-- 	Y2021VAWA1K, 
	CSSPOPULATION2022, 
	Y2022HATECRIME, 
	Y2022HATECRIME1K,
	Y2022VAWA,
	Y2022VAWA1K, 
	CSSPOPULATION2023, 
	Y2023HATECRIME, 
	Y2023HATECRIME1K,
	Y2023VAWA,
	Y2023VAWA1K, 
	CSSPOPULATION2024, 
	Y2024HATECRIME, 
	Y2024HATECRIME1K,
	Y2024VAWA,
	Y2024VAWA1K
)
WITH cssY22 AS (
	SELECT
        cssh22.OPEID,
		MAX(cssh22.Total) AS SchoolPopulation,
		SUM(
			cssh22.MURD21 +
			cssh22.RAPE21 +
			cssh22.FOND21 +
			cssh22.INCE21 +
			cssh22.STAT21 +
			cssh22.ROBBE21 +
			cssh22.AGG_A21 +
			cssh22.BURGLA21 +
			cssh22.VEHIC21 +
			cssh22.ARSON21 +
			cssh22.SIM_A21 +
			cssh22.LAR_T21 +
			cssh22.INTIM21 +
			cssh22.VANDAL21
		) AS Y2022HATECRIME,
		SUM(
			cssv22.DOMEST21 +
			cssv22.DATING21 +
			cssv22.STALK21
		) AS Y2022VAWA
	FROM `css2022`.`css_hate` cssh22
	JOIN `css2022`.`css_vawa` cssv22
	USING (OPEID)
	GROUP BY OPEID
),
cssY23 AS (
	SELECT 
        cssh23.OPEID,
		MAX(cssh23.Total) AS SchoolPopulation,
		SUM(
			cssh23.MURD22 +
			cssh23.RAPE22 +
			cssh23.FOND22 +
			cssh23.INCE22 +
			cssh23.STAT22 +
			cssh23.ROBBE22 +
			cssh23.AGG_A22 +
			cssh23.BURGLA22 +
			cssh23.VEHIC22 +
			cssh23.ARSON22 +
			cssh23.SIM_A22 +
			cssh23.LAR_T22 +
			cssh23.INTIM22 +
			cssh23.VANDAL22
		) AS Y2023HATECRIME,
		SUM(
			cssv23.DOMEST22 +
			cssv23.DATING22 +
			cssv23.STALK22
		) AS Y2023VAWA
	FROM `css2023`.`css_hate` cssh23
	JOIN `css2023`.`css_vawa` cssv23
	USING (OPEID)
	GROUP BY OPEID
),
cssY24 AS (
	SELECT 
        cssh24.OPEID,
		MAX(cssh24.Total) AS SchoolPopulation,
		SUM(
			cssh24.MURD23 +
			cssh24.RAPE23 +
			cssh24.FOND23 +
			cssh24.INCE23 +
			cssh24.STAT23 +
			cssh24.ROBBE23 +
			cssh24.AGG_A23 +
			cssh24.BURGLA23 +
			cssh24.VEHIC23 +
			cssh24.ARSON23 +
			cssh24.SIM_A23 +
			cssh24.LAR_T23 +
			cssh24.INTIM23 +
			cssh24.VANDAL23
		) AS Y2024HATECRIME,
		SUM(
			cssv24.DOMEST23 +
			cssv24.DATING23 +
			cssv24.STALK23
		) AS Y2023VAWA
	FROM `css2024`.`css_hate` cssh24
	JOIN `css2024`.`css_vawa` cssv24
	USING (OPEID)
	GROUP BY OPEID
),
ipedsS2022ISByAcademicRank AS (
	SELECT
		UNITID,
		SUM(CASE WHEN SISCAT = 1 THEN HRTOTLM ELSE 0 END) AS ACDTOTMEN,
		SUM(CASE WHEN SISCAT = 1 THEN HRTOTLW ELSE 0 END) AS ACDTOTWOMEN,
		SUM(CASE WHEN SISCAT = 1 THEN HRWHITT ELSE 0 END) AS ACDTOTWHIT,
		SUM(CASE WHEN SISCAT = 1 THEN HRBKAAT ELSE 0 END) AS ACDTOTBLAK,
		SUM(CASE WHEN SISCAT = 1 THEN HRASIAT ELSE 0 END) AS ACDTOTASIA,
		SUM(CASE WHEN SISCAT = 1 THEN HRHISPT ELSE 0 END) AS ACDTOTHISP,
		SUM(CASE WHEN SISCAT = 1 THEN HRNHPIT ELSE 0 END) AS ACDTOTNHPI,
		SUM(CASE WHEN SISCAT = 1 THEN HRAIANT ELSE 0 END) AS ACDTOTNAMC,
		SUM(CASE WHEN SISCAT = 1 THEN HRNRALT ELSE 0 END) AS ACDTOTNRES,
		SUM(CASE WHEN SISCAT = 1 THEN HR2MORT ELSE 0 END) AS ACDTOTTWOP,
		SUM(CASE WHEN SISCAT = 1 THEN HRUNKNT ELSE 0 END) AS ACDTOTUNKN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLM ELSE 0 END) AS PROFMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS PROFWOMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRWHITT ELSE 0 END) AS PROFWHIT,
		SUM(CASE WHEN SISCAT = 101 THEN HRBKAAT ELSE 0 END) AS PROFBLAK,
		SUM(CASE WHEN SISCAT = 101 THEN HRASIAT ELSE 0 END) AS PROFASIA,
		SUM(CASE WHEN SISCAT = 101 THEN HRHISPT ELSE 0 END) AS PROFHISP,
		SUM(CASE WHEN SISCAT = 101 THEN HRNHPIT ELSE 0 END) AS PROFNHPI,
		SUM(CASE WHEN SISCAT = 101 THEN HRAIANT ELSE 0 END) AS PROFNAMC,
		SUM(CASE WHEN SISCAT = 101 THEN HRNRALT ELSE 0 END) AS PROFNRES,
		SUM(CASE WHEN SISCAT = 101 THEN HR2MORT ELSE 0 END) AS PROFTWOP,
		SUM(CASE WHEN SISCAT = 101 THEN HRUNKNT ELSE 0 END) AS PROFUNKN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLM ELSE 0 END) AS ASSOCIATEPROFMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS ASSOCIATEPROFWOMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRWHITT ELSE 0 END) AS ASSOCIATEPROFWHIT,
		SUM(CASE WHEN SISCAT = 102 THEN HRBKAAT ELSE 0 END) AS ASSOCIATEPROFBLAK,
		SUM(CASE WHEN SISCAT = 102 THEN HRASIAT ELSE 0 END) AS ASSOCIATEPROFASIA,
		SUM(CASE WHEN SISCAT = 102 THEN HRHISPT ELSE 0 END) AS ASSOCIATEPROFHISP,
		SUM(CASE WHEN SISCAT = 102 THEN HRNHPIT ELSE 0 END) AS ASSOCIATEPROFNHPI,
		SUM(CASE WHEN SISCAT = 102 THEN HRAIANT ELSE 0 END) AS ASSOCIATEPROFNAMC,
		SUM(CASE WHEN SISCAT = 102 THEN HRNRALT ELSE 0 END) AS ASSOCIATEPROFNRES,
		SUM(CASE WHEN SISCAT = 102 THEN HR2MORT ELSE 0 END) AS ASSOCIATEPROFTWOP,
		SUM(CASE WHEN SISCAT = 102 THEN HRUNKNT ELSE 0 END) AS ASSOCIATEPROFUNKN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLM ELSE 0 END) AS ASSISTANTPROFMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLW ELSE 0 END) AS ASSISTANTPROFWOMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRWHITT ELSE 0 END) AS ASSISTANTPROFWHIT,
		SUM(CASE WHEN SISCAT = 103 THEN HRBKAAT ELSE 0 END) AS ASSISTANTPROFBLAK,
		SUM(CASE WHEN SISCAT = 103 THEN HRASIAT ELSE 0 END) AS ASSISTANTPROFASIA,
		SUM(CASE WHEN SISCAT = 103 THEN HRHISPT ELSE 0 END) AS ASSISTANTPROFHISP,
		SUM(CASE WHEN SISCAT = 103 THEN HRNHPIT ELSE 0 END) AS ASSISTANTPROFNHPI,
		SUM(CASE WHEN SISCAT = 103 THEN HRAIANT ELSE 0 END) AS ASSISTANTPROFNAMC,
		SUM(CASE WHEN SISCAT = 103 THEN HRNRALT ELSE 0 END) AS ASSISTANTPROFNRES,
		SUM(CASE WHEN SISCAT = 103 THEN HR2MORT ELSE 0 END) AS ASSISTANTPROFTWOP,
		SUM(CASE WHEN SISCAT = 103 THEN HRUNKNT ELSE 0 END) AS ASSISTANTPROFUNKN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLM ELSE 0 END) AS INSTRUCTORMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLW ELSE 0 END) AS INSTRUCTORWOMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRWHITT ELSE 0 END) AS INSTRUCTORWHIT,
		SUM(CASE WHEN SISCAT = 104 THEN HRBKAAT ELSE 0 END) AS INSTRUCTORBLAK,
		SUM(CASE WHEN SISCAT = 104 THEN HRASIAT ELSE 0 END) AS INSTRUCTORASIA,
		SUM(CASE WHEN SISCAT = 104 THEN HRHISPT ELSE 0 END) AS INSTRUCTORHISP,
		SUM(CASE WHEN SISCAT = 104 THEN HRNHPIT ELSE 0 END) AS INSTRUCTORNHPI,
		SUM(CASE WHEN SISCAT = 104 THEN HRAIANT ELSE 0 END) AS INSTRUCTORNAMC,
		SUM(CASE WHEN SISCAT = 104 THEN HRNRALT ELSE 0 END) AS INSTRUCTORNRES,
		SUM(CASE WHEN SISCAT = 104 THEN HR2MORT ELSE 0 END) AS INSTRUCTORTWOP,
		SUM(CASE WHEN SISCAT = 104 THEN HRUNKNT ELSE 0 END) AS INSTRUCTORUNKN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLM ELSE 0 END) AS LECTURERMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLW ELSE 0 END) AS LECTURERWOMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRWHITT ELSE 0 END) AS LECTURERWHIT,
		SUM(CASE WHEN SISCAT = 105 THEN HRBKAAT ELSE 0 END) AS LECTURERBLAK,
		SUM(CASE WHEN SISCAT = 105 THEN HRASIAT ELSE 0 END) AS LECTURERASIA,
		SUM(CASE WHEN SISCAT = 105 THEN HRHISPT ELSE 0 END) AS LECTURERHISP,
		SUM(CASE WHEN SISCAT = 105 THEN HRNHPIT ELSE 0 END) AS LECTURERNHPI,
		SUM(CASE WHEN SISCAT = 105 THEN HRAIANT ELSE 0 END) AS LECTURERNAMC,
		SUM(CASE WHEN SISCAT = 105 THEN HRNRALT ELSE 0 END) AS LECTURERNRES,
		SUM(CASE WHEN SISCAT = 105 THEN HR2MORT ELSE 0 END) AS LECTURERTWOP,
		SUM(CASE WHEN SISCAT = 105 THEN HRUNKNT ELSE 0 END) AS LECTURERUNKN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLM ELSE 0 END) AS NORANKMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLW ELSE 0 END) AS NORANKWOMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRWHITT ELSE 0 END) AS NORANKWHIT,
		SUM(CASE WHEN SISCAT = 106 THEN HRBKAAT ELSE 0 END) AS NORANKBLAK,
		SUM(CASE WHEN SISCAT = 106 THEN HRASIAT ELSE 0 END) AS NORANKASIA,
		SUM(CASE WHEN SISCAT = 106 THEN HRHISPT ELSE 0 END) AS NORANKHISP,
		SUM(CASE WHEN SISCAT = 106 THEN HRNHPIT ELSE 0 END) AS NORANKNHPI,
		SUM(CASE WHEN SISCAT = 106 THEN HRAIANT ELSE 0 END) AS NORANKNAMC,
		SUM(CASE WHEN SISCAT = 106 THEN HRNRALT ELSE 0 END) AS NORANKNRES,
		SUM(CASE WHEN SISCAT = 106 THEN HR2MORT ELSE 0 END) AS NORANKTWOP,
		SUM(CASE WHEN SISCAT = 106 THEN HRUNKNT ELSE 0 END) AS NORANKUNKN
	FROM `ipeds_2024_db`.`S2022_IS`
	GROUP BY `UNITID`
),
ipedsS2022OCByOccupation AS (
	SELECT 
		UNITID,
		SUM(HRTOTLM) AS NONACDMEN,
		SUM(HRTOTLW) AS NONACDWOMEN,
		SUM(HRWHITT) AS NONACDWHIT,
		SUM(HRBKAAT) AS NONACDBLAK,
		SUM(HRASIAT) AS NONACDASIA,
		SUM(HRHISPT) AS NONACDHISP,
		SUM(HRNHPIT) AS NONACDNHPI,
		SUM(HRAIANT) AS NONACDNAMC,
		SUM(HRNRALT) AS NONACDNRES,
		SUM(HR2MORT) AS NONACDTWOP,
		SUM(HRUNKNT) AS NONACDUNKN
	FROM `ipeds_2024_db`.`S2022_OC`
	WHERE `OCCUPCAT` IN (230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390)
	GROUP BY UNITID
),
ipedsSAL2022ISBYAcademicRank AS (
	SELECT 
		UNITID,
		SAINSTM AS ACDPOPM,
		SAINSTW AS ACDPOPF,
		SAOUTLM AS SALARYTOTACDM,
		SAOUTLW AS SALARYTOTACDF
	FROM `ipeds_2024_db`.`SAL2022_IS`
	WHERE `ARANK` = 7
),
ipedsHD2022TrimmedEIN AS (
	SELECT 
		UNITID,
		INSTNM,
		STABBR,
		TRIM(EIN) as EIN,
		OPEID
	FROM `ipeds_2024_db`.`HD2022`
),
ipedsIC2022AssociateAndAbove AS (
	SELECT 
		UNITID,
		CNTLAFFI,
		STUSRV8
	FROM `ipeds_2024_db`.`IC2022`
	WHERE (
			LEVEL3 = 1 OR
			LEVEL4 = 1 OR
			LEVEL5 = 1 OR
			LEVEL6 = 1 OR
			LEVEL7 = 1 OR
			LEVEL8 = 1 OR
			LEVEL17 = 1 OR
			LEVEL18 = 1 OR
			LEVEL19 = 1
	) AND `CNTLAFFI` IN (1, 3, 4)
),
ipedsEF2022ByLevelOfStudent AS (
	SELECT 
		UNITID,
		EFTOTAL AS ENROLLTOT
	FROM `ipeds_2024_db`.`EF2022`
	WHERE `EFLEVEL` IN (10)
)
SELECT
	C2022B.UNITID AS UNITID,
	HD2022F.INSTNM AS INSTNM,
	HD2022F.STABBR AS STATE,
	HD2022F.EIN AS EIN,
	HD2022F.OPEID AS OPEID,
	C2022B.CSTOTLT AS DEGREETOT,
	EF2022F.ENROLLTOT AS ENROLLTOT,
	IC2022F.CNTLAFFI AS INSTFUNDINGTYPE,
	IC2022F.STUSRV8 AS HASDAYCARE,
	SAL2022ISRANK.ACDPOPM AS ACDPOPM,
	SAL2022ISRANK.ACDPOPF AS ACDPOPF,
	SAL2022ISRANK.SALARYTOTACDM AS SALARYTOTACDM,
	SAL2022ISRANK.SALARYTOTACDF AS SALARYTOTACDF,
	S2022ISRank.ACDTOTMEN AS ACDTOTMEN,
	S2022ISRank.ACDTOTWOMEN AS ACDTOTWOMEN,
	S2022ISRank.ACDTOTWHIT AS ACDTOTWHIT,
	S2022ISRank.ACDTOTBLAK AS ACDTOTBLAK,
	S2022ISRank.ACDTOTASIA AS ACDTOTASIA,
	S2022ISRank.ACDTOTHISP AS ACDTOTHISP,
	S2022ISRank.ACDTOTNHPI AS ACDTOTNHPI,
	S2022ISRank.ACDTOTNAMC AS ACDTOTNAMC,
	S2022ISRank.ACDTOTNRES AS ACDTOTNRES,
	S2022ISRank.ACDTOTTWOP AS ACDTOTTWOP,
	S2022ISRank.ACDTOTUNKN AS ACDTOTUNKN,
	S2022ISRank.PROFMEN AS PROFMEN,
	S2022ISRank.PROFWOMEN AS PROFWOMEN,
	S2022ISRank.PROFWHIT AS PROFWHIT,
	S2022ISRank.PROFBLAK AS PROFBLAK,
	S2022ISRank.PROFASIA AS PROFASIA,
	S2022ISRank.PROFHISP AS PROFHISP,
	S2022ISRank.PROFNHPI AS PROFNHPI,
	S2022ISRank.PROFNAMC AS PROFNAMC,
	S2022ISRank.PROFNRES AS PROFNRES,
	S2022ISRank.PROFTWOP AS PROFTWOP,
	S2022ISRank.PROFUNKN AS PROFUNKN,
	S2022ISRank.ASSOCIATEPROFMEN AS ASSOCIATEPROFMEN,
	S2022ISRank.ASSOCIATEPROFWOMEN AS ASSOCIATEPROFWOMEN,
	S2022ISRank.ASSOCIATEPROFWHIT AS ASSOCIATEPROFWHIT,
	S2022ISRank.ASSOCIATEPROFBLAK AS ASSOCIATEPROFBLAK,
	S2022ISRank.ASSOCIATEPROFASIA AS ASSOCIATEPROFASIA,
	S2022ISRank.ASSOCIATEPROFHISP AS ASSOCIATEPROFHISP,
	S2022ISRank.ASSOCIATEPROFNHPI AS ASSOCIATEPROFNHPI,
	S2022ISRank.ASSOCIATEPROFNAMC AS ASSOCIATEPROFNAMC,
	S2022ISRank.ASSOCIATEPROFNRES AS ASSOCIATEPROFNRES,
	S2022ISRank.ASSOCIATEPROFTWOP AS ASSOCIATEPROFTWOP,
	S2022ISRank.ASSOCIATEPROFUNKN AS ASSOCIATEPROFUNKN,
	S2022ISRank.ASSISTANTPROFMEN AS ASSISTANTPROFMEN,
	S2022ISRank.ASSISTANTPROFWOMEN AS ASSISTANTPROFWOMEN,
	S2022ISRank.ASSISTANTPROFWHIT AS ASSISTANTPROFWHIT,
	S2022ISRank.ASSISTANTPROFBLAK AS ASSISTANTPROFBLAK,
	S2022ISRank.ASSISTANTPROFASIA AS ASSISTANTPROFASIA,
	S2022ISRank.ASSISTANTPROFHISP AS ASSISTANTPROFHISP,
	S2022ISRank.ASSISTANTPROFNHPI AS ASSISTANTPROFNHPI,
	S2022ISRank.ASSISTANTPROFNAMC AS ASSISTANTPROFNAMC,
	S2022ISRank.ASSISTANTPROFNRES AS ASSISTANTPROFNRES,
	S2022ISRank.ASSISTANTPROFTWOP AS ASSISTANTPROFTWOP,
	S2022ISRank.ASSISTANTPROFUNKN AS ASSISTANTPROFUNKN,
	S2022ISRank.INSTRUCTORMEN AS INSTRUCTORMEN,
	S2022ISRank.INSTRUCTORWOMEN AS INSTRUCTORWOMEN,
	S2022ISRank.INSTRUCTORWHIT AS INSTRUCTORWHIT,
	S2022ISRank.INSTRUCTORBLAK AS INSTRUCTORBLAK,
	S2022ISRank.INSTRUCTORASIA AS INSTRUCTORASIA,
	S2022ISRank.INSTRUCTORHISP AS INSTRUCTORHISP,
	S2022ISRank.INSTRUCTORNHPI AS INSTRUCTORNHPI,
	S2022ISRank.INSTRUCTORNAMC AS INSTRUCTORNAMC,
	S2022ISRank.INSTRUCTORNRES AS INSTRUCTORNRES,
	S2022ISRank.INSTRUCTORTWOP AS INSTRUCTORTWOP,
	S2022ISRank.INSTRUCTORUNKN AS INSTRUCTORUNKN,
	S2022ISRank.LECTURERMEN AS LECTURERMEN,
	S2022ISRank.LECTURERWOMEN AS LECTURERWOMEN,
	S2022ISRank.LECTURERWHIT AS LECTURERWHIT,
	S2022ISRank.LECTURERBLAK AS LECTURERBLAK,
	S2022ISRank.LECTURERASIA AS LECTURERASIA,
	S2022ISRank.LECTURERHISP AS LECTURERHISP,
	S2022ISRank.LECTURERNHPI AS LECTURERNHPI,
	S2022ISRank.LECTURERNAMC AS LECTURERNAMC,
	S2022ISRank.LECTURERNRES AS LECTURERNRES,
	S2022ISRank.LECTURERTWOP AS LECTURERTWOP,
	S2022ISRank.LECTURERUNKN AS LECTURERUNKN,
	S2022OCOCCUPATION.NONACDMEN AS NONACDMEN,
	S2022OCOCCUPATION.NONACDWOMEN AS NONACDWOMEN,
	S2022OCOCCUPATION.NONACDWHIT AS NONACDWHIT,
	S2022OCOCCUPATION.NONACDBLAK AS NONACDBLAK,
	S2022OCOCCUPATION.NONACDASIA AS NONACDASIA,
	S2022OCOCCUPATION.NONACDHISP AS NONACDHISP,
	S2022OCOCCUPATION.NONACDNHPI AS NONACDNHPI,
	S2022OCOCCUPATION.NONACDNAMC AS NONACDNAMC,
	S2022OCOCCUPATION.NONACDNRES AS NONACDNRES,
	S2022OCOCCUPATION.NONACDTWOP AS NONACDTWOP,
	S2022OCOCCUPATION.NONACDUNKN AS NONACDUNKN,  
	cssY22.SchoolPopulation as CSSPOPULATION2022,
	cssY22.Y2022HATECRIME AS Y2022HATECRIME,
	cssY22.Y2022HATECRIME * 1000 / NULLIF(cssY22.SchoolPopulation, 0) AS Y2022HATECRIME1K,
	cssY22.Y2022VAWA AS Y2022VAWA,
	cssY22.Y2022VAWA * 1000 / NULLIF(cssY22.SchoolPopulation, 0) AS Y2022VAWA1K, 
	cssY23.SchoolPopulation as CSSPOPULATION2023,
	cssY23.Y2023HATECRIME AS Y2023HATECRIME,
	cssY23.Y2023HATECRIME * 1000 / NULLIF(cssY23.SchoolPopulation, 0) AS Y2023HATECRIME1K,
	cssY23.Y2023VAWA AS Y2023VAWA,
	cssY23.Y2023VAWA * 1000 / NULLIF(cssY23.SchoolPopulation, 0) AS Y2023VAWA1K, 
	cssY24.SchoolPopulation as CSSPOPULATION2024,
	cssY24.Y2024HATECRIME AS Y2024HATECRIME,
	cssY24.Y2024HATECRIME * 1000 / NULLIF(cssY24.SchoolPopulation, 0) AS Y2024HATECRIME1K,
	cssY24.Y2024VAWA AS Y2024VAWA,
	cssY24.Y2024VAWA * 1000 / NULLIF(cssY23.SchoolPopulation, 0) AS Y2024VAWA1K
FROM `ipeds_2024_db`.`C2022_B` C2022B
INNER JOIN `ipedsEF2022ByLevelOfStudent` EF2022F ON C2022B.UNITID = EF2022F.UNITID
INNER JOIN `ipedsIC2022AssociateAndAbove` IC2022F ON C2022B.UNITID = IC2022F.UNITID
INNER JOIN `ipedsHD2022TrimmedEIN` HD2022F ON C2022B.UNITID = HD2022F.UNITID
INNER JOIN `ipedsSAL2022ISBYAcademicRank` SAL2022ISRANK ON C2022B.UNITID = SAL2022ISRANK.UNITID
INNER JOIN `ipedsS2022OCByOccupation` S2022OCOCCUPATION ON C2022B.UNITID = S2022OCOCCUPATION.UNITID
INNER JOIN `ipedsS2022ISByAcademicRank` S2022ISRank ON C2022B.UNITID = S2022ISRank.UNITID
INNER JOIN cssY23 ON TRIM(HD2022F.OPEID) REGEXP '^[0-9]+$' AND TRIM(cssY23.OPEID) REGEXP '^[0-9]+$' AND CAST(TRIM(HD2022F.OPEID) AS UNSIGNED) = CAST(TRIM(cssY23.OPEID) AS UNSIGNED)
INNER JOIN cssY22 ON TRIM(cssY22.OPEID) REGEXP '^[0-9]+$' AND CAST(TRIM(cssY23.OPEID) AS UNSIGNED) = CAST(TRIM(cssY22.OPEID) AS UNSIGNED)
INNER JOIN cssY24 ON TRIM(cssY24.OPEID) REGEXP '^[0-9]+$' AND CAST(TRIM(cssY23.OPEID) AS UNSIGNED) = CAST(TRIM(cssY24.OPEID) AS UNSIGNED)
WHERE C2022B.CSTOTLT >= 50 AND EF2022F.ENROLLTOT >= 200
ORDER BY C2022B.`UNITID` ASC;
