DROP TABLE IF EXISTS `merged_ipeds_css_irs`.`GenderFair2024`;

CREATE TABLE `merged_ipeds_css_irs`.`GenderFair2024` AS
WITH cssYearly AS (
	SELECT 
		OPEID,
		MAX(cssh.Total) AS SchoolPopulation,
		SUM(
			cssh.MURD22 +
			cssh.RAPE22 +
			cssh.FOND22 +
			cssh.INCE22 +
			cssh.STAT22 +
			cssh.ROBBE22 +
			cssh.AGG_A22 +
			cssh.BURGLA22 +
			cssh.VEHIC22 +
			cssh.ARSON22 +
			cssh.SIM_A22 +
			cssh.LAR_T22 +
			cssh.INTIM22 +
			cssh.VANDAL22
		) AS YEARLYHATECRIME,
		SUM(
			cssv.DOMEST22 +
			cssv.DATING22 +
			cssv.STALK22
		) AS YEARLYVAWA
	FROM `css`.`css_hate` cssh
	JOIN `css`.`css_vawa` cssv
	USING (OPEID)
	GROUP BY OPEID
),
ipedsS2022ISByAcademicRank AS (
	SELECT
		UNITID,
		SUM(CASE WHEN SISCAT = 1 THEN HRTOTLM ELSE 0 END) AS ACDTOTMEN,
		SUM(CASE WHEN SISCAT = 1 THEN HRTOTLW ELSE 0 END) AS ACDTOTWOMEN,
		SUM(CASE WHEN SISCAT = 1 THEN HRWHITT ELSE 0 END) AS ACDTOTWHIT,
		SUM(CASE WHEN SISCAT = 1 THEN HRBKAAT ELSE 0 END) AS ACDTOTBLAK,
		SUM(CASE WHEN SISCAT = 1 THEN HRASIAT ELSE 0 END) AS ACDTOTASIA,
		SUM(CASE WHEN SISCAT = 1 THEN HRHISPT ELSE 0 END) AS ACDTOTHISP,
		SUM(CASE WHEN SISCAT = 1 THEN HRNHPIT ELSE 0 END) AS ACDTOTNHPI,
		SUM(CASE WHEN SISCAT = 1 THEN HRAIANT ELSE 0 END) AS ACDTOTNAMC,
		SUM(CASE WHEN SISCAT = 1 THEN HRNRALT ELSE 0 END) AS ACDTOTNRES,
		SUM(CASE WHEN SISCAT = 1 THEN HR2MORT ELSE 0 END) AS ACDTOTTWOP,
		SUM(CASE WHEN SISCAT = 1 THEN HRUNKNT ELSE 0 END) AS ACDTOTUNKN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLM ELSE 0 END) AS PROFMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS PROFWOMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRWHITT ELSE 0 END) AS PROFWHIT,
		SUM(CASE WHEN SISCAT = 101 THEN HRBKAAT ELSE 0 END) AS PROFBLAK,
		SUM(CASE WHEN SISCAT = 101 THEN HRASIAT ELSE 0 END) AS PROFASIA,
		SUM(CASE WHEN SISCAT = 101 THEN HRHISPT ELSE 0 END) AS PROFHISP,
		SUM(CASE WHEN SISCAT = 101 THEN HRNHPIT ELSE 0 END) AS PROFNHPI,
		SUM(CASE WHEN SISCAT = 101 THEN HRAIANT ELSE 0 END) AS PROFNAMC,
		SUM(CASE WHEN SISCAT = 101 THEN HRNRALT ELSE 0 END) AS PROFNRES,
		SUM(CASE WHEN SISCAT = 101 THEN HR2MORT ELSE 0 END) AS PROFTWOP,
		SUM(CASE WHEN SISCAT = 101 THEN HRUNKNT ELSE 0 END) AS PROFUNKN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLM ELSE 0 END) AS ASSOCIATEPROFMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS ASSOCIATEPROFWOMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRWHITT ELSE 0 END) AS ASSOCIATEPROFWHIT,
		SUM(CASE WHEN SISCAT = 102 THEN HRBKAAT ELSE 0 END) AS ASSOCIATEPROFBLAK,
		SUM(CASE WHEN SISCAT = 102 THEN HRASIAT ELSE 0 END) AS ASSOCIATEPROFASIA,
		SUM(CASE WHEN SISCAT = 102 THEN HRHISPT ELSE 0 END) AS ASSOCIATEPROFHISP,
		SUM(CASE WHEN SISCAT = 102 THEN HRNHPIT ELSE 0 END) AS ASSOCIATEPROFNHPI,
		SUM(CASE WHEN SISCAT = 102 THEN HRAIANT ELSE 0 END) AS ASSOCIATEPROFNAMC,
		SUM(CASE WHEN SISCAT = 102 THEN HRNRALT ELSE 0 END) AS ASSOCIATEPROFNRES,
		SUM(CASE WHEN SISCAT = 102 THEN HR2MORT ELSE 0 END) AS ASSOCIATEPROFTWOP,
		SUM(CASE WHEN SISCAT = 102 THEN HRUNKNT ELSE 0 END) AS ASSOCIATEPROFUNKN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLM ELSE 0 END) AS ASSISTANTPROFMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLW ELSE 0 END) AS ASSISTANTPROFWOMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRWHITT ELSE 0 END) AS ASSISTANTPROFWHIT,
		SUM(CASE WHEN SISCAT = 103 THEN HRBKAAT ELSE 0 END) AS ASSISTANTPROFBLAK,
		SUM(CASE WHEN SISCAT = 103 THEN HRASIAT ELSE 0 END) AS ASSISTANTPROFASIA,
		SUM(CASE WHEN SISCAT = 103 THEN HRHISPT ELSE 0 END) AS ASSISTANTPROFHISP,
		SUM(CASE WHEN SISCAT = 103 THEN HRNHPIT ELSE 0 END) AS ASSISTANTPROFNHPI,
		SUM(CASE WHEN SISCAT = 103 THEN HRAIANT ELSE 0 END) AS ASSISTANTPROFNAMC,
		SUM(CASE WHEN SISCAT = 103 THEN HRNRALT ELSE 0 END) AS ASSISTANTPROFNRES,
		SUM(CASE WHEN SISCAT = 103 THEN HR2MORT ELSE 0 END) AS ASSISTANTPROFTWOP,
		SUM(CASE WHEN SISCAT = 103 THEN HRUNKNT ELSE 0 END) AS ASSISTANTPROFUNKN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLM ELSE 0 END) AS INSTRUCTORMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLW ELSE 0 END) AS INSTRUCTORWOMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRWHITT ELSE 0 END) AS INSTRUCTORWHIT,
		SUM(CASE WHEN SISCAT = 104 THEN HRBKAAT ELSE 0 END) AS INSTRUCTORBLAK,
		SUM(CASE WHEN SISCAT = 104 THEN HRASIAT ELSE 0 END) AS INSTRUCTORASIA,
		SUM(CASE WHEN SISCAT = 104 THEN HRHISPT ELSE 0 END) AS INSTRUCTORHISP,
		SUM(CASE WHEN SISCAT = 104 THEN HRNHPIT ELSE 0 END) AS INSTRUCTORNHPI,
		SUM(CASE WHEN SISCAT = 104 THEN HRAIANT ELSE 0 END) AS INSTRUCTORNAMC,
		SUM(CASE WHEN SISCAT = 104 THEN HRNRALT ELSE 0 END) AS INSTRUCTORNRES,
		SUM(CASE WHEN SISCAT = 104 THEN HR2MORT ELSE 0 END) AS INSTRUCTORTWOP,
		SUM(CASE WHEN SISCAT = 104 THEN HRUNKNT ELSE 0 END) AS INSTRUCTORUNKN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLM ELSE 0 END) AS LECTURERMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLW ELSE 0 END) AS LECTURERWOMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRWHITT ELSE 0 END) AS LECTURERWHIT,
		SUM(CASE WHEN SISCAT = 105 THEN HRBKAAT ELSE 0 END) AS LECTURERBLAK,
		SUM(CASE WHEN SISCAT = 105 THEN HRASIAT ELSE 0 END) AS LECTURERASIA,
		SUM(CASE WHEN SISCAT = 105 THEN HRHISPT ELSE 0 END) AS LECTURERHISP,
		SUM(CASE WHEN SISCAT = 105 THEN HRNHPIT ELSE 0 END) AS LECTURERNHPI,
		SUM(CASE WHEN SISCAT = 105 THEN HRAIANT ELSE 0 END) AS LECTURERNAMC,
		SUM(CASE WHEN SISCAT = 105 THEN HRNRALT ELSE 0 END) AS LECTURERNRES,
		SUM(CASE WHEN SISCAT = 105 THEN HR2MORT ELSE 0 END) AS LECTURERTWOP,
		SUM(CASE WHEN SISCAT = 105 THEN HRUNKNT ELSE 0 END) AS LECTURERUNKN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLM ELSE 0 END) AS NORANKMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLW ELSE 0 END) AS NORANKWOMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRWHITT ELSE 0 END) AS NORANKWHIT,
		SUM(CASE WHEN SISCAT = 106 THEN HRBKAAT ELSE 0 END) AS NORANKBLAK,
		SUM(CASE WHEN SISCAT = 106 THEN HRASIAT ELSE 0 END) AS NORANKASIA,
		SUM(CASE WHEN SISCAT = 106 THEN HRHISPT ELSE 0 END) AS NORANKHISP,
		SUM(CASE WHEN SISCAT = 106 THEN HRNHPIT ELSE 0 END) AS NORANKNHPI,
		SUM(CASE WHEN SISCAT = 106 THEN HRAIANT ELSE 0 END) AS NORANKNAMC,
		SUM(CASE WHEN SISCAT = 106 THEN HRNRALT ELSE 0 END) AS NORANKNRES,
		SUM(CASE WHEN SISCAT = 106 THEN HR2MORT ELSE 0 END) AS NORANKTWOP,
		SUM(CASE WHEN SISCAT = 106 THEN HRUNKNT ELSE 0 END) AS NORANKUNKN
	FROM `ipeds_2024_db`.`S2022_IS`
	GROUP BY `UNITID`
),
ipedsS2022OCByOccupation AS (
	SELECT 
		UNITID,
		SUM(HRTOTLM) AS NONACDMEN,
		SUM(HRTOTLW) AS NONACDWOMEN,
		SUM(HRWHITT) AS NONACDWHIT,
		SUM(HRBKAAT) AS NONACDBLAK,
		SUM(HRASIAT) AS NONACDASIA,
		SUM(HRHISPT) AS NONACDHISP,
		SUM(HRNHPIT) AS NONACDNHPI,
		SUM(HRAIANT) AS NONACDNAMC,
		SUM(HRNRALT) AS NONACDNRES,
		SUM(HR2MORT) AS NONACDTWOP,
		SUM(HRUNKNT) AS NONACDUNKN
	FROM `ipeds_2024_db`.`S2022_OC`
	WHERE `OCCUPCAT` IN (230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390)
	GROUP BY UNITID
),
ipedsSAL2022ISBYAcademicRank AS (
	SELECT 
		UNITID,
		SAINSTM AS ACDPOPM,
		SAINSTW AS ACDPOPF,
		SAOUTLM AS SALARYTOTACDM,
		SAOUTLW AS SALARYTOTACDF
	FROM `ipeds_2024_db`.`SAL2022_IS`
	WHERE `ARANK` = 7
),
ipedsHD2022TrimmedEIN AS (
	SELECT 
		UNITID,
		INSTNM,
		STABBR,
		TRIM(EIN) as EIN,
		OPEID
	FROM `ipeds_2024_db`.`HD2022`
),
ipedsIC2022AssociateAndAbove AS (
	SELECT *
	FROM `ipeds_2024_db`.`IC2022`
	WHERE (
			LEVEL3 = 1 OR
			LEVEL4 = 1 OR
			LEVEL5 = 1 OR
			LEVEL6 = 1 OR
			LEVEL7 = 1 OR
			LEVEL8 = 1 OR
			LEVEL17 = 1 OR
			LEVEL18 = 1 OR
			LEVEL19 = 1
	) AND `CNTLAFFI` IN (1, 3, 4)
),
ipedsEF2022ByLevelOfStudent AS (
	SELECT 
		UNITID,
		EFTOTAL AS ENROLLTOT
	FROM `ipeds_2024_db`.`EF2022`
	WHERE `EFLEVEL` IN (10)
),
irs990ByLatestDate AS (
	SELECT * FROM (
		SELECT *,
			ROW_NUMBER() OVER (
				PARTITION BY `EIN` 
				ORDER BY `YEAR` DESC, `IRS_MONTH` DESC
			) AS rn
		FROM `irs990`.`Organizations`
	) AS ranked
	WHERE rn = 1
)
SELECT
	C2022B.UNITID AS UNITID,
	HD2022.INSTNM AS INSTNM,
	HD2022.STABBR AS STATE,
	HD2022.EIN AS EIN,
	HD2022.OPEID AS OPEID,
	C2022B.CSTOTLT AS DEGREETOT,
	EF2022F.ENROLLTOT AS ENROLLTOT,
	IC2022F.CNTLAFFI AS INSTFUNDINGTYPE,
	IC2022F.STUSRV8 AS HASDAYCARE,
	SAL2022ISRANK.ACDPOPM AS ACDPOPM,
	SAL2022ISRANK.ACDPOPF AS ACDPOPF,
	SAL2022ISRANK.SALARYTOTACDM AS SALARYTOTACDM,
	SAL2022ISRANK.SALARYTOTACDF AS SALARYTOTACDF,
	S2022ISRank.ACDTOTMEN AS ACDTOTMEN,
	S2022ISRank.ACDTOTWOMEN AS ACDTOTWOMEN,
	S2022ISRank.ACDTOTWHIT AS ACDTOTWHIT,
	S2022ISRank.ACDTOTBLAK AS ACDTOTBLAK,
	S2022ISRank.ACDTOTASIA AS ACDTOTASIA,
	S2022ISRank.ACDTOTHISP AS ACDTOTHISP,
	S2022ISRank.ACDTOTNHPI AS ACDTOTNHPI,
	S2022ISRank.ACDTOTNAMC AS ACDTOTNAMC,
	S2022ISRank.ACDTOTNRES AS ACDTOTNRES,
	S2022ISRank.ACDTOTTWOP AS ACDTOTTWOP,
	S2022ISRank.ACDTOTUNKN AS ACDTOTUNKN,
	S2022ISRank.PROFMEN AS PROFMEN,
	S2022ISRank.PROFWOMEN AS PROFWOMEN,
	S2022ISRank.PROFWHIT AS PROFWHIT,
	S2022ISRank.PROFBLAK AS PROFBLAK,
	S2022ISRank.PROFASIA AS PROFASIA,
	S2022ISRank.PROFHISP AS PROFHISP,
	S2022ISRank.PROFNHPI AS PROFNHPI,
	S2022ISRank.PROFNAMC AS PROFNAMC,
	S2022ISRank.PROFNRES AS PROFNRES,
	S2022ISRank.PROFTWOP AS PROFTWOP,
	S2022ISRank.PROFUNKN AS PROFUNKN,
	S2022ISRank.ASSOCIATEPROFMEN AS ASSOCIATEPROFMEN,
	S2022ISRank.ASSOCIATEPROFWOMEN AS ASSOCIATEPROFWOMEN,
	S2022ISRank.ASSOCIATEPROFWHIT AS ASSOCIATEPROFWHIT,
	S2022ISRank.ASSOCIATEPROFBLAK AS ASSOCIATEPROFBLAK,
	S2022ISRank.ASSOCIATEPROFASIA AS ASSOCIATEPROFASIA,
	S2022ISRank.ASSOCIATEPROFHISP AS ASSOCIATEPROFHISP,
	S2022ISRank.ASSOCIATEPROFNHPI AS ASSOCIATEPROFNHPI,
	S2022ISRank.ASSOCIATEPROFNAMC AS ASSOCIATEPROFNAMC,
	S2022ISRank.ASSOCIATEPROFNRES AS ASSOCIATEPROFNRES,
	S2022ISRank.ASSOCIATEPROFTWOP AS ASSOCIATEPROFTWOP,
	S2022ISRank.ASSOCIATEPROFUNKN AS ASSOCIATEPROFUNKN,
	S2022ISRank.ASSISTANTPROFMEN AS ASSISTANTPROFMEN,
	S2022ISRank.ASSISTANTPROFWOMEN AS ASSISTANTPROFWOMEN,
	S2022ISRank.ASSISTANTPROFWHIT AS ASSISTANTPROFWHIT,
	S2022ISRank.ASSISTANTPROFBLAK AS ASSISTANTPROFBLAK,
	S2022ISRank.ASSISTANTPROFASIA AS ASSISTANTPROFASIA,
	S2022ISRank.ASSISTANTPROFHISP AS ASSISTANTPROFHISP,
	S2022ISRank.ASSISTANTPROFNHPI AS ASSISTANTPROFNHPI,
	S2022ISRank.ASSISTANTPROFNAMC AS ASSISTANTPROFNAMC,
	S2022ISRank.ASSISTANTPROFNRES AS ASSISTANTPROFNRES,
	S2022ISRank.ASSISTANTPROFTWOP AS ASSISTANTPROFTWOP,
	S2022ISRank.ASSISTANTPROFUNKN AS ASSISTANTPROFUNKN,
	S2022ISRank.INSTRUCTORMEN AS INSTRUCTORMEN,
	S2022ISRank.INSTRUCTORWOMEN AS INSTRUCTORWOMEN,
	S2022ISRank.INSTRUCTORWHIT AS INSTRUCTORWHIT,
	S2022ISRank.INSTRUCTORBLAK AS INSTRUCTORBLAK,
	S2022ISRank.INSTRUCTORASIA AS INSTRUCTORASIA,
	S2022ISRank.INSTRUCTORHISP AS INSTRUCTORHISP,
	S2022ISRank.INSTRUCTORNHPI AS INSTRUCTORNHPI,
	S2022ISRank.INSTRUCTORNAMC AS INSTRUCTORNAMC,
	S2022ISRank.INSTRUCTORNRES AS INSTRUCTORNRES,
	S2022ISRank.INSTRUCTORTWOP AS INSTRUCTORTWOP,
	S2022ISRank.INSTRUCTORUNKN AS INSTRUCTORUNKN,
	S2022ISRank.LECTURERMEN AS LECTURERMEN,
	S2022ISRank.LECTURERWOMEN AS LECTURERWOMEN,
	S2022ISRank.LECTURERWHIT AS LECTURERWHIT,
	S2022ISRank.LECTURERBLAK AS LECTURERBLAK,
	S2022ISRank.LECTURERASIA AS LECTURERASIA,
	S2022ISRank.LECTURERHISP AS LECTURERHISP,
	S2022ISRank.LECTURERNHPI AS LECTURERNHPI,
	S2022ISRank.LECTURERNAMC AS LECTURERNAMC,
	S2022ISRank.LECTURERNRES AS LECTURERNRES,
	S2022ISRank.LECTURERTWOP AS LECTURERTWOP,
	S2022ISRank.LECTURERUNKN AS LECTURERUNKN,
	S2022OCOCCUPATION.NONACDMEN AS NONACDMEN,
	S2022OCOCCUPATION.NONACDWOMEN AS NONACDWOMEN,
	S2022OCOCCUPATION.NONACDWHIT AS NONACDWHIT,
	S2022OCOCCUPATION.NONACDBLAK AS NONACDBLAK,
	S2022OCOCCUPATION.NONACDASIA AS NONACDASIA,
	S2022OCOCCUPATION.NONACDHISP AS NONACDHISP,
	S2022OCOCCUPATION.NONACDNHPI AS NONACDNHPI,
	S2022OCOCCUPATION.NONACDNAMC AS NONACDNAMC,
	S2022OCOCCUPATION.NONACDNRES AS NONACDNRES,
	S2022OCOCCUPATION.NONACDTWOP AS NONACDTWOP,
	S2022OCOCCUPATION.NONACDUNKN AS NONACDUNKN,
    css.SchoolPopulation as CSSPOPULATION,
	css.YEARLYHATECRIME AS YEARLYHATECRIME,
	css.YEARLYHATECRIME * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYHATECRIME1K,
	css.YEARLYVAWA AS YEARLYVAWA,
	css.YEARLYVAWA * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYVAWA1K,
	irs.PERCENTAGE_WOMEN_TRUSTEES AS PERCENTAGE_WOMEN_TRUSTEES,
	irs.PERCENTAGE_WOMEN_KEY_EMPLOYEES AS PERCENTAGE_WOMEN_KEY_EMPLOYEES,
	irs.WHISTLEBLOWER_POLICY AS WHISTLEBLOWER_POLICY,
	irs.CEO_REVIEWED_COMPENSATION AS CEO_REVIEWED_COMPENSATION,
	irs.OTHER_REVIEWED_COMPENSATION AS OTHER_REVIEWED_COMPENSATION,
	irs.MALE_TO_FEMALE_PAY_RATIO AS MALE_TO_FEMALE_PAY_RATIO,
	irs.PRESIDENT_TO_AVERAGE_PAY_RATIO AS PRESIDENT_TO_AVERAGE_PAY_RATIO
FROM `ipeds_2024_db`.`C2022_B` C2022B
INNER JOIN `ipedsEF2022ByLevelOfStudent` EF2022F ON C2022B.UNITID = EF2022F.UNITID
INNER JOIN `ipedsIC2022AssociateAndAbove` IC2022F ON C2022B.UNITID = IC2022F.UNITID
INNER JOIN `ipedsHD2022TrimmedEIN` HD2022 ON C2022B.UNITID = HD2022.UNITID
INNER JOIN `ipedsSAL2022ISBYAcademicRank` SAL2022ISRANK ON C2022B.UNITID = SAL2022ISRANK.UNITID
INNER JOIN `ipedsS2022OCByOccupation` S2022OCOCCUPATION ON C2022B.UNITID = S2022OCOCCUPATION.UNITID
INNER JOIN `ipedsS2022ISByAcademicRank` S2022ISRank ON C2022B.UNITID = S2022ISRank.UNITID
INNER JOIN `cssYearly` css ON HD2022.OPEID = css.OPEID
LEFT JOIN `irs990ByLatestDate` irs ON HD2022.EIN = irs.EIN
WHERE C2022B.CSTOTLT >= 50 AND EF2022F.ENROLLTOT >= 200
ORDER BY C2022B.`UNITID` ASC;