
INSERT INTO `PublicFacingData`.`SchoolData` (
	UNITID,
	INSTNM, 
	STATE,
	EIN,
	OPEID,
	DEGREETOT,
	ENROLLTOT,
	INSTFUNDINGTYPE,
	HASDAYCARE,
	ACDPOPM,
	ACDPOPF,
	SALARYTOTACDM,
	SALARYTOTACDF,
	ACDTOTMEN,
	ACDTOTWOMEN, 
	ACDTOTWHIT,
	ACDTOTBLAK,
	ACDTOTASIA,
	ACDTOTHISP,
	ACDTOTNHPI,
	ACDTOTNAMC,
	ACDTOTNRES,
	ACDTOTTWOP,
	ACDTOTUNKN, 
	PROFMEN,
	PROFWOMEN, 
	PROFWHIT, 
	PROFBLAK, 
	PROFASIA, 
	PROFHISP, 
	PROFNHPI, 
	PROFNAMC, 
	PROFNRES, 
	PROFTWOP, 
	PROFUNKN, 
	ASSOCIATEPROFMEN, 
	ASSOCIATEPROFWOMEN, 
	ASSOCIATEPROFWHIT, 
	ASSOCIATEPROFBLAK, 
	ASSOCIATEPROFASIA, 
	ASSOCIATEPROFHISP, 
	ASSOCIATEPROFNHPI, 
	ASSOCIATEPROFNAMC, 
	ASSOCIATEPROFNRES, 
	ASSOCIATEPROFTWOP, 
	ASSOCIATEPROFUNKN, 
	ASSISTANTPROFMEN, 
	ASSISTANTPROFWOMEN, 
	ASSISTANTPROFWHIT, 
	ASSISTANTPROFBLAK, 
	ASSISTANTPROFASIA, 
	ASSISTANTPROFHISP, 
	ASSISTANTPROFNHPI, 
	ASSISTANTPROFNAMC, 
	ASSISTANTPROFNRES, 
	ASSISTANTPROFTWOP, 
	ASSISTANTPROFUNKN, 
	INSTRUCTORMEN, 
	INSTRUCTORWOMEN, 
	INSTRUCTORWHIT, 
	INSTRUCTORBLAK, 
	INSTRUCTORASIA, 
	INSTRUCTORHISP, 
	INSTRUCTORNHPI, 
	INSTRUCTORNAMC, 
	INSTRUCTORNRES, 
	INSTRUCTORTWOP, 
	INSTRUCTORUNKN, 
	LECTURERMEN, 
	LECTURERWOMEN, 
	LECTURERWHIT, 
	LECTURERBLAK, 
	LECTURERASIA, 
	LECTURERHISP, 
	LECTURERNHPI, 
	LECTURERNAMC, 
	LECTURERNRES, 
	LECTURERTWOP, 
	LECTURERUNKN, 
	NONACDMEN, 
	NONACDWOMEN, 
	NONACDWHIT, 
	NONACDBLAK, 
	NONACDASIA, 
	NONACDHISP, 
	NONACDNHPI, 
	NONACDNAMC, 
	NONACDNRES, 
	NONACDTWOP, 
	NONACDUNKN,
	CSSPOPULATION, 
	YEARLYHATECRIME, 
	YEARLYHATECRIME1K,
	YEARLYVAWA,
	YEARLYVAWA1K
)
WITH css AS (
	SELECT 
        cssh24.OPEID,
		MAX(cssh24.Total) AS SchoolPopulation,
		SUM(
			cssh24.MURD23 +
			cssh24.RAPE23 +
			cssh24.FOND23 +
			cssh24.INCE23 +
			cssh24.STAT23 +
			cssh24.ROBBE23 +
			cssh24.AGG_A23 +
			cssh24.BURGLA23 +
			cssh24.VEHIC23 +
			cssh24.ARSON23 +
			cssh24.SIM_A23 +
			cssh24.LAR_T23 +
			cssh24.INTIM23 +
			cssh24.VANDAL23
		) AS HATECRIME,
		SUM(
			cssv24.DOMEST23 +
			cssv24.DATING23 +
			cssv24.STALK23
		) AS VAWA
	FROM `css2024`.`css_hate` cssh24
	JOIN `css2024`.`css_vawa` cssv24
	USING (OPEID)
	GROUP BY OPEID
),
ipedsS2023ISByAcademicRank AS (
	SELECT
		UNITID,
		SUM(CASE WHEN SISCAT = 1 THEN HRTOTLM ELSE 0 END) AS ACDTOTMEN,
		SUM(CASE WHEN SISCAT = 1 THEN HRTOTLW ELSE 0 END) AS ACDTOTWOMEN,
		SUM(CASE WHEN SISCAT = 1 THEN HRWHITT ELSE 0 END) AS ACDTOTWHIT,
		SUM(CASE WHEN SISCAT = 1 THEN HRBKAAT ELSE 0 END) AS ACDTOTBLAK,
		SUM(CASE WHEN SISCAT = 1 THEN HRASIAT ELSE 0 END) AS ACDTOTASIA,
		SUM(CASE WHEN SISCAT = 1 THEN HRHISPT ELSE 0 END) AS ACDTOTHISP,
		SUM(CASE WHEN SISCAT = 1 THEN HRNHPIT ELSE 0 END) AS ACDTOTNHPI,
		SUM(CASE WHEN SISCAT = 1 THEN HRAIANT ELSE 0 END) AS ACDTOTNAMC,
		SUM(CASE WHEN SISCAT = 1 THEN HRNRALT ELSE 0 END) AS ACDTOTNRES,
		SUM(CASE WHEN SISCAT = 1 THEN HR2MORT ELSE 0 END) AS ACDTOTTWOP,
		SUM(CASE WHEN SISCAT = 1 THEN HRUNKNT ELSE 0 END) AS ACDTOTUNKN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLM ELSE 0 END) AS PROFMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS PROFWOMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRWHITT ELSE 0 END) AS PROFWHIT,
		SUM(CASE WHEN SISCAT = 101 THEN HRBKAAT ELSE 0 END) AS PROFBLAK,
		SUM(CASE WHEN SISCAT = 101 THEN HRASIAT ELSE 0 END) AS PROFASIA,
		SUM(CASE WHEN SISCAT = 101 THEN HRHISPT ELSE 0 END) AS PROFHISP,
		SUM(CASE WHEN SISCAT = 101 THEN HRNHPIT ELSE 0 END) AS PROFNHPI,
		SUM(CASE WHEN SISCAT = 101 THEN HRAIANT ELSE 0 END) AS PROFNAMC,
		SUM(CASE WHEN SISCAT = 101 THEN HRNRALT ELSE 0 END) AS PROFNRES,
		SUM(CASE WHEN SISCAT = 101 THEN HR2MORT ELSE 0 END) AS PROFTWOP,
		SUM(CASE WHEN SISCAT = 101 THEN HRUNKNT ELSE 0 END) AS PROFUNKN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLM ELSE 0 END) AS ASSOCIATEPROFMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS ASSOCIATEPROFWOMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRWHITT ELSE 0 END) AS ASSOCIATEPROFWHIT,
		SUM(CASE WHEN SISCAT = 102 THEN HRBKAAT ELSE 0 END) AS ASSOCIATEPROFBLAK,
		SUM(CASE WHEN SISCAT = 102 THEN HRASIAT ELSE 0 END) AS ASSOCIATEPROFASIA,
		SUM(CASE WHEN SISCAT = 102 THEN HRHISPT ELSE 0 END) AS ASSOCIATEPROFHISP,
		SUM(CASE WHEN SISCAT = 102 THEN HRNHPIT ELSE 0 END) AS ASSOCIATEPROFNHPI,
		SUM(CASE WHEN SISCAT = 102 THEN HRAIANT ELSE 0 END) AS ASSOCIATEPROFNAMC,
		SUM(CASE WHEN SISCAT = 102 THEN HRNRALT ELSE 0 END) AS ASSOCIATEPROFNRES,
		SUM(CASE WHEN SISCAT = 102 THEN HR2MORT ELSE 0 END) AS ASSOCIATEPROFTWOP,
		SUM(CASE WHEN SISCAT = 102 THEN HRUNKNT ELSE 0 END) AS ASSOCIATEPROFUNKN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLM ELSE 0 END) AS ASSISTANTPROFMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLW ELSE 0 END) AS ASSISTANTPROFWOMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRWHITT ELSE 0 END) AS ASSISTANTPROFWHIT,
		SUM(CASE WHEN SISCAT = 103 THEN HRBKAAT ELSE 0 END) AS ASSISTANTPROFBLAK,
		SUM(CASE WHEN SISCAT = 103 THEN HRASIAT ELSE 0 END) AS ASSISTANTPROFASIA,
		SUM(CASE WHEN SISCAT = 103 THEN HRHISPT ELSE 0 END) AS ASSISTANTPROFHISP,
		SUM(CASE WHEN SISCAT = 103 THEN HRNHPIT ELSE 0 END) AS ASSISTANTPROFNHPI,
		SUM(CASE WHEN SISCAT = 103 THEN HRAIANT ELSE 0 END) AS ASSISTANTPROFNAMC,
		SUM(CASE WHEN SISCAT = 103 THEN HRNRALT ELSE 0 END) AS ASSISTANTPROFNRES,
		SUM(CASE WHEN SISCAT = 103 THEN HR2MORT ELSE 0 END) AS ASSISTANTPROFTWOP,
		SUM(CASE WHEN SISCAT = 103 THEN HRUNKNT ELSE 0 END) AS ASSISTANTPROFUNKN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLM ELSE 0 END) AS INSTRUCTORMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLW ELSE 0 END) AS INSTRUCTORWOMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRWHITT ELSE 0 END) AS INSTRUCTORWHIT,
		SUM(CASE WHEN SISCAT = 104 THEN HRBKAAT ELSE 0 END) AS INSTRUCTORBLAK,
		SUM(CASE WHEN SISCAT = 104 THEN HRASIAT ELSE 0 END) AS INSTRUCTORASIA,
		SUM(CASE WHEN SISCAT = 104 THEN HRHISPT ELSE 0 END) AS INSTRUCTORHISP,
		SUM(CASE WHEN SISCAT = 104 THEN HRNHPIT ELSE 0 END) AS INSTRUCTORNHPI,
		SUM(CASE WHEN SISCAT = 104 THEN HRAIANT ELSE 0 END) AS INSTRUCTORNAMC,
		SUM(CASE WHEN SISCAT = 104 THEN HRNRALT ELSE 0 END) AS INSTRUCTORNRES,
		SUM(CASE WHEN SISCAT = 104 THEN HR2MORT ELSE 0 END) AS INSTRUCTORTWOP,
		SUM(CASE WHEN SISCAT = 104 THEN HRUNKNT ELSE 0 END) AS INSTRUCTORUNKN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLM ELSE 0 END) AS LECTURERMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLW ELSE 0 END) AS LECTURERWOMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRWHITT ELSE 0 END) AS LECTURERWHIT,
		SUM(CASE WHEN SISCAT = 105 THEN HRBKAAT ELSE 0 END) AS LECTURERBLAK,
		SUM(CASE WHEN SISCAT = 105 THEN HRASIAT ELSE 0 END) AS LECTURERASIA,
		SUM(CASE WHEN SISCAT = 105 THEN HRHISPT ELSE 0 END) AS LECTURERHISP,
		SUM(CASE WHEN SISCAT = 105 THEN HRNHPIT ELSE 0 END) AS LECTURERNHPI,
		SUM(CASE WHEN SISCAT = 105 THEN HRAIANT ELSE 0 END) AS LECTURERNAMC,
		SUM(CASE WHEN SISCAT = 105 THEN HRNRALT ELSE 0 END) AS LECTURERNRES,
		SUM(CASE WHEN SISCAT = 105 THEN HR2MORT ELSE 0 END) AS LECTURERTWOP,
		SUM(CASE WHEN SISCAT = 105 THEN HRUNKNT ELSE 0 END) AS LECTURERUNKN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLM ELSE 0 END) AS NORANKMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLW ELSE 0 END) AS NORANKWOMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRWHITT ELSE 0 END) AS NORANKWHIT,
		SUM(CASE WHEN SISCAT = 106 THEN HRBKAAT ELSE 0 END) AS NORANKBLAK,
		SUM(CASE WHEN SISCAT = 106 THEN HRASIAT ELSE 0 END) AS NORANKASIA,
		SUM(CASE WHEN SISCAT = 106 THEN HRHISPT ELSE 0 END) AS NORANKHISP,
		SUM(CASE WHEN SISCAT = 106 THEN HRNHPIT ELSE 0 END) AS NORANKNHPI,
		SUM(CASE WHEN SISCAT = 106 THEN HRAIANT ELSE 0 END) AS NORANKNAMC,
		SUM(CASE WHEN SISCAT = 106 THEN HRNRALT ELSE 0 END) AS NORANKNRES,
		SUM(CASE WHEN SISCAT = 106 THEN HR2MORT ELSE 0 END) AS NORANKTWOP,
		SUM(CASE WHEN SISCAT = 106 THEN HRUNKNT ELSE 0 END) AS NORANKUNKN
	FROM `ipeds2324provisional`.`S2023_IS`
	GROUP BY `UNITID`
),
ipedsS2023OCByOccupation AS (
	SELECT 
		UNITID,
		SUM(HRTOTLM) AS NONACDMEN,
		SUM(HRTOTLW) AS NONACDWOMEN,
		SUM(HRWHITT) AS NONACDWHIT,
		SUM(HRBKAAT) AS NONACDBLAK,
		SUM(HRASIAT) AS NONACDASIA,
		SUM(HRHISPT) AS NONACDHISP,
		SUM(HRNHPIT) AS NONACDNHPI,
		SUM(HRAIANT) AS NONACDNAMC,
		SUM(HRNRALT) AS NONACDNRES,
		SUM(HR2MORT) AS NONACDTWOP,
		SUM(HRUNKNT) AS NONACDUNKN
	FROM `ipeds2324provisional`.`S2023_OC`
	WHERE `OCCUPCAT` IN (230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390)
	GROUP BY UNITID
),
ipedsSAL2023ISBYAcademicRank AS (
	SELECT 
		UNITID,
		SAINSTM AS ACDPOPM,
		SAINSTW AS ACDPOPF,
		SAOUTLM AS SALARYTOTACDM,
		SAOUTLW AS SALARYTOTACDF
	FROM `ipeds2324provisional`.`SAL2023_IS`
	WHERE `ARANK` = 7
),
ipedsHD2023TrimmedEIN AS (
	SELECT 
		UNITID,
		INSTNM,
		STABBR,
		TRIM(EIN) as EIN,
		OPEID
	FROM `ipeds2324provisional`.`HD2023`
),
ipedsIC2023AssociateAndAbove AS (
	SELECT 
		UNITID,
		CNTLAFFI,
		STUSRV8
	FROM `ipeds2324provisional`.`IC2023`
	WHERE (
			LEVEL3 = 1 OR
			LEVEL4 = 1 OR
			LEVEL5 = 1 OR
			LEVEL6 = 1 OR
			LEVEL7 = 1 OR
			LEVEL8 = 1 OR
			LEVEL17 = 1 OR
			LEVEL18 = 1 OR
			LEVEL19 = 1
	) AND `CNTLAFFI` IN (1, 3, 4)
),
ipedsEF2023ByLevelOfStudent AS (
	SELECT 
		UNITID,
		EFTOTAL AS ENROLLTOT
	FROM `ipeds2324provisional`.`EF2023`
	WHERE `EFLEVEL` IN (10)
)
SELECT
	C2023B.UNITID AS UNITID,
	HD2023F.INSTNM AS INSTNM,
	HD2023F.STABBR AS STATE,
	HD2023F.EIN AS EIN,
	HD2023F.OPEID AS OPEID,
	C2023B.CSTOTLT AS DEGREETOT,
	EF2023F.ENROLLTOT AS ENROLLTOT,
	IC2023F.CNTLAFFI AS INSTFUNDINGTYPE,
	IC2023F.STUSRV8 AS HASDAYCARE,
	SAL2023ISRANK.ACDPOPM AS ACDPOPM,
	SAL2023ISRANK.ACDPOPF AS ACDPOPF,
	SAL2023ISRANK.SALARYTOTACDM AS SALARYTOTACDM,
	SAL2023ISRANK.SALARYTOTACDF AS SALARYTOTACDF,
	S2023ISRank.ACDTOTMEN AS ACDTOTMEN,
	S2023ISRank.ACDTOTWOMEN AS ACDTOTWOMEN,
	S2023ISRank.ACDTOTWHIT AS ACDTOTWHIT,
	S2023ISRank.ACDTOTBLAK AS ACDTOTBLAK,
	S2023ISRank.ACDTOTASIA AS ACDTOTASIA,
	S2023ISRank.ACDTOTHISP AS ACDTOTHISP,
	S2023ISRank.ACDTOTNHPI AS ACDTOTNHPI,
	S2023ISRank.ACDTOTNAMC AS ACDTOTNAMC,
	S2023ISRank.ACDTOTNRES AS ACDTOTNRES,
	S2023ISRank.ACDTOTTWOP AS ACDTOTTWOP,
	S2023ISRank.ACDTOTUNKN AS ACDTOTUNKN,
	S2023ISRank.PROFMEN AS PROFMEN,
	S2023ISRank.PROFWOMEN AS PROFWOMEN,
	S2023ISRank.PROFWHIT AS PROFWHIT,
	S2023ISRank.PROFBLAK AS PROFBLAK,
	S2023ISRank.PROFASIA AS PROFASIA,
	S2023ISRank.PROFHISP AS PROFHISP,
	S2023ISRank.PROFNHPI AS PROFNHPI,
	S2023ISRank.PROFNAMC AS PROFNAMC,
	S2023ISRank.PROFNRES AS PROFNRES,
	S2023ISRank.PROFTWOP AS PROFTWOP,
	S2023ISRank.PROFUNKN AS PROFUNKN,
	S2023ISRank.ASSOCIATEPROFMEN AS ASSOCIATEPROFMEN,
	S2023ISRank.ASSOCIATEPROFWOMEN AS ASSOCIATEPROFWOMEN,
	S2023ISRank.ASSOCIATEPROFWHIT AS ASSOCIATEPROFWHIT,
	S2023ISRank.ASSOCIATEPROFBLAK AS ASSOCIATEPROFBLAK,
	S2023ISRank.ASSOCIATEPROFASIA AS ASSOCIATEPROFASIA,
	S2023ISRank.ASSOCIATEPROFHISP AS ASSOCIATEPROFHISP,
	S2023ISRank.ASSOCIATEPROFNHPI AS ASSOCIATEPROFNHPI,
	S2023ISRank.ASSOCIATEPROFNAMC AS ASSOCIATEPROFNAMC,
	S2023ISRank.ASSOCIATEPROFNRES AS ASSOCIATEPROFNRES,
	S2023ISRank.ASSOCIATEPROFTWOP AS ASSOCIATEPROFTWOP,
	S2023ISRank.ASSOCIATEPROFUNKN AS ASSOCIATEPROFUNKN,
	S2023ISRank.ASSISTANTPROFMEN AS ASSISTANTPROFMEN,
	S2023ISRank.ASSISTANTPROFWOMEN AS ASSISTANTPROFWOMEN,
	S2023ISRank.ASSISTANTPROFWHIT AS ASSISTANTPROFWHIT,
	S2023ISRank.ASSISTANTPROFBLAK AS ASSISTANTPROFBLAK,
	S2023ISRank.ASSISTANTPROFASIA AS ASSISTANTPROFASIA,
	S2023ISRank.ASSISTANTPROFHISP AS ASSISTANTPROFHISP,
	S2023ISRank.ASSISTANTPROFNHPI AS ASSISTANTPROFNHPI,
	S2023ISRank.ASSISTANTPROFNAMC AS ASSISTANTPROFNAMC,
	S2023ISRank.ASSISTANTPROFNRES AS ASSISTANTPROFNRES,
	S2023ISRank.ASSISTANTPROFTWOP AS ASSISTANTPROFTWOP,
	S2023ISRank.ASSISTANTPROFUNKN AS ASSISTANTPROFUNKN,
	S2023ISRank.INSTRUCTORMEN AS INSTRUCTORMEN,
	S2023ISRank.INSTRUCTORWOMEN AS INSTRUCTORWOMEN,
	S2023ISRank.INSTRUCTORWHIT AS INSTRUCTORWHIT,
	S2023ISRank.INSTRUCTORBLAK AS INSTRUCTORBLAK,
	S2023ISRank.INSTRUCTORASIA AS INSTRUCTORASIA,
	S2023ISRank.INSTRUCTORHISP AS INSTRUCTORHISP,
	S2023ISRank.INSTRUCTORNHPI AS INSTRUCTORNHPI,
	S2023ISRank.INSTRUCTORNAMC AS INSTRUCTORNAMC,
	S2023ISRank.INSTRUCTORNRES AS INSTRUCTORNRES,
	S2023ISRank.INSTRUCTORTWOP AS INSTRUCTORTWOP,
	S2023ISRank.INSTRUCTORUNKN AS INSTRUCTORUNKN,
	S2023ISRank.LECTURERMEN AS LECTURERMEN,
	S2023ISRank.LECTURERWOMEN AS LECTURERWOMEN,
	S2023ISRank.LECTURERWHIT AS LECTURERWHIT,
	S2023ISRank.LECTURERBLAK AS LECTURERBLAK,
	S2023ISRank.LECTURERASIA AS LECTURERASIA,
	S2023ISRank.LECTURERHISP AS LECTURERHISP,
	S2023ISRank.LECTURERNHPI AS LECTURERNHPI,
	S2023ISRank.LECTURERNAMC AS LECTURERNAMC,
	S2023ISRank.LECTURERNRES AS LECTURERNRES,
	S2023ISRank.LECTURERTWOP AS LECTURERTWOP,
	S2023ISRank.LECTURERUNKN AS LECTURERUNKN,
	S2023OCOCCUPATION.NONACDMEN AS NONACDMEN,
	S2023OCOCCUPATION.NONACDWOMEN AS NONACDWOMEN,
	S2023OCOCCUPATION.NONACDWHIT AS NONACDWHIT,
	S2023OCOCCUPATION.NONACDBLAK AS NONACDBLAK,
	S2023OCOCCUPATION.NONACDASIA AS NONACDASIA,
	S2023OCOCCUPATION.NONACDHISP AS NONACDHISP,
	S2023OCOCCUPATION.NONACDNHPI AS NONACDNHPI,
	S2023OCOCCUPATION.NONACDNAMC AS NONACDNAMC,
	S2023OCOCCUPATION.NONACDNRES AS NONACDNRES,
	S2023OCOCCUPATION.NONACDTWOP AS NONACDTWOP,
	S2023OCOCCUPATION.NONACDUNKN AS NONACDUNKN,  
	css.SchoolPopulation as CSSPOPULATION,
	css.HATECRIME AS YEARLYHATECRIME,
	css.HATECRIME * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYHATECRIME1K,
	css.VAWA AS YEARLYVAWA,
	css.VAWA * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYVAWA1K
FROM `ipeds2324provisional`.`C2023_B` C2023B
INNER JOIN `ipedsEF2023ByLevelOfStudent` EF2023F ON C2023B.UNITID = EF2023F.UNITID
INNER JOIN `ipedsIC2023AssociateAndAbove` IC2023F ON C2023B.UNITID = IC2023F.UNITID
INNER JOIN `ipedsHD2023TrimmedEIN` HD2023F ON C2023B.UNITID = HD2023F.UNITID
INNER JOIN `ipedsSAL2023ISBYAcademicRank` SAL2023ISRANK ON C2023B.UNITID = SAL2023ISRANK.UNITID
INNER JOIN `ipedsS2023OCByOccupation` S2023OCOCCUPATION ON C2023B.UNITID = S2023OCOCCUPATION.UNITID
INNER JOIN `ipedsS2023ISByAcademicRank` S2023ISRank ON C2023B.UNITID = S2023ISRank.UNITID
INNER JOIN css ON TRIM(HD2023F.OPEID) REGEXP '^[0-9]+$' AND TRIM(css.OPEID) REGEXP '^[0-9]+$' AND CAST(TRIM(HD2023F.OPEID) AS UNSIGNED) = CAST(TRIM(css.OPEID) AS UNSIGNED)
WHERE C2023B.CSTOTLT >= 50 AND EF2023F.ENROLLTOT >= 200
ORDER BY C2023B.`UNITID` ASC;
