DROP TABLE IF EXISTS `merged_ipeds_css_irs`.`gf2024_final`;

CREATE TABLE `merged_ipeds_css_irs`.`gf2024_final` AS
WITH cssYearly AS (
	SELECT 
		OPEID,
		MIN(cssh.Total) AS SchoolPopulation,
		SUM(
			cssh.MURD20 +
			cssh.RAPE20 +
			cssh.FOND20 +
			cssh.INCE20 +
			cssh.STAT20 +
			cssh.ROBBE20 +
			cssh.AGG_A20 +
			cssh.BURGLA20 +
			cssh.VEHIC20 +
			cssh.ARSON20 +
			cssh.SIM_A20 +
			cssh.LAR_T20 +
			cssh.INTIM20 +
			cssh.VANDAL20 +
			cssh.MURD21 +
			cssh.RAPE21 +
			cssh.FOND21 +
			cssh.INCE21 +
			cssh.STAT21 +
			cssh.ROBBE21 +
			cssh.AGG_A21 +
			cssh.BURGLA21 +
			cssh.VEHIC21 +
			cssh.ARSON21 +
			cssh.SIM_A21 +
			cssh.LAR_T21 +
			cssh.INTIM21 +
			cssh.VANDAL21 +
			cssh.MURD22 +
			cssh.RAPE22 +
			cssh.FOND22 +
			cssh.INCE22 +
			cssh.STAT22 +
			cssh.ROBBE22 +
			cssh.AGG_A22 +
			cssh.BURGLA22 +
			cssh.VEHIC22 +
			cssh.ARSON22 +
			cssh.SIM_A22 +
			cssh.LAR_T22 +
			cssh.INTIM22 +
			cssh.VANDAL22
		) / 3 AS YEARLYHATECRIME,
		SUM(
			cssv.DOMEST20 +
			cssv.DATING20 +
			cssv.STALK20 +
			cssv.DOMEST21 +
			cssv.DATING21 +
			cssv.STALK21 +
			cssv.DOMEST22 +
			cssv.DATING22 +
			cssv.STALK22
		) / 3 AS YEARLYVAWA
	FROM `css`.`css_hate` cssh
	JOIN `css`.`css_vawa` cssv
	USING (OPEID)
	GROUP BY OPEID
),
ipeds_S2022_IS_temp AS (
	SELECT
		UNITID,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_101,
		SUM(CASE WHEN SISCAT = 101 THEN HRASIAW ELSE 0 END) AS HRASIAW_101,
		SUM(CASE WHEN SISCAT = 101 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_101,
		SUM(CASE WHEN SISCAT = 101 THEN HRHISPW ELSE 0 END) AS HRHISPW_101,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_102,
		SUM(CASE WHEN SISCAT = 102 THEN HRASIAW ELSE 0 END) AS HRASIAW_102,
		SUM(CASE WHEN SISCAT = 102 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_102,
		SUM(CASE WHEN SISCAT = 102 THEN HRHISPW ELSE 0 END) AS HRHISPW_102,
		SUM(CASE WHEN SISCAT = 200 THEN HRTOTLW ELSE 0 END) AS HRTOTLW_200,
		SUM(CASE WHEN SISCAT = 200 THEN HRASIAW ELSE 0 END) AS HRASIAW_200,
		SUM(CASE WHEN SISCAT = 200 THEN HRBKAAW ELSE 0 END) AS HRBKAAW_200,
		SUM(CASE WHEN SISCAT = 200 THEN HRHISPW ELSE 0 END) AS HRHISPW_200
	FROM `ipeds_2024_db`.`S2022_IS`
	WHERE `SISCAT` IN (101, 102, 200)
	GROUP BY `UNITID`
),
ipeds_S2022_OC_temp AS (
	SELECT 
		UNITID,
		SUM(HRTOTLT) AS HRTOTLT,
		SUM(HRTOTLM) AS HRTOTLM,
		SUM(HRTOTLW) AS HRTOTLW,
		SUM(HRASIAT) AS HRASIAT,
		SUM(HRASIAM) AS HRASIAM,
		SUM(HRASIAW) AS HRASIAW,
		SUM(HRBKAAT) AS HRBKAAT,
		SUM(HRBKAAM) AS HRBKAAM,
		SUM(HRBKAAW) AS HRBKAAW,
		SUM(HRHISPT) AS HRHISPT,
		SUM(HRHISPM) AS HRHISPM,
		SUM(HRHISPW) AS HRHISPW
	FROM `ipeds_2024_db`.`S2022_OC`
	WHERE `OCCUPCAT` IN (220, 230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 420, 490)
	GROUP BY UNITID
),
ipeds_SAL2022_IS_temp AS (
	SELECT *, 
		CASE 
			WHEN SAINSTM = 0 OR SAOUTLM = 0 THEN NULL
			ELSE SAOUTLM / SAINSTM 
		END AS AVGSALM,
		CASE 
			WHEN SAINSTW = 0 OR SAOUTLW = 0 THEN NULL
			ELSE SAOUTLW / SAINSTW 
		END AS AVGSALW
	FROM `ipeds_2024_db`.`SAL2022_IS`
	WHERE `ARANK` IN (7)
),
ipedsIC2022AssociateAndAbove AS (
	SELECT *
	FROM `ipeds_2024_db`.`IC2022`
	WHERE (
			LEVEL3 = 1 OR
			LEVEL4 = 1 OR
			LEVEL5 = 1 OR
			LEVEL6 = 1 OR
			LEVEL7 = 1 OR
			LEVEL8 = 1 OR
			LEVEL17 = 1 OR
			LEVEL18 = 1 OR
			LEVEL19 = 1
	) AND `CNTLAFFI` IN (1, 3, 4)
),
ipeds_EF2022_temp AS (
SELECT * 
FROM `ipeds_2024_db`.`EF2022`
WHERE `EFLEVEL` IN (10)),
irs990_temp AS (
SELECT *
FROM (
	SELECT *,
		ROW_NUMBER() OVER (
			PARTITION BY `EIN` 
			ORDER BY `YEAR` DESC, `IRS_MONTH` DESC
		) AS rn
	FROM `irs990`.`Organizations`
) AS ranked
WHERE rn = 1)
-- Selecting columns --
SELECT
	C2022B.UNITID AS UNITID,
	HD2022.INSTNM AS INSTNM,
	HD2022.STABBR AS STATE,
	HD2022.EIN AS EIN,
	HD2022.OPEID AS OPEID,
	C2022B.CSTOTLT AS DEGREETOT,
	b.EFTOTAL AS ENROLLTOT,
	IC2022F.CNTLAFFI AS INSTFUNDINGTYPE,
	IC2022F.STUSRV8 AS HASDAYCARE,
	e.SAINSTM AS ACADEMICPOPM,
	e.SAINSTW AS ACADEMICPOPF,
	e.SAOUTLM AS SALARYTOTM,
	e.SAOUTLW AS SALARYTOTF,  
	e.AVGSALM AS SALARYPPM,
	e.AVGSALW AS SALARYPPF,
	f.HRBKAAT AS NONACD_BLKPCT,
	f.HRHISPT AS NONACD_HSPPCT,
	f.HRASIAT AS NONACD_ASIAPCT,
	g.HRTOTLW_101 AS PROFWOMENPCT,
	g.HRTOTLW_102 AS ASSOCPROFWOMENPCT,
	g.HRTOTLW_200 AS TENUREWOMENPCT,
	g.HRBKAAW_101 AS BLACKPROFWOMENPCT,
	g.HRBKAAW_102 AS BLACKASSOCPROFWOMENPCT,
	g.HRBKAAW_200 AS BLACKTENUREWOMENPCT,
	g.HRHISPW_101 AS HISPANICPROFWOMENPCT,
	g.HRHISPW_102 AS HISPANICASSOCPROFWOMENPCT,
	g.HRHISPW_200 AS HISPANICTENUREWOMENPCT,
	g.HRASIAW_101 AS ASIANPROFWOMENPCT, 
	g.HRASIAW_102 AS ASIANASSOCPROFWOMENPCT,
	g.HRASIAW_200 AS ASIANTENUREWOMENPCT,
	css.YEARLYHATECRIME AS YEARLYHATECRIME,
	css.YEARLYHATECRIME * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYHATECRIME1K,
	css.YEARLYVAWA AS YEARLYVAWA,
	css.YEARLYVAWA * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYVAWA1K,
	j.PERCENTAGE_WOMEN_TRUSTEES AS PERCENTAGE_WOMEN_TRUSTEES,
	j.PERCENTAGE_WOMEN_KEY_EMPLOYEES AS PERCENTAGE_WOMEN_KEY_EMPLOYEES,
	j.WHISTLEBLOWER_POLICY AS WHISTLEBLOWER_POLICY,
	j.CEO_REVIEWED_COMPENSATION AS CEO_REVIEWED_COMPENSATION,
	j.OTHER_REVIEWED_COMPENSATION AS OTHER_REVIEWED_COMPENSATION,
	j.MALE_TO_FEMALE_PAY_RATIO AS MALE_TO_FEMALE_PAY_RATIO,
	j.PRESIDENT_TO_AVERAGE_PAY_RATIO AS PRESIDENT_TO_AVERAGE_PAY_RATIO
FROM `ipeds_2024_db`.`C2022_B` C2022B
INNER JOIN `ipeds_EF2022_temp` b ON C2022B.UNITID = b.UNITID
INNER JOIN `ipedsIC2022AssociateAndAbove` IC2022F ON C2022B.UNITID = IC2022F.UNITID
INNER JOIN `ipeds_2024_db`.`HD2022` HD2022 ON C2022B.UNITID = HD2022.UNITID
INNER JOIN `ipeds_SAL2022_IS_temp` e ON C2022B.UNITID = e.UNITID
INNER JOIN `ipeds_S2022_OC_temp` f ON C2022B.UNITID = f.UNITID
INNER JOIN `ipeds_S2022_IS_temp` g ON C2022B.UNITID = g.UNITID
INNER JOIN `cssYearly` css ON HD2022.OPEID = css.OPEID
LEFT JOIN `irs990_temp` j ON HD2022.EIN = j.EIN
WHERE C2022B.CSTOTLT >= 50 AND b.EFTOTAL >= 200
ORDER BY C2022B.`UNITID` ASC;

ALTER TABLE `merged_ipeds_css_irs`.`gf2024_final`
ADD PRIMARY KEY (`UNITID`);
