DROP TABLE IF EXISTS `merged_ipeds_css_irs`.`gf2024_final`;

CREATE TABLE `merged_ipeds_css_irs`.`gf2024_final` AS
WITH cssYearly AS (
	SELECT 
		OPEID,
		MAX(cssh.Total) AS SchoolPopulation,
		SUM(
			cssh.MURD20 +
			cssh.RAPE20 +
			cssh.FOND20 +
			cssh.INCE20 +
			cssh.STAT20 +
			cssh.ROBBE20 +
			cssh.AGG_A20 +
			cssh.BURGLA20 +
			cssh.VEHIC20 +
			cssh.ARSON20 +
			cssh.SIM_A20 +
			cssh.LAR_T20 +
			cssh.INTIM20 +
			cssh.VANDAL20 +
			cssh.MURD21 +
			cssh.RAPE21 +
			cssh.FOND21 +
			cssh.INCE21 +
			cssh.STAT21 +
			cssh.ROBBE21 +
			cssh.AGG_A21 +
			cssh.BURGLA21 +
			cssh.VEHIC21 +
			cssh.ARSON21 +
			cssh.SIM_A21 +
			cssh.LAR_T21 +
			cssh.INTIM21 +
			cssh.VANDAL21 +
			cssh.MURD22 +
			cssh.RAPE22 +
			cssh.FOND22 +
			cssh.INCE22 +
			cssh.STAT22 +
			cssh.ROBBE22 +
			cssh.AGG_A22 +
			cssh.BURGLA22 +
			cssh.VEHIC22 +
			cssh.ARSON22 +
			cssh.SIM_A22 +
			cssh.LAR_T22 +
			cssh.INTIM22 +
			cssh.VANDAL22
		) / 3 AS YEARLYHATECRIME,
		SUM(
			cssv.DOMEST20 +
			cssv.DATING20 +
			cssv.STALK20 +
			cssv.DOMEST21 +
			cssv.DATING21 +
			cssv.STALK21 +
			cssv.DOMEST22 +
			cssv.DATING22 +
			cssv.STALK22
		) / 3 AS YEARLYVAWA
	FROM `css`.`css_hate` cssh
	JOIN `css`.`css_vawa` cssv
	USING (OPEID)
	GROUP BY OPEID
),
ipedsS2022ISByAcademicRank AS (
	SELECT
		UNITID,
		
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLM ELSE 0 END) AS PROFMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRTOTLW ELSE 0 END) AS PROFWOMEN,
		SUM(CASE WHEN SISCAT = 101 THEN HRWHITT ELSE 0 END) AS PROFWHIT,
		SUM(CASE WHEN SISCAT = 101 THEN HRBKAAT ELSE 0 END) AS PROFBLAK,
		SUM(CASE WHEN SISCAT = 101 THEN HRASIAT ELSE 0 END) AS PROFASIA,
		SUM(CASE WHEN SISCAT = 101 THEN HRHISPT ELSE 0 END) AS PROFHISP,
		SUM(CASE WHEN SISCAT = 101 THEN HRNHPIT ELSE 0 END) AS PROFNHPI,
		SUM(CASE WHEN SISCAT = 101 THEN HRAIANT ELSE 0 END) AS PROFNAMC,
		SUM(CASE WHEN SISCAT = 101 THEN HRNRALT ELSE 0 END) AS PROFNRES,
		SUM(CASE WHEN SISCAT = 101 THEN HR2MORT ELSE 0 END) AS PROFTWOP,
		SUM(CASE WHEN SISCAT = 101 THEN HRUNKNT ELSE 0 END) AS PROFUNKN,
		
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLM ELSE 0 END) AS ASSOCIATEPROFMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRTOTLW ELSE 0 END) AS ASSOCIATEPROFWOMEN,
		SUM(CASE WHEN SISCAT = 102 THEN HRWHITT ELSE 0 END) AS ASSOCIATEPROFWHIT,
		SUM(CASE WHEN SISCAT = 102 THEN HRBKAAT ELSE 0 END) AS ASSOCIATEPROFBLAK,
		SUM(CASE WHEN SISCAT = 102 THEN HRASIAT ELSE 0 END) AS ASSOCIATEPROFASIA,
		SUM(CASE WHEN SISCAT = 102 THEN HRHISPT ELSE 0 END) AS ASSOCIATEPROFHISP,
		SUM(CASE WHEN SISCAT = 102 THEN HRNHPIT ELSE 0 END) AS ASSOCIATEPROFNHPI,
		SUM(CASE WHEN SISCAT = 102 THEN HRAIANT ELSE 0 END) AS ASSOCIATEPROFNAMC,
		SUM(CASE WHEN SISCAT = 102 THEN HRNRALT ELSE 0 END) AS ASSOCIATEPROFNRES,
		SUM(CASE WHEN SISCAT = 102 THEN HR2MORT ELSE 0 END) AS ASSOCIATEPROFTWOP,
		SUM(CASE WHEN SISCAT = 102 THEN HRUNKNT ELSE 0 END) AS ASSOCIATEPROFUNKN,
		
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLM ELSE 0 END) AS ASSISTANTPROFMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRTOTLW ELSE 0 END) AS ASSISTANTPROFWOMEN,
		SUM(CASE WHEN SISCAT = 103 THEN HRWHITT ELSE 0 END) AS ASSISTANTPROFWHIT,
		SUM(CASE WHEN SISCAT = 103 THEN HRBKAAT ELSE 0 END) AS ASSISTANTPROFBLAK,
		SUM(CASE WHEN SISCAT = 103 THEN HRASIAT ELSE 0 END) AS ASSISTANTPROFASIA,
		SUM(CASE WHEN SISCAT = 103 THEN HRHISPT ELSE 0 END) AS ASSISTANTPROFHISP,
		SUM(CASE WHEN SISCAT = 103 THEN HRNHPIT ELSE 0 END) AS ASSISTANTPROFNHPI,
		SUM(CASE WHEN SISCAT = 103 THEN HRAIANT ELSE 0 END) AS ASSISTANTPROFNAMC,
		SUM(CASE WHEN SISCAT = 103 THEN HRNRALT ELSE 0 END) AS ASSISTANTPROFNRES,
		SUM(CASE WHEN SISCAT = 103 THEN HR2MORT ELSE 0 END) AS ASSISTANTPROFTWOP,
		SUM(CASE WHEN SISCAT = 103 THEN HRUNKNT ELSE 0 END) AS ASSISTANTPROFUNKN,
		
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLM ELSE 0 END) AS INSTRUCTORMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRTOTLW ELSE 0 END) AS INSTRUCTORWOMEN,
		SUM(CASE WHEN SISCAT = 104 THEN HRWHITT ELSE 0 END) AS INSTRUCTORWHIT,
		SUM(CASE WHEN SISCAT = 104 THEN HRBKAAT ELSE 0 END) AS INSTRUCTORBLAK,
		SUM(CASE WHEN SISCAT = 104 THEN HRASIAT ELSE 0 END) AS INSTRUCTORASIA,
		SUM(CASE WHEN SISCAT = 104 THEN HRHISPT ELSE 0 END) AS INSTRUCTORHISP,
		SUM(CASE WHEN SISCAT = 104 THEN HRNHPIT ELSE 0 END) AS INSTRUCTORNHPI,
		SUM(CASE WHEN SISCAT = 104 THEN HRAIANT ELSE 0 END) AS INSTRUCTORNAMC,
		SUM(CASE WHEN SISCAT = 104 THEN HRNRALT ELSE 0 END) AS INSTRUCTORNRES,
		SUM(CASE WHEN SISCAT = 104 THEN HR2MORT ELSE 0 END) AS INSTRUCTORTWOP,
		SUM(CASE WHEN SISCAT = 104 THEN HRUNKNT ELSE 0 END) AS INSTRUCTORUNKN,
		
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLM ELSE 0 END) AS LECTUREMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRTOTLW ELSE 0 END) AS LECTUREWOMEN,
		SUM(CASE WHEN SISCAT = 105 THEN HRWHITT ELSE 0 END) AS LECTURERWHIT,
		SUM(CASE WHEN SISCAT = 105 THEN HRBKAAT ELSE 0 END) AS LECTURERBLAK,
		SUM(CASE WHEN SISCAT = 105 THEN HRASIAT ELSE 0 END) AS LECTURERASIA,
		SUM(CASE WHEN SISCAT = 105 THEN HRHISPT ELSE 0 END) AS LECTURERHISP,
		SUM(CASE WHEN SISCAT = 105 THEN HRNHPIT ELSE 0 END) AS LECTURERNHPI,
		SUM(CASE WHEN SISCAT = 105 THEN HRAIANT ELSE 0 END) AS LECTURERNAMC,
		SUM(CASE WHEN SISCAT = 105 THEN HRNRALT ELSE 0 END) AS LECTURERNRES,
		SUM(CASE WHEN SISCAT = 105 THEN HR2MORT ELSE 0 END) AS LECTURERTWOP,
		SUM(CASE WHEN SISCAT = 105 THEN HRUNKNT ELSE 0 END) AS LECTURERUNKN,
		
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLM ELSE 0 END) AS NORANKMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRTOTLW ELSE 0 END) AS NORANKWOMEN,
		SUM(CASE WHEN SISCAT = 106 THEN HRWHITT ELSE 0 END) AS NORANKWHIT,
		SUM(CASE WHEN SISCAT = 106 THEN HRBKAAT ELSE 0 END) AS NORANKBLAK,
		SUM(CASE WHEN SISCAT = 106 THEN HRASIAT ELSE 0 END) AS NORANKASIA,
		SUM(CASE WHEN SISCAT = 106 THEN HRHISPT ELSE 0 END) AS NORANKHISP,
		SUM(CASE WHEN SISCAT = 106 THEN HRNHPIT ELSE 0 END) AS NORANKNHPI,
		SUM(CASE WHEN SISCAT = 106 THEN HRAIANT ELSE 0 END) AS NORANKNAMC,
		SUM(CASE WHEN SISCAT = 106 THEN HRNRALT ELSE 0 END) AS NORANKNRES,
		SUM(CASE WHEN SISCAT = 106 THEN HR2MORT ELSE 0 END) AS NORANKTWOP,
		SUM(CASE WHEN SISCAT = 106 THEN HRUNKNT ELSE 0 END) AS NORANKUNKN,
	
	FROM `ipeds_2024_db`.`S2022_IS`
	WHERE `SISCAT` IN (101, 102, 103, 104, 105, 106)
	GROUP BY `UNITID`
	/*
	Though SISCAT is a concatenation of FACSTAT and ARANK (by the formula FACSTAT*10+ARANK), not every pairing of FACSTAT and ARANK is valid.
	Notably exceptions:
		SISCAT 1 is the entry for all full-time staff, and does not correspond to a FACSTAT category (The FACSTAT and ARANK values in that row are both 0). It is the sum of FACSTAT 100 and 500.
		FACSTAT 50 only matchers up with ARANK 0.
	To get the total number of academic staff in each category, use SISCAT 101,102...106

	Metadata:

	TYPE	VAL	DESCRIPTION
	FACSTAT	10	With faculty status, total
	FACSTAT	20	With faculty status, tenured
	FACSTAT	30	With faculty status, on tenure track
	FACSTAT	40	With faculty status not on tenure track/No tenure system, total
	FACSTAT	41	With faculty status not on tenure track/No tenure system, multi-year and indefinite contract
	FACSTAT	42	With faculty status not on tenure track/No tenure system, annual contract
	FACSTAT	43	With faculty status not on tenure track/No tenure system, less-than-annual contract
	FACSTAT	44	With faculty status not on tenure track/No tenure system, multi-year contract
	FACSTAT	45	With faculty status not on tenure track/No tenure system, indefinite contract
	FACSTAT	50	Without faculty status
	ARANK	0	All ranks
	ARANK	1	Professors
	ARANK	2	Associate professors
	ARANK	3	Assistant professors
	ARANK	4	Instructors
	ARANK	5	Lecturers
	ARANK	6	No academic rank
	SISCAT	100	Full-time instructional with faculty status
	SISCAT	101	Full-time instructional professors
	SISCAT	102	Full-time instructional associate professors
	SISCAT	103	Full-time instructional assistant professors
	SISCAT	104	Full-time instructional instructors
	SISCAT	105	Full-time instructional lecturers
	SISCAT	106	Full-time instructional no academic rank

	NAME	DESCRIPTION
	HRTOTLM	Grand total men
	HRTOTLW	Grand total women
	HRWHITT	White total
	HRBKAAT	Black or African American total
	HRASIAT	Asian total
	HRHISPT	Hispanic or Latino total
	HRNHPIT	Native Hawaiian or Other Pacific Islander total
	HRAIANT	American Indian or Alaska Native total
	HRNRALT	U.S. Nonresident total
	HR2MORT	Two or more races total
	HRUNKNT	Race/ethnicity unknown total
	*/
),
ipeds_S2022_OC_temp AS (
	SELECT 
		UNITID,
		SUM(HRTOTLT) AS HRTOTLT,
		SUM(HRTOTLM) AS HRTOTLM,
		SUM(HRTOTLW) AS HRTOTLW,
		SUM(HRASIAT) AS HRASIAT,
		SUM(HRASIAM) AS HRASIAM,
		SUM(HRASIAW) AS HRASIAW,
		SUM(HRBKAAT) AS HRBKAAT,
		SUM(HRBKAAM) AS HRBKAAM,
		SUM(HRBKAAW) AS HRBKAAW,
		SUM(HRHISPT) AS HRHISPT,
		SUM(HRHISPM) AS HRHISPM,
		SUM(HRHISPW) AS HRHISPW
	FROM `ipeds_2024_db`.`S2022_OC`
	WHERE `OCCUPCAT` IN (220, 230, 250, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 420, 490)
	GROUP BY UNITID
),
ipeds_SAL2022_IS_temp AS (
	SELECT *, 
	FROM `ipeds_2024_db`.`SAL2022_IS`
	WHERE `ARANK` = 7
),
ipedsIC2022AssociateAndAbove AS (
	SELECT *
	FROM `ipeds_2024_db`.`IC2022`
	WHERE (
			LEVEL3 = 1 OR
			LEVEL4 = 1 OR
			LEVEL5 = 1 OR
			LEVEL6 = 1 OR
			LEVEL7 = 1 OR
			LEVEL8 = 1 OR
			LEVEL17 = 1 OR
			LEVEL18 = 1 OR
			LEVEL19 = 1
	) AND `CNTLAFFI` IN (1, 3, 4)
),
ipeds_EF2022_temp AS (
SELECT * 
FROM `ipeds_2024_db`.`EF2022`
WHERE `EFLEVEL` IN (10)),
irs990_temp AS (
SELECT *
FROM (
	SELECT *,
		ROW_NUMBER() OVER (
			PARTITION BY `EIN` 
			ORDER BY `YEAR` DESC, `IRS_MONTH` DESC
		) AS rn
	FROM `irs990`.`Organizations`
) AS ranked
WHERE rn = 1)
-- Selecting columns --
SELECT
	C2022B.UNITID AS UNITID,
	HD2022.INSTNM AS INSTNM,
	HD2022.STABBR AS STATE,
	HD2022.EIN AS EIN,
	HD2022.OPEID AS OPEID,
	C2022B.CSTOTLT AS DEGREETOT,
	b.EFTOTAL AS ENROLLTOT,
	IC2022F.CNTLAFFI AS INSTFUNDINGTYPE,
	IC2022F.STUSRV8 AS HASDAYCARE,
	e.SAINSTM AS ACADEMICPOPM,
	e.SAINSTW AS ACADEMICPOPF,
	e.SAOUTLM AS SALARYTOTM,
	e.SAOUTLW AS SALARYTOTF,
	f.HRBKAAT AS NONACD_BLKPCT,
	f.HRHISPT AS NONACD_HSPPCT,
	f.HRASIAT AS NONACD_ASIAPCT,
	g.HRTOTLW_101 AS PROFWOMENPCT,
	g.HRTOTLW_102 AS ASSOCPROFWOMENPCT,
	g.HRTOTLW_200 AS TENUREWOMENPCT,
	g.HRBKAAW_101 AS BLACKPROFWOMENPCT,
	g.HRBKAAW_102 AS BLACKASSOCPROFWOMENPCT,
	g.HRBKAAW_200 AS BLACKTENUREWOMENPCT,
	g.HRHISPW_101 AS HISPANICPROFWOMENPCT,
	g.HRHISPW_102 AS HISPANICASSOCPROFWOMENPCT,
	g.HRHISPW_200 AS HISPANICTENUREWOMENPCT,
	g.HRASIAW_101 AS ASIANPROFWOMENPCT, 
	g.HRASIAW_102 AS ASIANASSOCPROFWOMENPCT,
	g.HRASIAW_200 AS ASIANTENUREWOMENPCT,



	css.YEARLYHATECRIME AS YEARLYHATECRIME,
	css.YEARLYHATECRIME * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYHATECRIME1K,
	css.YEARLYVAWA AS YEARLYVAWA,
	css.YEARLYVAWA * 1000 / NULLIF(css.SchoolPopulation, 0) AS YEARLYVAWA1K,
	j.PERCENTAGE_WOMEN_TRUSTEES AS PERCENTAGE_WOMEN_TRUSTEES,
	j.PERCENTAGE_WOMEN_KEY_EMPLOYEES AS PERCENTAGE_WOMEN_KEY_EMPLOYEES,
	j.WHISTLEBLOWER_POLICY AS WHISTLEBLOWER_POLICY,
	j.CEO_REVIEWED_COMPENSATION AS CEO_REVIEWED_COMPENSATION,
	j.OTHER_REVIEWED_COMPENSATION AS OTHER_REVIEWED_COMPENSATION,
	j.MALE_TO_FEMALE_PAY_RATIO AS MALE_TO_FEMALE_PAY_RATIO,
	j.PRESIDENT_TO_AVERAGE_PAY_RATIO AS PRESIDENT_TO_AVERAGE_PAY_RATIO
FROM `ipeds_2024_db`.`C2022_B` C2022B
INNER JOIN `ipeds_EF2022_temp` b ON C2022B.UNITID = b.UNITID
INNER JOIN `ipedsIC2022AssociateAndAbove` IC2022F ON C2022B.UNITID = IC2022F.UNITID
INNER JOIN `ipeds_2024_db`.`HD2022` HD2022 ON C2022B.UNITID = HD2022.UNITID
INNER JOIN `ipeds_SAL2022_IS_temp` e ON C2022B.UNITID = e.UNITID
INNER JOIN `ipeds_S2022_OC_temp` f ON C2022B.UNITID = f.UNITID
INNER JOIN `ipedsS2022ISByAcademicRank` S2022ISRank ON C2022B.UNITID = S2022ISRank.UNITID
INNER JOIN `cssYearly` css ON HD2022.OPEID = css.OPEID
LEFT JOIN `irs990_temp` j ON HD2022.EIN = j.EIN
WHERE C2022B.CSTOTLT >= 50 AND b.EFTOTAL >= 200
ORDER BY C2022B.`UNITID` ASC;

ALTER TABLE `merged_ipeds_css_irs`.`gf2024_final`
ADD PRIMARY KEY (`UNITID`);
